/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import * as operations from "../operations/index.js";
import { BereachError } from "./bereach-error.js";

/**
 * The server encountered a situation it does not know how to handle.
 */
export type ArchiveConversationInternalServerErrorData = {
  success?: false | undefined;
  error: operations.ArchiveConversationInternalServerErrorError;
};

/**
 * The server encountered a situation it does not know how to handle.
 */
export class ArchiveConversationInternalServerError extends BereachError {
  success?: false | undefined;
  error: operations.ArchiveConversationInternalServerErrorError;

  /** The original data that was passed to this error instance. */
  data$: ArchiveConversationInternalServerErrorData;

  constructor(
    err: ArchiveConversationInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "ArchiveConversationInternalServerError";
  }
}

/**
 * Rate limit exceeded. Read error.retryAfter for the wait time in seconds.
 */
export type ArchiveConversationTooManyRequestsErrorData = {
  success?: false | undefined;
  error: operations.ArchiveConversationTooManyRequestsError;
};

/**
 * Rate limit exceeded. Read error.retryAfter for the wait time in seconds.
 */
export class ArchiveConversationTooManyRequestsError extends BereachError {
  success?: false | undefined;
  error: operations.ArchiveConversationTooManyRequestsError;

  /** The original data that was passed to this error instance. */
  data$: ArchiveConversationTooManyRequestsErrorData;

  constructor(
    err: ArchiveConversationTooManyRequestsErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "ArchiveConversationTooManyRequestsError";
  }
}

/**
 * The request was well-formed but was unable to be followed due to semantic errors.
 */
export type ArchiveConversationUnprocessableEntityErrorData = {
  success?: false | undefined;
  error: operations.ArchiveConversationUnprocessableEntityError;
};

/**
 * The request was well-formed but was unable to be followed due to semantic errors.
 */
export class ArchiveConversationUnprocessableEntityError extends BereachError {
  success?: false | undefined;
  error: operations.ArchiveConversationUnprocessableEntityError;

  /** The original data that was passed to this error instance. */
  data$: ArchiveConversationUnprocessableEntityErrorData;

  constructor(
    err: ArchiveConversationUnprocessableEntityErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "ArchiveConversationUnprocessableEntityError";
  }
}

/**
 * The requested content has been permanently deleted from the server.
 */
export type ArchiveConversationGoneErrorData = {
  success?: false | undefined;
  error: operations.ArchiveConversationGoneError;
};

/**
 * The requested content has been permanently deleted from the server.
 */
export class ArchiveConversationGoneError extends BereachError {
  success?: false | undefined;
  error: operations.ArchiveConversationGoneError;

  /** The original data that was passed to this error instance. */
  data$: ArchiveConversationGoneErrorData;

  constructor(
    err: ArchiveConversationGoneErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "ArchiveConversationGoneError";
  }
}

/**
 * The request conflicts with the current state of the server.
 */
export type ArchiveConversationConflictErrorData = {
  success?: false | undefined;
  error: operations.ArchiveConversationConflictError;
};

/**
 * The request conflicts with the current state of the server.
 */
export class ArchiveConversationConflictError extends BereachError {
  success?: false | undefined;
  error: operations.ArchiveConversationConflictError;

  /** The original data that was passed to this error instance. */
  data$: ArchiveConversationConflictErrorData;

  constructor(
    err: ArchiveConversationConflictErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "ArchiveConversationConflictError";
  }
}

/**
 * The server cannot find the requested resource.
 */
export type ArchiveConversationNotFoundErrorData = {
  success?: false | undefined;
  error: operations.ArchiveConversationNotFoundError;
};

/**
 * The server cannot find the requested resource.
 */
export class ArchiveConversationNotFoundError extends BereachError {
  success?: false | undefined;
  error: operations.ArchiveConversationNotFoundError;

  /** The original data that was passed to this error instance. */
  data$: ArchiveConversationNotFoundErrorData;

  constructor(
    err: ArchiveConversationNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "ArchiveConversationNotFoundError";
  }
}

/**
 * The client does not have access rights to the content.
 */
export type ArchiveConversationForbiddenErrorData = {
  success?: false | undefined;
  error: operations.ArchiveConversationForbiddenError;
};

/**
 * The client does not have access rights to the content.
 */
export class ArchiveConversationForbiddenError extends BereachError {
  success?: false | undefined;
  error: operations.ArchiveConversationForbiddenError;

  /** The original data that was passed to this error instance. */
  data$: ArchiveConversationForbiddenErrorData;

  constructor(
    err: ArchiveConversationForbiddenErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "ArchiveConversationForbiddenError";
  }
}

/**
 * Although HTTP specifies "unauthorized", this response means "unauthenticated". Authenticate to continue.
 */
export type ArchiveConversationUnauthorizedErrorData = {
  success?: false | undefined;
  error: operations.ArchiveConversationUnauthorizedError;
};

/**
 * Although HTTP specifies "unauthorized", this response means "unauthenticated". Authenticate to continue.
 */
export class ArchiveConversationUnauthorizedError extends BereachError {
  success?: false | undefined;
  error: operations.ArchiveConversationUnauthorizedError;

  /** The original data that was passed to this error instance. */
  data$: ArchiveConversationUnauthorizedErrorData;

  constructor(
    err: ArchiveConversationUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "ArchiveConversationUnauthorizedError";
  }
}

/**
 * The server cannot or will not process the request due to something that is perceived to be a client error.
 */
export type ArchiveConversationBadRequestErrorData = {
  success?: false | undefined;
  error: operations.ArchiveConversationBadRequestError;
};

/**
 * The server cannot or will not process the request due to something that is perceived to be a client error.
 */
export class ArchiveConversationBadRequestError extends BereachError {
  success?: false | undefined;
  error: operations.ArchiveConversationBadRequestError;

  /** The original data that was passed to this error instance. */
  data$: ArchiveConversationBadRequestErrorData;

  constructor(
    err: ArchiveConversationBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "ArchiveConversationBadRequestError";
  }
}

/** @internal */
export const ArchiveConversationInternalServerError$inboundSchema:
  z.ZodMiniType<ArchiveConversationInternalServerError, unknown> = z.pipe(
    z.object({
      success: z._default(types.literal(false), false),
      error: z.lazy(() =>
        operations.ArchiveConversationInternalServerErrorError$inboundSchema
      ),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new ArchiveConversationInternalServerError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const ArchiveConversationTooManyRequestsError$inboundSchema:
  z.ZodMiniType<ArchiveConversationTooManyRequestsError, unknown> = z.pipe(
    z.object({
      success: z._default(types.literal(false), false),
      error: z.lazy(() =>
        operations.ArchiveConversationTooManyRequestsError$inboundSchema
      ),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new ArchiveConversationTooManyRequestsError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const ArchiveConversationUnprocessableEntityError$inboundSchema:
  z.ZodMiniType<ArchiveConversationUnprocessableEntityError, unknown> = z.pipe(
    z.object({
      success: z._default(types.literal(false), false),
      error: z.lazy(() =>
        operations.ArchiveConversationUnprocessableEntityError$inboundSchema
      ),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new ArchiveConversationUnprocessableEntityError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const ArchiveConversationGoneError$inboundSchema: z.ZodMiniType<
  ArchiveConversationGoneError,
  unknown
> = z.pipe(
  z.object({
    success: z._default(types.literal(false), false),
    error: z.lazy(() => operations.ArchiveConversationGoneError$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new ArchiveConversationGoneError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const ArchiveConversationConflictError$inboundSchema: z.ZodMiniType<
  ArchiveConversationConflictError,
  unknown
> = z.pipe(
  z.object({
    success: z._default(types.literal(false), false),
    error: z.lazy(() =>
      operations.ArchiveConversationConflictError$inboundSchema
    ),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new ArchiveConversationConflictError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const ArchiveConversationNotFoundError$inboundSchema: z.ZodMiniType<
  ArchiveConversationNotFoundError,
  unknown
> = z.pipe(
  z.object({
    success: z._default(types.literal(false), false),
    error: z.lazy(() =>
      operations.ArchiveConversationNotFoundError$inboundSchema
    ),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new ArchiveConversationNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const ArchiveConversationForbiddenError$inboundSchema: z.ZodMiniType<
  ArchiveConversationForbiddenError,
  unknown
> = z.pipe(
  z.object({
    success: z._default(types.literal(false), false),
    error: z.lazy(() =>
      operations.ArchiveConversationForbiddenError$inboundSchema
    ),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new ArchiveConversationForbiddenError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const ArchiveConversationUnauthorizedError$inboundSchema: z.ZodMiniType<
  ArchiveConversationUnauthorizedError,
  unknown
> = z.pipe(
  z.object({
    success: z._default(types.literal(false), false),
    error: z.lazy(() =>
      operations.ArchiveConversationUnauthorizedError$inboundSchema
    ),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new ArchiveConversationUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const ArchiveConversationBadRequestError$inboundSchema: z.ZodMiniType<
  ArchiveConversationBadRequestError,
  unknown
> = z.pipe(
  z.object({
    success: z._default(types.literal(false), false),
    error: z.lazy(() =>
      operations.ArchiveConversationBadRequestError$inboundSchema
    ),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new ArchiveConversationBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
