/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import * as operations from "../operations/index.js";
import { BereachError } from "./bereach-error.js";

/**
 * The server encountered a situation it does not know how to handle.
 */
export type InternalServerErrorData = {
  success?: false | undefined;
  error: operations.CollectLinkedInLikesInternalServerErrorError;
};

/**
 * The server encountered a situation it does not know how to handle.
 */
export class InternalServerError extends BereachError {
  success?: false | undefined;
  error: operations.CollectLinkedInLikesInternalServerErrorError;

  /** The original data that was passed to this error instance. */
  data$: InternalServerErrorData;

  constructor(
    err: InternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "InternalServerError";
  }
}

/**
 * Rate limit exceeded. Read error.retryAfter for the wait time in seconds.
 */
export type TooManyRequestsErrorData = {
  success?: false | undefined;
  error: operations.CollectLinkedInLikesTooManyRequestsError;
};

/**
 * Rate limit exceeded. Read error.retryAfter for the wait time in seconds.
 */
export class TooManyRequestsError extends BereachError {
  success?: false | undefined;
  error: operations.CollectLinkedInLikesTooManyRequestsError;

  /** The original data that was passed to this error instance. */
  data$: TooManyRequestsErrorData;

  constructor(
    err: TooManyRequestsErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "TooManyRequestsError";
  }
}

/**
 * The request was well-formed but was unable to be followed due to semantic errors.
 */
export type UnprocessableEntityErrorData = {
  success?: false | undefined;
  error: operations.CollectLinkedInLikesUnprocessableEntityError;
};

/**
 * The request was well-formed but was unable to be followed due to semantic errors.
 */
export class UnprocessableEntityError extends BereachError {
  success?: false | undefined;
  error: operations.CollectLinkedInLikesUnprocessableEntityError;

  /** The original data that was passed to this error instance. */
  data$: UnprocessableEntityErrorData;

  constructor(
    err: UnprocessableEntityErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "UnprocessableEntityError";
  }
}

/**
 * The requested content has been permanently deleted from the server.
 */
export type GoneErrorData = {
  success?: false | undefined;
  error: operations.CollectLinkedInLikesGoneError;
};

/**
 * The requested content has been permanently deleted from the server.
 */
export class GoneError extends BereachError {
  success?: false | undefined;
  error: operations.CollectLinkedInLikesGoneError;

  /** The original data that was passed to this error instance. */
  data$: GoneErrorData;

  constructor(
    err: GoneErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "GoneError";
  }
}

/**
 * The request conflicts with the current state of the server.
 */
export type ConflictErrorData = {
  success?: false | undefined;
  error: operations.CollectLinkedInLikesConflictError;
};

/**
 * The request conflicts with the current state of the server.
 */
export class ConflictError extends BereachError {
  success?: false | undefined;
  error: operations.CollectLinkedInLikesConflictError;

  /** The original data that was passed to this error instance. */
  data$: ConflictErrorData;

  constructor(
    err: ConflictErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "ConflictError";
  }
}

/**
 * The server cannot find the requested resource.
 */
export type NotFoundErrorData = {
  success?: false | undefined;
  error: operations.CollectLinkedInLikesNotFoundError;
};

/**
 * The server cannot find the requested resource.
 */
export class NotFoundError extends BereachError {
  success?: false | undefined;
  error: operations.CollectLinkedInLikesNotFoundError;

  /** The original data that was passed to this error instance. */
  data$: NotFoundErrorData;

  constructor(
    err: NotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "NotFoundError";
  }
}

/**
 * The client does not have access rights to the content.
 */
export type ForbiddenErrorData = {
  success?: false | undefined;
  error: operations.CollectLinkedInLikesForbiddenError;
};

/**
 * The client does not have access rights to the content.
 */
export class ForbiddenError extends BereachError {
  success?: false | undefined;
  error: operations.CollectLinkedInLikesForbiddenError;

  /** The original data that was passed to this error instance. */
  data$: ForbiddenErrorData;

  constructor(
    err: ForbiddenErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "ForbiddenError";
  }
}

/**
 * Although HTTP specifies "unauthorized", this response means "unauthenticated". Authenticate to continue.
 */
export type UnauthorizedErrorData = {
  success?: false | undefined;
  error: operations.CollectLinkedInLikesUnauthorizedError;
};

/**
 * Although HTTP specifies "unauthorized", this response means "unauthenticated". Authenticate to continue.
 */
export class UnauthorizedError extends BereachError {
  success?: false | undefined;
  error: operations.CollectLinkedInLikesUnauthorizedError;

  /** The original data that was passed to this error instance. */
  data$: UnauthorizedErrorData;

  constructor(
    err: UnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "UnauthorizedError";
  }
}

/**
 * The server cannot or will not process the request due to something that is perceived to be a client error.
 */
export type BadRequestErrorData = {
  success?: false | undefined;
  error: operations.CollectLinkedInLikesBadRequestError;
};

/**
 * The server cannot or will not process the request due to something that is perceived to be a client error.
 */
export class BadRequestError extends BereachError {
  success?: false | undefined;
  error: operations.CollectLinkedInLikesBadRequestError;

  /** The original data that was passed to this error instance. */
  data$: BadRequestErrorData;

  constructor(
    err: BadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "BadRequestError";
  }
}

/** @internal */
export const InternalServerError$inboundSchema: z.ZodMiniType<
  InternalServerError,
  unknown
> = z.pipe(
  z.object({
    success: z._default(types.literal(false), false),
    error:
      operations.CollectLinkedInLikesInternalServerErrorError$inboundSchema,
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new InternalServerError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const TooManyRequestsError$inboundSchema: z.ZodMiniType<
  TooManyRequestsError,
  unknown
> = z.pipe(
  z.object({
    success: z._default(types.literal(false), false),
    error: operations.CollectLinkedInLikesTooManyRequestsError$inboundSchema,
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new TooManyRequestsError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const UnprocessableEntityError$inboundSchema: z.ZodMiniType<
  UnprocessableEntityError,
  unknown
> = z.pipe(
  z.object({
    success: z._default(types.literal(false), false),
    error:
      operations.CollectLinkedInLikesUnprocessableEntityError$inboundSchema,
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new UnprocessableEntityError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const GoneError$inboundSchema: z.ZodMiniType<GoneError, unknown> = z
  .pipe(
    z.object({
      success: z._default(types.literal(false), false),
      error: operations.CollectLinkedInLikesGoneError$inboundSchema,
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new GoneError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const ConflictError$inboundSchema: z.ZodMiniType<
  ConflictError,
  unknown
> = z.pipe(
  z.object({
    success: z._default(types.literal(false), false),
    error: operations.CollectLinkedInLikesConflictError$inboundSchema,
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new ConflictError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const NotFoundError$inboundSchema: z.ZodMiniType<
  NotFoundError,
  unknown
> = z.pipe(
  z.object({
    success: z._default(types.literal(false), false),
    error: operations.CollectLinkedInLikesNotFoundError$inboundSchema,
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new NotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const ForbiddenError$inboundSchema: z.ZodMiniType<
  ForbiddenError,
  unknown
> = z.pipe(
  z.object({
    success: z._default(types.literal(false), false),
    error: operations.CollectLinkedInLikesForbiddenError$inboundSchema,
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new ForbiddenError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const UnauthorizedError$inboundSchema: z.ZodMiniType<
  UnauthorizedError,
  unknown
> = z.pipe(
  z.object({
    success: z._default(types.literal(false), false),
    error: operations.CollectLinkedInLikesUnauthorizedError$inboundSchema,
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new UnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const BadRequestError$inboundSchema: z.ZodMiniType<
  BadRequestError,
  unknown
> = z.pipe(
  z.object({
    success: z._default(types.literal(false), false),
    error: operations.CollectLinkedInLikesBadRequestError$inboundSchema,
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new BadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
