/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import * as operations from "../operations/index.js";
import { BereachError } from "./bereach-error.js";

/**
 * The server encountered a situation it does not know how to handle.
 */
export type GetUnreadCountInternalServerErrorData = {
  success?: false | undefined;
  error: operations.GetUnreadCountInternalServerErrorError;
};

/**
 * The server encountered a situation it does not know how to handle.
 */
export class GetUnreadCountInternalServerError extends BereachError {
  success?: false | undefined;
  error: operations.GetUnreadCountInternalServerErrorError;

  /** The original data that was passed to this error instance. */
  data$: GetUnreadCountInternalServerErrorData;

  constructor(
    err: GetUnreadCountInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "GetUnreadCountInternalServerError";
  }
}

/**
 * Rate limit exceeded. Read error.retryAfter for the wait time in seconds.
 */
export type GetUnreadCountTooManyRequestsErrorData = {
  success?: false | undefined;
  error: operations.GetUnreadCountTooManyRequestsError;
};

/**
 * Rate limit exceeded. Read error.retryAfter for the wait time in seconds.
 */
export class GetUnreadCountTooManyRequestsError extends BereachError {
  success?: false | undefined;
  error: operations.GetUnreadCountTooManyRequestsError;

  /** The original data that was passed to this error instance. */
  data$: GetUnreadCountTooManyRequestsErrorData;

  constructor(
    err: GetUnreadCountTooManyRequestsErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "GetUnreadCountTooManyRequestsError";
  }
}

/**
 * The request was well-formed but was unable to be followed due to semantic errors.
 */
export type GetUnreadCountUnprocessableEntityErrorData = {
  success?: false | undefined;
  error: operations.GetUnreadCountUnprocessableEntityError;
};

/**
 * The request was well-formed but was unable to be followed due to semantic errors.
 */
export class GetUnreadCountUnprocessableEntityError extends BereachError {
  success?: false | undefined;
  error: operations.GetUnreadCountUnprocessableEntityError;

  /** The original data that was passed to this error instance. */
  data$: GetUnreadCountUnprocessableEntityErrorData;

  constructor(
    err: GetUnreadCountUnprocessableEntityErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "GetUnreadCountUnprocessableEntityError";
  }
}

/**
 * The requested content has been permanently deleted from the server.
 */
export type GetUnreadCountGoneErrorData = {
  success?: false | undefined;
  error: operations.GetUnreadCountGoneError;
};

/**
 * The requested content has been permanently deleted from the server.
 */
export class GetUnreadCountGoneError extends BereachError {
  success?: false | undefined;
  error: operations.GetUnreadCountGoneError;

  /** The original data that was passed to this error instance. */
  data$: GetUnreadCountGoneErrorData;

  constructor(
    err: GetUnreadCountGoneErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "GetUnreadCountGoneError";
  }
}

/**
 * The request conflicts with the current state of the server.
 */
export type GetUnreadCountConflictErrorData = {
  success?: false | undefined;
  error: operations.GetUnreadCountConflictError;
};

/**
 * The request conflicts with the current state of the server.
 */
export class GetUnreadCountConflictError extends BereachError {
  success?: false | undefined;
  error: operations.GetUnreadCountConflictError;

  /** The original data that was passed to this error instance. */
  data$: GetUnreadCountConflictErrorData;

  constructor(
    err: GetUnreadCountConflictErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "GetUnreadCountConflictError";
  }
}

/**
 * The server cannot find the requested resource.
 */
export type GetUnreadCountNotFoundErrorData = {
  success?: false | undefined;
  error: operations.GetUnreadCountNotFoundError;
};

/**
 * The server cannot find the requested resource.
 */
export class GetUnreadCountNotFoundError extends BereachError {
  success?: false | undefined;
  error: operations.GetUnreadCountNotFoundError;

  /** The original data that was passed to this error instance. */
  data$: GetUnreadCountNotFoundErrorData;

  constructor(
    err: GetUnreadCountNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "GetUnreadCountNotFoundError";
  }
}

/**
 * The client does not have access rights to the content.
 */
export type GetUnreadCountForbiddenErrorData = {
  success?: false | undefined;
  error: operations.GetUnreadCountForbiddenError;
};

/**
 * The client does not have access rights to the content.
 */
export class GetUnreadCountForbiddenError extends BereachError {
  success?: false | undefined;
  error: operations.GetUnreadCountForbiddenError;

  /** The original data that was passed to this error instance. */
  data$: GetUnreadCountForbiddenErrorData;

  constructor(
    err: GetUnreadCountForbiddenErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "GetUnreadCountForbiddenError";
  }
}

/**
 * Although HTTP specifies "unauthorized", this response means "unauthenticated". Authenticate to continue.
 */
export type GetUnreadCountUnauthorizedErrorData = {
  success?: false | undefined;
  error: operations.GetUnreadCountUnauthorizedError;
};

/**
 * Although HTTP specifies "unauthorized", this response means "unauthenticated". Authenticate to continue.
 */
export class GetUnreadCountUnauthorizedError extends BereachError {
  success?: false | undefined;
  error: operations.GetUnreadCountUnauthorizedError;

  /** The original data that was passed to this error instance. */
  data$: GetUnreadCountUnauthorizedErrorData;

  constructor(
    err: GetUnreadCountUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "GetUnreadCountUnauthorizedError";
  }
}

/**
 * The server cannot or will not process the request due to something that is perceived to be a client error.
 */
export type GetUnreadCountBadRequestErrorData = {
  success?: false | undefined;
  error: operations.GetUnreadCountBadRequestError;
};

/**
 * The server cannot or will not process the request due to something that is perceived to be a client error.
 */
export class GetUnreadCountBadRequestError extends BereachError {
  success?: false | undefined;
  error: operations.GetUnreadCountBadRequestError;

  /** The original data that was passed to this error instance. */
  data$: GetUnreadCountBadRequestErrorData;

  constructor(
    err: GetUnreadCountBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "GetUnreadCountBadRequestError";
  }
}

/** @internal */
export const GetUnreadCountInternalServerError$inboundSchema: z.ZodMiniType<
  GetUnreadCountInternalServerError,
  unknown
> = z.pipe(
  z.object({
    success: z._default(types.literal(false), false),
    error: z.lazy(() =>
      operations.GetUnreadCountInternalServerErrorError$inboundSchema
    ),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetUnreadCountInternalServerError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const GetUnreadCountTooManyRequestsError$inboundSchema: z.ZodMiniType<
  GetUnreadCountTooManyRequestsError,
  unknown
> = z.pipe(
  z.object({
    success: z._default(types.literal(false), false),
    error: z.lazy(() =>
      operations.GetUnreadCountTooManyRequestsError$inboundSchema
    ),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetUnreadCountTooManyRequestsError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const GetUnreadCountUnprocessableEntityError$inboundSchema:
  z.ZodMiniType<GetUnreadCountUnprocessableEntityError, unknown> = z.pipe(
    z.object({
      success: z._default(types.literal(false), false),
      error: z.lazy(() =>
        operations.GetUnreadCountUnprocessableEntityError$inboundSchema
      ),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new GetUnreadCountUnprocessableEntityError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const GetUnreadCountGoneError$inboundSchema: z.ZodMiniType<
  GetUnreadCountGoneError,
  unknown
> = z.pipe(
  z.object({
    success: z._default(types.literal(false), false),
    error: z.lazy(() => operations.GetUnreadCountGoneError$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetUnreadCountGoneError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const GetUnreadCountConflictError$inboundSchema: z.ZodMiniType<
  GetUnreadCountConflictError,
  unknown
> = z.pipe(
  z.object({
    success: z._default(types.literal(false), false),
    error: z.lazy(() => operations.GetUnreadCountConflictError$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetUnreadCountConflictError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const GetUnreadCountNotFoundError$inboundSchema: z.ZodMiniType<
  GetUnreadCountNotFoundError,
  unknown
> = z.pipe(
  z.object({
    success: z._default(types.literal(false), false),
    error: z.lazy(() => operations.GetUnreadCountNotFoundError$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetUnreadCountNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const GetUnreadCountForbiddenError$inboundSchema: z.ZodMiniType<
  GetUnreadCountForbiddenError,
  unknown
> = z.pipe(
  z.object({
    success: z._default(types.literal(false), false),
    error: z.lazy(() => operations.GetUnreadCountForbiddenError$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetUnreadCountForbiddenError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const GetUnreadCountUnauthorizedError$inboundSchema: z.ZodMiniType<
  GetUnreadCountUnauthorizedError,
  unknown
> = z.pipe(
  z.object({
    success: z._default(types.literal(false), false),
    error: z.lazy(() =>
      operations.GetUnreadCountUnauthorizedError$inboundSchema
    ),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetUnreadCountUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const GetUnreadCountBadRequestError$inboundSchema: z.ZodMiniType<
  GetUnreadCountBadRequestError,
  unknown
> = z.pipe(
  z.object({
    success: z._default(types.literal(false), false),
    error: z.lazy(() => operations.GetUnreadCountBadRequestError$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetUnreadCountBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
