/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import * as operations from "../operations/index.js";
import { BereachError } from "./bereach-error.js";

/**
 * The server encountered a situation it does not know how to handle.
 */
export type GetCompanyPagePermissionsInternalServerErrorData = {
  success?: false | undefined;
  error: operations.GetCompanyPagePermissionsInternalServerErrorError;
};

/**
 * The server encountered a situation it does not know how to handle.
 */
export class GetCompanyPagePermissionsInternalServerError extends BereachError {
  success?: false | undefined;
  error: operations.GetCompanyPagePermissionsInternalServerErrorError;

  /** The original data that was passed to this error instance. */
  data$: GetCompanyPagePermissionsInternalServerErrorData;

  constructor(
    err: GetCompanyPagePermissionsInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "GetCompanyPagePermissionsInternalServerError";
  }
}

/**
 * Rate limit exceeded. Read error.retryAfter for the wait time in seconds.
 */
export type GetCompanyPagePermissionsTooManyRequestsErrorData = {
  success?: false | undefined;
  error: operations.GetCompanyPagePermissionsTooManyRequestsError;
};

/**
 * Rate limit exceeded. Read error.retryAfter for the wait time in seconds.
 */
export class GetCompanyPagePermissionsTooManyRequestsError
  extends BereachError
{
  success?: false | undefined;
  error: operations.GetCompanyPagePermissionsTooManyRequestsError;

  /** The original data that was passed to this error instance. */
  data$: GetCompanyPagePermissionsTooManyRequestsErrorData;

  constructor(
    err: GetCompanyPagePermissionsTooManyRequestsErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "GetCompanyPagePermissionsTooManyRequestsError";
  }
}

/**
 * The request was well-formed but was unable to be followed due to semantic errors.
 */
export type GetCompanyPagePermissionsUnprocessableEntityErrorData = {
  success?: false | undefined;
  error: operations.GetCompanyPagePermissionsUnprocessableEntityError;
};

/**
 * The request was well-formed but was unable to be followed due to semantic errors.
 */
export class GetCompanyPagePermissionsUnprocessableEntityError
  extends BereachError
{
  success?: false | undefined;
  error: operations.GetCompanyPagePermissionsUnprocessableEntityError;

  /** The original data that was passed to this error instance. */
  data$: GetCompanyPagePermissionsUnprocessableEntityErrorData;

  constructor(
    err: GetCompanyPagePermissionsUnprocessableEntityErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "GetCompanyPagePermissionsUnprocessableEntityError";
  }
}

/**
 * The requested content has been permanently deleted from the server.
 */
export type GetCompanyPagePermissionsGoneErrorData = {
  success?: false | undefined;
  error: operations.GetCompanyPagePermissionsGoneError;
};

/**
 * The requested content has been permanently deleted from the server.
 */
export class GetCompanyPagePermissionsGoneError extends BereachError {
  success?: false | undefined;
  error: operations.GetCompanyPagePermissionsGoneError;

  /** The original data that was passed to this error instance. */
  data$: GetCompanyPagePermissionsGoneErrorData;

  constructor(
    err: GetCompanyPagePermissionsGoneErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "GetCompanyPagePermissionsGoneError";
  }
}

/**
 * The request conflicts with the current state of the server.
 */
export type GetCompanyPagePermissionsConflictErrorData = {
  success?: false | undefined;
  error: operations.GetCompanyPagePermissionsConflictError;
};

/**
 * The request conflicts with the current state of the server.
 */
export class GetCompanyPagePermissionsConflictError extends BereachError {
  success?: false | undefined;
  error: operations.GetCompanyPagePermissionsConflictError;

  /** The original data that was passed to this error instance. */
  data$: GetCompanyPagePermissionsConflictErrorData;

  constructor(
    err: GetCompanyPagePermissionsConflictErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "GetCompanyPagePermissionsConflictError";
  }
}

/**
 * The server cannot find the requested resource.
 */
export type GetCompanyPagePermissionsNotFoundErrorData = {
  success?: false | undefined;
  error: operations.GetCompanyPagePermissionsNotFoundError;
};

/**
 * The server cannot find the requested resource.
 */
export class GetCompanyPagePermissionsNotFoundError extends BereachError {
  success?: false | undefined;
  error: operations.GetCompanyPagePermissionsNotFoundError;

  /** The original data that was passed to this error instance. */
  data$: GetCompanyPagePermissionsNotFoundErrorData;

  constructor(
    err: GetCompanyPagePermissionsNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "GetCompanyPagePermissionsNotFoundError";
  }
}

/**
 * The client does not have access rights to the content.
 */
export type GetCompanyPagePermissionsForbiddenErrorData = {
  success?: false | undefined;
  error: operations.GetCompanyPagePermissionsForbiddenError;
};

/**
 * The client does not have access rights to the content.
 */
export class GetCompanyPagePermissionsForbiddenError extends BereachError {
  success?: false | undefined;
  error: operations.GetCompanyPagePermissionsForbiddenError;

  /** The original data that was passed to this error instance. */
  data$: GetCompanyPagePermissionsForbiddenErrorData;

  constructor(
    err: GetCompanyPagePermissionsForbiddenErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "GetCompanyPagePermissionsForbiddenError";
  }
}

/**
 * Although HTTP specifies "unauthorized", this response means "unauthenticated". Authenticate to continue.
 */
export type GetCompanyPagePermissionsUnauthorizedErrorData = {
  success?: false | undefined;
  error: operations.GetCompanyPagePermissionsUnauthorizedError;
};

/**
 * Although HTTP specifies "unauthorized", this response means "unauthenticated". Authenticate to continue.
 */
export class GetCompanyPagePermissionsUnauthorizedError extends BereachError {
  success?: false | undefined;
  error: operations.GetCompanyPagePermissionsUnauthorizedError;

  /** The original data that was passed to this error instance. */
  data$: GetCompanyPagePermissionsUnauthorizedErrorData;

  constructor(
    err: GetCompanyPagePermissionsUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "GetCompanyPagePermissionsUnauthorizedError";
  }
}

/**
 * The server cannot or will not process the request due to something that is perceived to be a client error.
 */
export type GetCompanyPagePermissionsBadRequestErrorData = {
  success?: false | undefined;
  error: operations.GetCompanyPagePermissionsBadRequestError;
};

/**
 * The server cannot or will not process the request due to something that is perceived to be a client error.
 */
export class GetCompanyPagePermissionsBadRequestError extends BereachError {
  success?: false | undefined;
  error: operations.GetCompanyPagePermissionsBadRequestError;

  /** The original data that was passed to this error instance. */
  data$: GetCompanyPagePermissionsBadRequestErrorData;

  constructor(
    err: GetCompanyPagePermissionsBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "GetCompanyPagePermissionsBadRequestError";
  }
}

/** @internal */
export const GetCompanyPagePermissionsInternalServerError$inboundSchema:
  z.ZodMiniType<GetCompanyPagePermissionsInternalServerError, unknown> = z.pipe(
    z.object({
      success: z._default(types.literal(false), false),
      error: z.lazy(() =>
        operations
          .GetCompanyPagePermissionsInternalServerErrorError$inboundSchema
      ),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new GetCompanyPagePermissionsInternalServerError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const GetCompanyPagePermissionsTooManyRequestsError$inboundSchema:
  z.ZodMiniType<GetCompanyPagePermissionsTooManyRequestsError, unknown> = z
    .pipe(
      z.object({
        success: z._default(types.literal(false), false),
        error: z.lazy(() =>
          operations.GetCompanyPagePermissionsTooManyRequestsError$inboundSchema
        ),
        request$: z.custom<Request>(x => x instanceof Request),
        response$: z.custom<Response>(x => x instanceof Response),
        body$: z.string(),
      }),
      z.transform((v) => {
        return new GetCompanyPagePermissionsTooManyRequestsError(v, {
          request: v.request$,
          response: v.response$,
          body: v.body$,
        });
      }),
    );

/** @internal */
export const GetCompanyPagePermissionsUnprocessableEntityError$inboundSchema:
  z.ZodMiniType<GetCompanyPagePermissionsUnprocessableEntityError, unknown> = z
    .pipe(
      z.object({
        success: z._default(types.literal(false), false),
        error: z.lazy(() =>
          operations
            .GetCompanyPagePermissionsUnprocessableEntityError$inboundSchema
        ),
        request$: z.custom<Request>(x => x instanceof Request),
        response$: z.custom<Response>(x => x instanceof Response),
        body$: z.string(),
      }),
      z.transform((v) => {
        return new GetCompanyPagePermissionsUnprocessableEntityError(v, {
          request: v.request$,
          response: v.response$,
          body: v.body$,
        });
      }),
    );

/** @internal */
export const GetCompanyPagePermissionsGoneError$inboundSchema: z.ZodMiniType<
  GetCompanyPagePermissionsGoneError,
  unknown
> = z.pipe(
  z.object({
    success: z._default(types.literal(false), false),
    error: z.lazy(() =>
      operations.GetCompanyPagePermissionsGoneError$inboundSchema
    ),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetCompanyPagePermissionsGoneError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const GetCompanyPagePermissionsConflictError$inboundSchema:
  z.ZodMiniType<GetCompanyPagePermissionsConflictError, unknown> = z.pipe(
    z.object({
      success: z._default(types.literal(false), false),
      error: z.lazy(() =>
        operations.GetCompanyPagePermissionsConflictError$inboundSchema
      ),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new GetCompanyPagePermissionsConflictError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const GetCompanyPagePermissionsNotFoundError$inboundSchema:
  z.ZodMiniType<GetCompanyPagePermissionsNotFoundError, unknown> = z.pipe(
    z.object({
      success: z._default(types.literal(false), false),
      error: z.lazy(() =>
        operations.GetCompanyPagePermissionsNotFoundError$inboundSchema
      ),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new GetCompanyPagePermissionsNotFoundError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const GetCompanyPagePermissionsForbiddenError$inboundSchema:
  z.ZodMiniType<GetCompanyPagePermissionsForbiddenError, unknown> = z.pipe(
    z.object({
      success: z._default(types.literal(false), false),
      error: z.lazy(() =>
        operations.GetCompanyPagePermissionsForbiddenError$inboundSchema
      ),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new GetCompanyPagePermissionsForbiddenError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const GetCompanyPagePermissionsUnauthorizedError$inboundSchema:
  z.ZodMiniType<GetCompanyPagePermissionsUnauthorizedError, unknown> = z.pipe(
    z.object({
      success: z._default(types.literal(false), false),
      error: z.lazy(() =>
        operations.GetCompanyPagePermissionsUnauthorizedError$inboundSchema
      ),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new GetCompanyPagePermissionsUnauthorizedError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const GetCompanyPagePermissionsBadRequestError$inboundSchema:
  z.ZodMiniType<GetCompanyPagePermissionsBadRequestError, unknown> = z.pipe(
    z.object({
      success: z._default(types.literal(false), false),
      error: z.lazy(() =>
        operations.GetCompanyPagePermissionsBadRequestError$inboundSchema
      ),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new GetCompanyPagePermissionsBadRequestError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );
