/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import * as operations from "../operations/index.js";
import { BereachError } from "./bereach-error.js";

/**
 * The server encountered a situation it does not know how to handle.
 */
export type ListLinkedInCompanyPagesInternalServerErrorData = {
  success?: false | undefined;
  error: operations.ListLinkedInCompanyPagesInternalServerErrorError;
};

/**
 * The server encountered a situation it does not know how to handle.
 */
export class ListLinkedInCompanyPagesInternalServerError extends BereachError {
  success?: false | undefined;
  error: operations.ListLinkedInCompanyPagesInternalServerErrorError;

  /** The original data that was passed to this error instance. */
  data$: ListLinkedInCompanyPagesInternalServerErrorData;

  constructor(
    err: ListLinkedInCompanyPagesInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "ListLinkedInCompanyPagesInternalServerError";
  }
}

/**
 * Rate limit exceeded. Read error.retryAfter for the wait time in seconds.
 */
export type ListLinkedInCompanyPagesTooManyRequestsErrorData = {
  success?: false | undefined;
  error: operations.ListLinkedInCompanyPagesTooManyRequestsError;
};

/**
 * Rate limit exceeded. Read error.retryAfter for the wait time in seconds.
 */
export class ListLinkedInCompanyPagesTooManyRequestsError extends BereachError {
  success?: false | undefined;
  error: operations.ListLinkedInCompanyPagesTooManyRequestsError;

  /** The original data that was passed to this error instance. */
  data$: ListLinkedInCompanyPagesTooManyRequestsErrorData;

  constructor(
    err: ListLinkedInCompanyPagesTooManyRequestsErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "ListLinkedInCompanyPagesTooManyRequestsError";
  }
}

/**
 * The request was well-formed but was unable to be followed due to semantic errors.
 */
export type ListLinkedInCompanyPagesUnprocessableEntityErrorData = {
  success?: false | undefined;
  error: operations.ListLinkedInCompanyPagesUnprocessableEntityError;
};

/**
 * The request was well-formed but was unable to be followed due to semantic errors.
 */
export class ListLinkedInCompanyPagesUnprocessableEntityError
  extends BereachError
{
  success?: false | undefined;
  error: operations.ListLinkedInCompanyPagesUnprocessableEntityError;

  /** The original data that was passed to this error instance. */
  data$: ListLinkedInCompanyPagesUnprocessableEntityErrorData;

  constructor(
    err: ListLinkedInCompanyPagesUnprocessableEntityErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "ListLinkedInCompanyPagesUnprocessableEntityError";
  }
}

/**
 * The requested content has been permanently deleted from the server.
 */
export type ListLinkedInCompanyPagesGoneErrorData = {
  success?: false | undefined;
  error: operations.ListLinkedInCompanyPagesGoneError;
};

/**
 * The requested content has been permanently deleted from the server.
 */
export class ListLinkedInCompanyPagesGoneError extends BereachError {
  success?: false | undefined;
  error: operations.ListLinkedInCompanyPagesGoneError;

  /** The original data that was passed to this error instance. */
  data$: ListLinkedInCompanyPagesGoneErrorData;

  constructor(
    err: ListLinkedInCompanyPagesGoneErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "ListLinkedInCompanyPagesGoneError";
  }
}

/**
 * The request conflicts with the current state of the server.
 */
export type ListLinkedInCompanyPagesConflictErrorData = {
  success?: false | undefined;
  error: operations.ListLinkedInCompanyPagesConflictError;
};

/**
 * The request conflicts with the current state of the server.
 */
export class ListLinkedInCompanyPagesConflictError extends BereachError {
  success?: false | undefined;
  error: operations.ListLinkedInCompanyPagesConflictError;

  /** The original data that was passed to this error instance. */
  data$: ListLinkedInCompanyPagesConflictErrorData;

  constructor(
    err: ListLinkedInCompanyPagesConflictErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "ListLinkedInCompanyPagesConflictError";
  }
}

/**
 * The server cannot find the requested resource.
 */
export type ListLinkedInCompanyPagesNotFoundErrorData = {
  success?: false | undefined;
  error: operations.ListLinkedInCompanyPagesNotFoundError;
};

/**
 * The server cannot find the requested resource.
 */
export class ListLinkedInCompanyPagesNotFoundError extends BereachError {
  success?: false | undefined;
  error: operations.ListLinkedInCompanyPagesNotFoundError;

  /** The original data that was passed to this error instance. */
  data$: ListLinkedInCompanyPagesNotFoundErrorData;

  constructor(
    err: ListLinkedInCompanyPagesNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "ListLinkedInCompanyPagesNotFoundError";
  }
}

/**
 * The client does not have access rights to the content.
 */
export type ListLinkedInCompanyPagesForbiddenErrorData = {
  success?: false | undefined;
  error: operations.ListLinkedInCompanyPagesForbiddenError;
};

/**
 * The client does not have access rights to the content.
 */
export class ListLinkedInCompanyPagesForbiddenError extends BereachError {
  success?: false | undefined;
  error: operations.ListLinkedInCompanyPagesForbiddenError;

  /** The original data that was passed to this error instance. */
  data$: ListLinkedInCompanyPagesForbiddenErrorData;

  constructor(
    err: ListLinkedInCompanyPagesForbiddenErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "ListLinkedInCompanyPagesForbiddenError";
  }
}

/**
 * Although HTTP specifies "unauthorized", this response means "unauthenticated". Authenticate to continue.
 */
export type ListLinkedInCompanyPagesUnauthorizedErrorData = {
  success?: false | undefined;
  error: operations.ListLinkedInCompanyPagesUnauthorizedError;
};

/**
 * Although HTTP specifies "unauthorized", this response means "unauthenticated". Authenticate to continue.
 */
export class ListLinkedInCompanyPagesUnauthorizedError extends BereachError {
  success?: false | undefined;
  error: operations.ListLinkedInCompanyPagesUnauthorizedError;

  /** The original data that was passed to this error instance. */
  data$: ListLinkedInCompanyPagesUnauthorizedErrorData;

  constructor(
    err: ListLinkedInCompanyPagesUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "ListLinkedInCompanyPagesUnauthorizedError";
  }
}

/**
 * The server cannot or will not process the request due to something that is perceived to be a client error.
 */
export type ListLinkedInCompanyPagesBadRequestErrorData = {
  success?: false | undefined;
  error: operations.ListLinkedInCompanyPagesBadRequestError;
};

/**
 * The server cannot or will not process the request due to something that is perceived to be a client error.
 */
export class ListLinkedInCompanyPagesBadRequestError extends BereachError {
  success?: false | undefined;
  error: operations.ListLinkedInCompanyPagesBadRequestError;

  /** The original data that was passed to this error instance. */
  data$: ListLinkedInCompanyPagesBadRequestErrorData;

  constructor(
    err: ListLinkedInCompanyPagesBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "ListLinkedInCompanyPagesBadRequestError";
  }
}

/** @internal */
export const ListLinkedInCompanyPagesInternalServerError$inboundSchema:
  z.ZodMiniType<ListLinkedInCompanyPagesInternalServerError, unknown> = z.pipe(
    z.object({
      success: z._default(types.literal(false), false),
      error: z.lazy(() =>
        operations
          .ListLinkedInCompanyPagesInternalServerErrorError$inboundSchema
      ),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new ListLinkedInCompanyPagesInternalServerError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const ListLinkedInCompanyPagesTooManyRequestsError$inboundSchema:
  z.ZodMiniType<ListLinkedInCompanyPagesTooManyRequestsError, unknown> = z.pipe(
    z.object({
      success: z._default(types.literal(false), false),
      error: z.lazy(() =>
        operations.ListLinkedInCompanyPagesTooManyRequestsError$inboundSchema
      ),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new ListLinkedInCompanyPagesTooManyRequestsError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const ListLinkedInCompanyPagesUnprocessableEntityError$inboundSchema:
  z.ZodMiniType<ListLinkedInCompanyPagesUnprocessableEntityError, unknown> = z
    .pipe(
      z.object({
        success: z._default(types.literal(false), false),
        error: z.lazy(() =>
          operations
            .ListLinkedInCompanyPagesUnprocessableEntityError$inboundSchema
        ),
        request$: z.custom<Request>(x => x instanceof Request),
        response$: z.custom<Response>(x => x instanceof Response),
        body$: z.string(),
      }),
      z.transform((v) => {
        return new ListLinkedInCompanyPagesUnprocessableEntityError(v, {
          request: v.request$,
          response: v.response$,
          body: v.body$,
        });
      }),
    );

/** @internal */
export const ListLinkedInCompanyPagesGoneError$inboundSchema: z.ZodMiniType<
  ListLinkedInCompanyPagesGoneError,
  unknown
> = z.pipe(
  z.object({
    success: z._default(types.literal(false), false),
    error: z.lazy(() =>
      operations.ListLinkedInCompanyPagesGoneError$inboundSchema
    ),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new ListLinkedInCompanyPagesGoneError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const ListLinkedInCompanyPagesConflictError$inboundSchema: z.ZodMiniType<
  ListLinkedInCompanyPagesConflictError,
  unknown
> = z.pipe(
  z.object({
    success: z._default(types.literal(false), false),
    error: z.lazy(() =>
      operations.ListLinkedInCompanyPagesConflictError$inboundSchema
    ),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new ListLinkedInCompanyPagesConflictError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const ListLinkedInCompanyPagesNotFoundError$inboundSchema: z.ZodMiniType<
  ListLinkedInCompanyPagesNotFoundError,
  unknown
> = z.pipe(
  z.object({
    success: z._default(types.literal(false), false),
    error: z.lazy(() =>
      operations.ListLinkedInCompanyPagesNotFoundError$inboundSchema
    ),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new ListLinkedInCompanyPagesNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const ListLinkedInCompanyPagesForbiddenError$inboundSchema:
  z.ZodMiniType<ListLinkedInCompanyPagesForbiddenError, unknown> = z.pipe(
    z.object({
      success: z._default(types.literal(false), false),
      error: z.lazy(() =>
        operations.ListLinkedInCompanyPagesForbiddenError$inboundSchema
      ),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new ListLinkedInCompanyPagesForbiddenError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const ListLinkedInCompanyPagesUnauthorizedError$inboundSchema:
  z.ZodMiniType<ListLinkedInCompanyPagesUnauthorizedError, unknown> = z.pipe(
    z.object({
      success: z._default(types.literal(false), false),
      error: z.lazy(() =>
        operations.ListLinkedInCompanyPagesUnauthorizedError$inboundSchema
      ),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new ListLinkedInCompanyPagesUnauthorizedError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const ListLinkedInCompanyPagesBadRequestError$inboundSchema:
  z.ZodMiniType<ListLinkedInCompanyPagesBadRequestError, unknown> = z.pipe(
    z.object({
      success: z._default(types.literal(false), false),
      error: z.lazy(() =>
        operations.ListLinkedInCompanyPagesBadRequestError$inboundSchema
      ),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new ListLinkedInCompanyPagesBadRequestError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );
