/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import * as operations from "../operations/index.js";
import { BereachError } from "./bereach-error.js";

/**
 * The server encountered a situation it does not know how to handle.
 */
export type SearchSalesNavCompaniesInternalServerErrorData = {
  success?: false | undefined;
  error: operations.SearchSalesNavCompaniesInternalServerErrorError;
};

/**
 * The server encountered a situation it does not know how to handle.
 */
export class SearchSalesNavCompaniesInternalServerError extends BereachError {
  success?: false | undefined;
  error: operations.SearchSalesNavCompaniesInternalServerErrorError;

  /** The original data that was passed to this error instance. */
  data$: SearchSalesNavCompaniesInternalServerErrorData;

  constructor(
    err: SearchSalesNavCompaniesInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "SearchSalesNavCompaniesInternalServerError";
  }
}

/**
 * Rate limit exceeded. Read error.retryAfter for the wait time in seconds.
 */
export type SearchSalesNavCompaniesTooManyRequestsErrorData = {
  success?: false | undefined;
  error: operations.SearchSalesNavCompaniesTooManyRequestsError;
};

/**
 * Rate limit exceeded. Read error.retryAfter for the wait time in seconds.
 */
export class SearchSalesNavCompaniesTooManyRequestsError extends BereachError {
  success?: false | undefined;
  error: operations.SearchSalesNavCompaniesTooManyRequestsError;

  /** The original data that was passed to this error instance. */
  data$: SearchSalesNavCompaniesTooManyRequestsErrorData;

  constructor(
    err: SearchSalesNavCompaniesTooManyRequestsErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "SearchSalesNavCompaniesTooManyRequestsError";
  }
}

/**
 * The request was well-formed but was unable to be followed due to semantic errors.
 */
export type SearchSalesNavCompaniesUnprocessableEntityErrorData = {
  success?: false | undefined;
  error: operations.SearchSalesNavCompaniesUnprocessableEntityError;
};

/**
 * The request was well-formed but was unable to be followed due to semantic errors.
 */
export class SearchSalesNavCompaniesUnprocessableEntityError
  extends BereachError
{
  success?: false | undefined;
  error: operations.SearchSalesNavCompaniesUnprocessableEntityError;

  /** The original data that was passed to this error instance. */
  data$: SearchSalesNavCompaniesUnprocessableEntityErrorData;

  constructor(
    err: SearchSalesNavCompaniesUnprocessableEntityErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "SearchSalesNavCompaniesUnprocessableEntityError";
  }
}

/**
 * The requested content has been permanently deleted from the server.
 */
export type SearchSalesNavCompaniesGoneErrorData = {
  success?: false | undefined;
  error: operations.SearchSalesNavCompaniesGoneError;
};

/**
 * The requested content has been permanently deleted from the server.
 */
export class SearchSalesNavCompaniesGoneError extends BereachError {
  success?: false | undefined;
  error: operations.SearchSalesNavCompaniesGoneError;

  /** The original data that was passed to this error instance. */
  data$: SearchSalesNavCompaniesGoneErrorData;

  constructor(
    err: SearchSalesNavCompaniesGoneErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "SearchSalesNavCompaniesGoneError";
  }
}

/**
 * The request conflicts with the current state of the server.
 */
export type SearchSalesNavCompaniesConflictErrorData = {
  success?: false | undefined;
  error: operations.SearchSalesNavCompaniesConflictError;
};

/**
 * The request conflicts with the current state of the server.
 */
export class SearchSalesNavCompaniesConflictError extends BereachError {
  success?: false | undefined;
  error: operations.SearchSalesNavCompaniesConflictError;

  /** The original data that was passed to this error instance. */
  data$: SearchSalesNavCompaniesConflictErrorData;

  constructor(
    err: SearchSalesNavCompaniesConflictErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "SearchSalesNavCompaniesConflictError";
  }
}

/**
 * The server cannot find the requested resource.
 */
export type SearchSalesNavCompaniesNotFoundErrorData = {
  success?: false | undefined;
  error: operations.SearchSalesNavCompaniesNotFoundError;
};

/**
 * The server cannot find the requested resource.
 */
export class SearchSalesNavCompaniesNotFoundError extends BereachError {
  success?: false | undefined;
  error: operations.SearchSalesNavCompaniesNotFoundError;

  /** The original data that was passed to this error instance. */
  data$: SearchSalesNavCompaniesNotFoundErrorData;

  constructor(
    err: SearchSalesNavCompaniesNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "SearchSalesNavCompaniesNotFoundError";
  }
}

/**
 * The client does not have access rights to the content.
 */
export type SearchSalesNavCompaniesForbiddenErrorData = {
  success?: false | undefined;
  error: operations.SearchSalesNavCompaniesForbiddenError;
};

/**
 * The client does not have access rights to the content.
 */
export class SearchSalesNavCompaniesForbiddenError extends BereachError {
  success?: false | undefined;
  error: operations.SearchSalesNavCompaniesForbiddenError;

  /** The original data that was passed to this error instance. */
  data$: SearchSalesNavCompaniesForbiddenErrorData;

  constructor(
    err: SearchSalesNavCompaniesForbiddenErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "SearchSalesNavCompaniesForbiddenError";
  }
}

/**
 * Although HTTP specifies "unauthorized", this response means "unauthenticated". Authenticate to continue.
 */
export type SearchSalesNavCompaniesUnauthorizedErrorData = {
  success?: false | undefined;
  error: operations.SearchSalesNavCompaniesUnauthorizedError;
};

/**
 * Although HTTP specifies "unauthorized", this response means "unauthenticated". Authenticate to continue.
 */
export class SearchSalesNavCompaniesUnauthorizedError extends BereachError {
  success?: false | undefined;
  error: operations.SearchSalesNavCompaniesUnauthorizedError;

  /** The original data that was passed to this error instance. */
  data$: SearchSalesNavCompaniesUnauthorizedErrorData;

  constructor(
    err: SearchSalesNavCompaniesUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "SearchSalesNavCompaniesUnauthorizedError";
  }
}

/**
 * The server cannot or will not process the request due to something that is perceived to be a client error.
 */
export type SearchSalesNavCompaniesBadRequestErrorData = {
  success?: false | undefined;
  error: operations.SearchSalesNavCompaniesBadRequestError;
};

/**
 * The server cannot or will not process the request due to something that is perceived to be a client error.
 */
export class SearchSalesNavCompaniesBadRequestError extends BereachError {
  success?: false | undefined;
  error: operations.SearchSalesNavCompaniesBadRequestError;

  /** The original data that was passed to this error instance. */
  data$: SearchSalesNavCompaniesBadRequestErrorData;

  constructor(
    err: SearchSalesNavCompaniesBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "SearchSalesNavCompaniesBadRequestError";
  }
}

/** @internal */
export const SearchSalesNavCompaniesInternalServerError$inboundSchema:
  z.ZodMiniType<SearchSalesNavCompaniesInternalServerError, unknown> = z.pipe(
    z.object({
      success: z._default(types.literal(false), false),
      error: z.lazy(() =>
        operations.SearchSalesNavCompaniesInternalServerErrorError$inboundSchema
      ),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new SearchSalesNavCompaniesInternalServerError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const SearchSalesNavCompaniesTooManyRequestsError$inboundSchema:
  z.ZodMiniType<SearchSalesNavCompaniesTooManyRequestsError, unknown> = z.pipe(
    z.object({
      success: z._default(types.literal(false), false),
      error: z.lazy(() =>
        operations.SearchSalesNavCompaniesTooManyRequestsError$inboundSchema
      ),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new SearchSalesNavCompaniesTooManyRequestsError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const SearchSalesNavCompaniesUnprocessableEntityError$inboundSchema:
  z.ZodMiniType<SearchSalesNavCompaniesUnprocessableEntityError, unknown> = z
    .pipe(
      z.object({
        success: z._default(types.literal(false), false),
        error: z.lazy(() =>
          operations
            .SearchSalesNavCompaniesUnprocessableEntityError$inboundSchema
        ),
        request$: z.custom<Request>(x => x instanceof Request),
        response$: z.custom<Response>(x => x instanceof Response),
        body$: z.string(),
      }),
      z.transform((v) => {
        return new SearchSalesNavCompaniesUnprocessableEntityError(v, {
          request: v.request$,
          response: v.response$,
          body: v.body$,
        });
      }),
    );

/** @internal */
export const SearchSalesNavCompaniesGoneError$inboundSchema: z.ZodMiniType<
  SearchSalesNavCompaniesGoneError,
  unknown
> = z.pipe(
  z.object({
    success: z._default(types.literal(false), false),
    error: z.lazy(() =>
      operations.SearchSalesNavCompaniesGoneError$inboundSchema
    ),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new SearchSalesNavCompaniesGoneError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const SearchSalesNavCompaniesConflictError$inboundSchema: z.ZodMiniType<
  SearchSalesNavCompaniesConflictError,
  unknown
> = z.pipe(
  z.object({
    success: z._default(types.literal(false), false),
    error: z.lazy(() =>
      operations.SearchSalesNavCompaniesConflictError$inboundSchema
    ),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new SearchSalesNavCompaniesConflictError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const SearchSalesNavCompaniesNotFoundError$inboundSchema: z.ZodMiniType<
  SearchSalesNavCompaniesNotFoundError,
  unknown
> = z.pipe(
  z.object({
    success: z._default(types.literal(false), false),
    error: z.lazy(() =>
      operations.SearchSalesNavCompaniesNotFoundError$inboundSchema
    ),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new SearchSalesNavCompaniesNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const SearchSalesNavCompaniesForbiddenError$inboundSchema: z.ZodMiniType<
  SearchSalesNavCompaniesForbiddenError,
  unknown
> = z.pipe(
  z.object({
    success: z._default(types.literal(false), false),
    error: z.lazy(() =>
      operations.SearchSalesNavCompaniesForbiddenError$inboundSchema
    ),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new SearchSalesNavCompaniesForbiddenError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const SearchSalesNavCompaniesUnauthorizedError$inboundSchema:
  z.ZodMiniType<SearchSalesNavCompaniesUnauthorizedError, unknown> = z.pipe(
    z.object({
      success: z._default(types.literal(false), false),
      error: z.lazy(() =>
        operations.SearchSalesNavCompaniesUnauthorizedError$inboundSchema
      ),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new SearchSalesNavCompaniesUnauthorizedError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const SearchSalesNavCompaniesBadRequestError$inboundSchema:
  z.ZodMiniType<SearchSalesNavCompaniesBadRequestError, unknown> = z.pipe(
    z.object({
      success: z._default(types.literal(false), false),
      error: z.lazy(() =>
        operations.SearchSalesNavCompaniesBadRequestError$inboundSchema
      ),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new SearchSalesNavCompaniesBadRequestError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );
