/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import * as operations from "../operations/index.js";
import { BereachError } from "./bereach-error.js";

/**
 * The server encountered a situation it does not know how to handle.
 */
export type UnsaveLinkedInPostInternalServerErrorData = {
  success?: false | undefined;
  error: operations.UnsaveLinkedInPostInternalServerErrorError;
};

/**
 * The server encountered a situation it does not know how to handle.
 */
export class UnsaveLinkedInPostInternalServerError extends BereachError {
  success?: false | undefined;
  error: operations.UnsaveLinkedInPostInternalServerErrorError;

  /** The original data that was passed to this error instance. */
  data$: UnsaveLinkedInPostInternalServerErrorData;

  constructor(
    err: UnsaveLinkedInPostInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "UnsaveLinkedInPostInternalServerError";
  }
}

/**
 * Rate limit exceeded. Read error.retryAfter for the wait time in seconds.
 */
export type UnsaveLinkedInPostTooManyRequestsErrorData = {
  success?: false | undefined;
  error: operations.UnsaveLinkedInPostTooManyRequestsError;
};

/**
 * Rate limit exceeded. Read error.retryAfter for the wait time in seconds.
 */
export class UnsaveLinkedInPostTooManyRequestsError extends BereachError {
  success?: false | undefined;
  error: operations.UnsaveLinkedInPostTooManyRequestsError;

  /** The original data that was passed to this error instance. */
  data$: UnsaveLinkedInPostTooManyRequestsErrorData;

  constructor(
    err: UnsaveLinkedInPostTooManyRequestsErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "UnsaveLinkedInPostTooManyRequestsError";
  }
}

/**
 * The request was well-formed but was unable to be followed due to semantic errors.
 */
export type UnsaveLinkedInPostUnprocessableEntityErrorData = {
  success?: false | undefined;
  error: operations.UnsaveLinkedInPostUnprocessableEntityError;
};

/**
 * The request was well-formed but was unable to be followed due to semantic errors.
 */
export class UnsaveLinkedInPostUnprocessableEntityError extends BereachError {
  success?: false | undefined;
  error: operations.UnsaveLinkedInPostUnprocessableEntityError;

  /** The original data that was passed to this error instance. */
  data$: UnsaveLinkedInPostUnprocessableEntityErrorData;

  constructor(
    err: UnsaveLinkedInPostUnprocessableEntityErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "UnsaveLinkedInPostUnprocessableEntityError";
  }
}

/**
 * The requested content has been permanently deleted from the server.
 */
export type UnsaveLinkedInPostGoneErrorData = {
  success?: false | undefined;
  error: operations.UnsaveLinkedInPostGoneError;
};

/**
 * The requested content has been permanently deleted from the server.
 */
export class UnsaveLinkedInPostGoneError extends BereachError {
  success?: false | undefined;
  error: operations.UnsaveLinkedInPostGoneError;

  /** The original data that was passed to this error instance. */
  data$: UnsaveLinkedInPostGoneErrorData;

  constructor(
    err: UnsaveLinkedInPostGoneErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "UnsaveLinkedInPostGoneError";
  }
}

/**
 * The request conflicts with the current state of the server.
 */
export type UnsaveLinkedInPostConflictErrorData = {
  success?: false | undefined;
  error: operations.UnsaveLinkedInPostConflictError;
};

/**
 * The request conflicts with the current state of the server.
 */
export class UnsaveLinkedInPostConflictError extends BereachError {
  success?: false | undefined;
  error: operations.UnsaveLinkedInPostConflictError;

  /** The original data that was passed to this error instance. */
  data$: UnsaveLinkedInPostConflictErrorData;

  constructor(
    err: UnsaveLinkedInPostConflictErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "UnsaveLinkedInPostConflictError";
  }
}

/**
 * The server cannot find the requested resource.
 */
export type UnsaveLinkedInPostNotFoundErrorData = {
  success?: false | undefined;
  error: operations.UnsaveLinkedInPostNotFoundError;
};

/**
 * The server cannot find the requested resource.
 */
export class UnsaveLinkedInPostNotFoundError extends BereachError {
  success?: false | undefined;
  error: operations.UnsaveLinkedInPostNotFoundError;

  /** The original data that was passed to this error instance. */
  data$: UnsaveLinkedInPostNotFoundErrorData;

  constructor(
    err: UnsaveLinkedInPostNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "UnsaveLinkedInPostNotFoundError";
  }
}

/**
 * The client does not have access rights to the content.
 */
export type UnsaveLinkedInPostForbiddenErrorData = {
  success?: false | undefined;
  error: operations.UnsaveLinkedInPostForbiddenError;
};

/**
 * The client does not have access rights to the content.
 */
export class UnsaveLinkedInPostForbiddenError extends BereachError {
  success?: false | undefined;
  error: operations.UnsaveLinkedInPostForbiddenError;

  /** The original data that was passed to this error instance. */
  data$: UnsaveLinkedInPostForbiddenErrorData;

  constructor(
    err: UnsaveLinkedInPostForbiddenErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "UnsaveLinkedInPostForbiddenError";
  }
}

/**
 * Although HTTP specifies "unauthorized", this response means "unauthenticated". Authenticate to continue.
 */
export type UnsaveLinkedInPostUnauthorizedErrorData = {
  success?: false | undefined;
  error: operations.UnsaveLinkedInPostUnauthorizedError;
};

/**
 * Although HTTP specifies "unauthorized", this response means "unauthenticated". Authenticate to continue.
 */
export class UnsaveLinkedInPostUnauthorizedError extends BereachError {
  success?: false | undefined;
  error: operations.UnsaveLinkedInPostUnauthorizedError;

  /** The original data that was passed to this error instance. */
  data$: UnsaveLinkedInPostUnauthorizedErrorData;

  constructor(
    err: UnsaveLinkedInPostUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "UnsaveLinkedInPostUnauthorizedError";
  }
}

/**
 * The server cannot or will not process the request due to something that is perceived to be a client error.
 */
export type UnsaveLinkedInPostBadRequestErrorData = {
  success?: false | undefined;
  error: operations.UnsaveLinkedInPostBadRequestError;
};

/**
 * The server cannot or will not process the request due to something that is perceived to be a client error.
 */
export class UnsaveLinkedInPostBadRequestError extends BereachError {
  success?: false | undefined;
  error: operations.UnsaveLinkedInPostBadRequestError;

  /** The original data that was passed to this error instance. */
  data$: UnsaveLinkedInPostBadRequestErrorData;

  constructor(
    err: UnsaveLinkedInPostBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.success != null) this.success = err.success;
    this.error = err.error;

    this.name = "UnsaveLinkedInPostBadRequestError";
  }
}

/** @internal */
export const UnsaveLinkedInPostInternalServerError$inboundSchema: z.ZodMiniType<
  UnsaveLinkedInPostInternalServerError,
  unknown
> = z.pipe(
  z.object({
    success: z._default(types.literal(false), false),
    error: z.lazy(() =>
      operations.UnsaveLinkedInPostInternalServerErrorError$inboundSchema
    ),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new UnsaveLinkedInPostInternalServerError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const UnsaveLinkedInPostTooManyRequestsError$inboundSchema:
  z.ZodMiniType<UnsaveLinkedInPostTooManyRequestsError, unknown> = z.pipe(
    z.object({
      success: z._default(types.literal(false), false),
      error: z.lazy(() =>
        operations.UnsaveLinkedInPostTooManyRequestsError$inboundSchema
      ),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new UnsaveLinkedInPostTooManyRequestsError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const UnsaveLinkedInPostUnprocessableEntityError$inboundSchema:
  z.ZodMiniType<UnsaveLinkedInPostUnprocessableEntityError, unknown> = z.pipe(
    z.object({
      success: z._default(types.literal(false), false),
      error: z.lazy(() =>
        operations.UnsaveLinkedInPostUnprocessableEntityError$inboundSchema
      ),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new UnsaveLinkedInPostUnprocessableEntityError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const UnsaveLinkedInPostGoneError$inboundSchema: z.ZodMiniType<
  UnsaveLinkedInPostGoneError,
  unknown
> = z.pipe(
  z.object({
    success: z._default(types.literal(false), false),
    error: z.lazy(() => operations.UnsaveLinkedInPostGoneError$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new UnsaveLinkedInPostGoneError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const UnsaveLinkedInPostConflictError$inboundSchema: z.ZodMiniType<
  UnsaveLinkedInPostConflictError,
  unknown
> = z.pipe(
  z.object({
    success: z._default(types.literal(false), false),
    error: z.lazy(() =>
      operations.UnsaveLinkedInPostConflictError$inboundSchema
    ),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new UnsaveLinkedInPostConflictError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const UnsaveLinkedInPostNotFoundError$inboundSchema: z.ZodMiniType<
  UnsaveLinkedInPostNotFoundError,
  unknown
> = z.pipe(
  z.object({
    success: z._default(types.literal(false), false),
    error: z.lazy(() =>
      operations.UnsaveLinkedInPostNotFoundError$inboundSchema
    ),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new UnsaveLinkedInPostNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const UnsaveLinkedInPostForbiddenError$inboundSchema: z.ZodMiniType<
  UnsaveLinkedInPostForbiddenError,
  unknown
> = z.pipe(
  z.object({
    success: z._default(types.literal(false), false),
    error: z.lazy(() =>
      operations.UnsaveLinkedInPostForbiddenError$inboundSchema
    ),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new UnsaveLinkedInPostForbiddenError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const UnsaveLinkedInPostUnauthorizedError$inboundSchema: z.ZodMiniType<
  UnsaveLinkedInPostUnauthorizedError,
  unknown
> = z.pipe(
  z.object({
    success: z._default(types.literal(false), false),
    error: z.lazy(() =>
      operations.UnsaveLinkedInPostUnauthorizedError$inboundSchema
    ),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new UnsaveLinkedInPostUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const UnsaveLinkedInPostBadRequestError$inboundSchema: z.ZodMiniType<
  UnsaveLinkedInPostBadRequestError,
  unknown
> = z.pipe(
  z.object({
    success: z._default(types.literal(false), false),
    error: z.lazy(() =>
      operations.UnsaveLinkedInPostBadRequestError$inboundSchema
    ),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new UnsaveLinkedInPostBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
