/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { linkedInScrapersCollectPosts } from "../../funcs/linkedInScrapersCollectPosts.js";
import { CollectLinkedInPostsRequest$zodSchema } from "../../models/collectlinkedinpostsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CollectLinkedInPostsRequest$zodSchema,
};

export const tool$linkedInScrapersCollectPosts: ToolDefinition<typeof args> = {
  name: "linked-in-scrapers-collect-posts",
  description: `Scrape LinkedIn profile posts

Authenticates the requester, validates LinkedIn credentials, and returns paginated posts from a LinkedIn profile. Supports count, start, and paginationToken for pagination.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await linkedInScrapersCollectPosts(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
