/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { linkedInActionsPublishPost } from "../../funcs/linkedInActionsPublishPost.js";
import { PublishLinkedInPostRequest$zodSchema } from "../../models/publishlinkedinpostop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PublishLinkedInPostRequest$zodSchema,
};

export const tool$linkedInActionsPublishPost: ToolDefinition<typeof args> = {
  name: "linked-in-actions-publish-post",
  description: `Publish or schedule a LinkedIn post

Creates a new LinkedIn post. Supports instant publishing and scheduled posting. Optionally attach an image by providing its URL. Rate limited to 80 actions per day per user. Consumes 1 credit per post.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await linkedInActionsPublishPost(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
