/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { BereachCore } from "../core.js";
import { encodeJSON } from "../lib/encodings.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import { BereachError } from "../models/errors/bereach-error.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/http-client-errors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/response-validation-error.js";
import { SDKValidationError } from "../models/errors/sdk-validation-error.js";
import * as operations from "../models/operations/index.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * React to a message with emoji
 *
 * @remarks
 * Add an emoji reaction to a LinkedIn message. 0 credits.
 */
export function linkedinChatReact(
  client: BereachCore,
  request: operations.ReactToMessageRequest,
  options?: RequestOptions,
): APIPromise<
  Result<
    operations.ReactToMessageResponse,
    | errors.ReactToMessageBadRequestError
    | errors.ReactToMessageUnauthorizedError
    | errors.ReactToMessageForbiddenError
    | errors.ReactToMessageNotFoundError
    | errors.ReactToMessageConflictError
    | errors.ReactToMessageGoneError
    | errors.ReactToMessageUnprocessableEntityError
    | errors.ReactToMessageTooManyRequestsError
    | errors.ReactToMessageInternalServerError
    | BereachError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
> {
  return new APIPromise($do(
    client,
    request,
    options,
  ));
}

async function $do(
  client: BereachCore,
  request: operations.ReactToMessageRequest,
  options?: RequestOptions,
): Promise<
  [
    Result<
      operations.ReactToMessageResponse,
      | errors.ReactToMessageBadRequestError
      | errors.ReactToMessageUnauthorizedError
      | errors.ReactToMessageForbiddenError
      | errors.ReactToMessageNotFoundError
      | errors.ReactToMessageConflictError
      | errors.ReactToMessageGoneError
      | errors.ReactToMessageUnprocessableEntityError
      | errors.ReactToMessageTooManyRequestsError
      | errors.ReactToMessageInternalServerError
      | BereachError
      | ResponseValidationError
      | ConnectionError
      | RequestAbortedError
      | RequestTimeoutError
      | InvalidRequestError
      | UnexpectedClientError
      | SDKValidationError
    >,
    APICall,
  ]
> {
  const parsed = safeParse(
    request,
    (value) => z.parse(operations.ReactToMessageRequest$outboundSchema, value),
    "Input validation failed",
  );
  if (!parsed.ok) {
    return [parsed, { status: "invalid" }];
  }
  const payload = parsed.value;
  const body = encodeJSON("body", payload, { explode: true });

  const path = pathToFunc("/chats/linkedin/react")();

  const headers = new Headers(compactMap({
    "Content-Type": "application/json",
    Accept: "application/json",
  }));

  const secConfig = await extractSecurity(client._options.token);
  const securityInput = secConfig == null ? {} : { token: secConfig };
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    options: client._options,
    baseURL: options?.serverURL ?? client._baseURL ?? "",
    operationID: "reactToMessage",
    oAuth2Scopes: null,

    resolvedSecurity: requestSecurity,

    securitySource: client._options.token,
    retryConfig: options?.retries
      || client._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
  };

  const requestRes = client._createRequest(context, {
    security: requestSecurity,
    method: "POST",
    baseURL: options?.serverURL,
    path: path,
    headers: headers,
    body: body,
    userAgent: client._options.userAgent,
    timeoutMs: options?.timeoutMs || client._options.timeoutMs || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req = requestRes.value;

  const doResult = await client._do(req, {
    context,
    errorCodes: [
      "400",
      "401",
      "403",
      "404",
      "409",
      "410",
      "422",
      "429",
      "4XX",
      "500",
      "5XX",
    ],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req }];
  }
  const response = doResult.value;

  const responseFields = {
    HttpMeta: { Response: response, Request: req },
  };

  const [result] = await M.match<
    operations.ReactToMessageResponse,
    | errors.ReactToMessageBadRequestError
    | errors.ReactToMessageUnauthorizedError
    | errors.ReactToMessageForbiddenError
    | errors.ReactToMessageNotFoundError
    | errors.ReactToMessageConflictError
    | errors.ReactToMessageGoneError
    | errors.ReactToMessageUnprocessableEntityError
    | errors.ReactToMessageTooManyRequestsError
    | errors.ReactToMessageInternalServerError
    | BereachError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >(
    M.json(200, operations.ReactToMessageResponse$inboundSchema),
    M.jsonErr(400, errors.ReactToMessageBadRequestError$inboundSchema),
    M.jsonErr(401, errors.ReactToMessageUnauthorizedError$inboundSchema),
    M.jsonErr(403, errors.ReactToMessageForbiddenError$inboundSchema),
    M.jsonErr(404, errors.ReactToMessageNotFoundError$inboundSchema),
    M.jsonErr(409, errors.ReactToMessageConflictError$inboundSchema),
    M.jsonErr(410, errors.ReactToMessageGoneError$inboundSchema),
    M.jsonErr(422, errors.ReactToMessageUnprocessableEntityError$inboundSchema),
    M.jsonErr(429, errors.ReactToMessageTooManyRequestsError$inboundSchema),
    M.jsonErr(500, errors.ReactToMessageInternalServerError$inboundSchema),
    M.fail("4XX"),
    M.fail("5XX"),
  )(response, req, { extraFields: responseFields });
  if (!result.ok) {
    return [result, { status: "complete", request: req, response }];
  }

  return [result, { status: "complete", request: req, response }];
}
