/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { BereachCore } from "../core.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import { BereachError } from "../models/errors/bereach-error.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/http-client-errors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/response-validation-error.js";
import { SDKValidationError } from "../models/errors/sdk-validation-error.js";
import * as operations from "../models/operations/index.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * Get follower analytics
 *
 * @remarks
 * Get follower demographics and growth data for your LinkedIn profile. Returns follower count, growth trends, and demographic breakdowns. 1 credit.
 */
export function profileGetFollowerAnalytics(
  client: BereachCore,
  _request?: operations.GetLinkedInFollowerAnalyticsRequest | undefined,
  options?: RequestOptions,
): APIPromise<
  Result<
    operations.GetLinkedInFollowerAnalyticsResponse,
    | errors.GetLinkedInFollowerAnalyticsBadRequestError
    | errors.GetLinkedInFollowerAnalyticsUnauthorizedError
    | errors.GetLinkedInFollowerAnalyticsForbiddenError
    | errors.GetLinkedInFollowerAnalyticsNotFoundError
    | errors.GetLinkedInFollowerAnalyticsConflictError
    | errors.GetLinkedInFollowerAnalyticsGoneError
    | errors.GetLinkedInFollowerAnalyticsUnprocessableEntityError
    | errors.GetLinkedInFollowerAnalyticsTooManyRequestsError
    | errors.GetLinkedInFollowerAnalyticsInternalServerError
    | BereachError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
> {
  return new APIPromise($do(
    client,
    _request,
    options,
  ));
}

async function $do(
  client: BereachCore,
  _request?: operations.GetLinkedInFollowerAnalyticsRequest | undefined,
  options?: RequestOptions,
): Promise<
  [
    Result<
      operations.GetLinkedInFollowerAnalyticsResponse,
      | errors.GetLinkedInFollowerAnalyticsBadRequestError
      | errors.GetLinkedInFollowerAnalyticsUnauthorizedError
      | errors.GetLinkedInFollowerAnalyticsForbiddenError
      | errors.GetLinkedInFollowerAnalyticsNotFoundError
      | errors.GetLinkedInFollowerAnalyticsConflictError
      | errors.GetLinkedInFollowerAnalyticsGoneError
      | errors.GetLinkedInFollowerAnalyticsUnprocessableEntityError
      | errors.GetLinkedInFollowerAnalyticsTooManyRequestsError
      | errors.GetLinkedInFollowerAnalyticsInternalServerError
      | BereachError
      | ResponseValidationError
      | ConnectionError
      | RequestAbortedError
      | RequestTimeoutError
      | InvalidRequestError
      | UnexpectedClientError
      | SDKValidationError
    >,
    APICall,
  ]
> {
  const path = pathToFunc("/analytics/linkedin/followers")();

  const headers = new Headers(compactMap({
    "Content-Type": "application/json",
    Accept: "application/json",
  }));

  const secConfig = await extractSecurity(client._options.token);
  const securityInput = secConfig == null ? {} : { token: secConfig };
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    options: client._options,
    baseURL: options?.serverURL ?? client._baseURL ?? "",
    operationID: "getLinkedInFollowerAnalytics",
    oAuth2Scopes: null,

    resolvedSecurity: requestSecurity,

    securitySource: client._options.token,
    retryConfig: options?.retries
      || client._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
  };

  const requestRes = client._createRequest(context, {
    security: requestSecurity,
    method: "POST",
    baseURL: options?.serverURL,
    path: path,
    headers: headers,
    userAgent: client._options.userAgent,
    timeoutMs: options?.timeoutMs || client._options.timeoutMs || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req = requestRes.value;

  const doResult = await client._do(req, {
    context,
    errorCodes: [
      "400",
      "401",
      "403",
      "404",
      "409",
      "410",
      "422",
      "429",
      "4XX",
      "500",
      "5XX",
    ],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req }];
  }
  const response = doResult.value;

  const responseFields = {
    HttpMeta: { Response: response, Request: req },
  };

  const [result] = await M.match<
    operations.GetLinkedInFollowerAnalyticsResponse,
    | errors.GetLinkedInFollowerAnalyticsBadRequestError
    | errors.GetLinkedInFollowerAnalyticsUnauthorizedError
    | errors.GetLinkedInFollowerAnalyticsForbiddenError
    | errors.GetLinkedInFollowerAnalyticsNotFoundError
    | errors.GetLinkedInFollowerAnalyticsConflictError
    | errors.GetLinkedInFollowerAnalyticsGoneError
    | errors.GetLinkedInFollowerAnalyticsUnprocessableEntityError
    | errors.GetLinkedInFollowerAnalyticsTooManyRequestsError
    | errors.GetLinkedInFollowerAnalyticsInternalServerError
    | BereachError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >(
    M.json(200, operations.GetLinkedInFollowerAnalyticsResponse$inboundSchema),
    M.jsonErr(
      400,
      errors.GetLinkedInFollowerAnalyticsBadRequestError$inboundSchema,
    ),
    M.jsonErr(
      401,
      errors.GetLinkedInFollowerAnalyticsUnauthorizedError$inboundSchema,
    ),
    M.jsonErr(
      403,
      errors.GetLinkedInFollowerAnalyticsForbiddenError$inboundSchema,
    ),
    M.jsonErr(
      404,
      errors.GetLinkedInFollowerAnalyticsNotFoundError$inboundSchema,
    ),
    M.jsonErr(
      409,
      errors.GetLinkedInFollowerAnalyticsConflictError$inboundSchema,
    ),
    M.jsonErr(410, errors.GetLinkedInFollowerAnalyticsGoneError$inboundSchema),
    M.jsonErr(
      422,
      errors.GetLinkedInFollowerAnalyticsUnprocessableEntityError$inboundSchema,
    ),
    M.jsonErr(
      429,
      errors.GetLinkedInFollowerAnalyticsTooManyRequestsError$inboundSchema,
    ),
    M.jsonErr(
      500,
      errors.GetLinkedInFollowerAnalyticsInternalServerError$inboundSchema,
    ),
    M.fail("4XX"),
    M.fail("5XX"),
  )(response, req, { extraFields: responseFields });
  if (!result.ok) {
    return [result, { status: "complete", request: req, response }];
  }

  return [result, { status: "complete", request: req, response }];
}
