/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { BereachCore } from "../core.js";
import { SDKOptions } from "../lib/config.js";
import type { ConsoleLogger } from "./console-logger.js";
import { createRegisterPrompt } from "./prompts.js";
import {
  createRegisterResource,
  createRegisterResourceTemplate,
} from "./resources.js";
import { MCPScope } from "./scopes.js";
import { createRegisterTool, registerDynamicTools } from "./tools.js";
import { tool$campaignsFilter } from "./tools/campaignsFilter.js";
import { tool$linkedInActionsAcceptInvitation } from "./tools/linkedInActionsAcceptInvitation.js";
import { tool$linkedInActionsConnectProfile } from "./tools/linkedInActionsConnectProfile.js";
import { tool$linkedInActionsLikeComment } from "./tools/linkedInActionsLikeComment.js";
import { tool$linkedInActionsListInvitations } from "./tools/linkedInActionsListInvitations.js";
import { tool$linkedInActionsPublishPost } from "./tools/linkedInActionsPublishPost.js";
import { tool$linkedInActionsReplyToComment } from "./tools/linkedInActionsReplyToComment.js";
import { tool$linkedInActionsSendMessage } from "./tools/linkedInActionsSendMessage.js";
import { tool$linkedInScrapersCollectCommentReplies } from "./tools/linkedInScrapersCollectCommentReplies.js";
import { tool$linkedInScrapersCollectComments } from "./tools/linkedInScrapersCollectComments.js";
import { tool$linkedInScrapersCollectLikes } from "./tools/linkedInScrapersCollectLikes.js";
import { tool$linkedInScrapersCollectPosts } from "./tools/linkedInScrapersCollectPosts.js";
import { tool$linkedInScrapersVisitCompany } from "./tools/linkedInScrapersVisitCompany.js";
import { tool$linkedInScrapersVisitProfile } from "./tools/linkedInScrapersVisitProfile.js";
import { tool$linkedInSearchResolveParameters } from "./tools/linkedInSearchResolveParameters.js";
import { tool$linkedInSearchSearchByUrl } from "./tools/linkedInSearchSearchByUrl.js";
import { tool$linkedInSearchSearchCompanies } from "./tools/linkedInSearchSearchCompanies.js";
import { tool$linkedInSearchSearchJobs } from "./tools/linkedInSearchSearchJobs.js";
import { tool$linkedInSearchSearchPeople } from "./tools/linkedInSearchSearchPeople.js";
import { tool$linkedInSearchSearchPosts } from "./tools/linkedInSearchSearchPosts.js";
import { tool$linkedInSearchUnifiedSearch } from "./tools/linkedInSearchUnifiedSearch.js";
import { tool$profileGetFollowers } from "./tools/profileGetFollowers.js";
import { tool$profileGetLimits } from "./tools/profileGetLimits.js";
import { tool$profileGetPosts } from "./tools/profileGetPosts.js";
import { tool$profileGetProfile } from "./tools/profileGetProfile.js";
import { tool$profileRefresh } from "./tools/profileRefresh.js";

export function createMCPServer(deps: {
  logger: ConsoleLogger;
  allowedTools?: string[] | undefined;
  dynamic?: boolean | undefined;
  scopes?: MCPScope[] | undefined;
  getSDK?: () => BereachCore;
  serverURL?: string | undefined;
  security?: SDKOptions["security"] | undefined;
  serverIdx?: SDKOptions["serverIdx"] | undefined;
}) {
  const server = new McpServer({
    name: "Bereach",
    version: "0.1.2",
  });

  const getClient = deps.getSDK || (() =>
    new BereachCore({
      security: deps.security,
      serverURL: deps.serverURL,
      serverIdx: deps.serverIdx,
      debugLogger: deps.logger.level === "debug"
        ? {
          log: (...args) => console.log(...args),
          group: (...args) => console.group(...args),
          groupEnd: (...args) => console.groupEnd(...args),
        }
        : undefined,
    }));

  const scopes = new Set(deps.scopes);

  const allowedTools = deps.allowedTools && new Set(deps.allowedTools);
  const [tool, tools, toolMap] = createRegisterTool(
    deps.logger,
    server,
    getClient,
    scopes,
    allowedTools,
    deps.dynamic,
  );
  const resource = createRegisterResource(
    deps.logger,
    server,
    getClient,
    scopes,
  );
  const resourceTemplate = createRegisterResourceTemplate(
    deps.logger,
    server,
    getClient,
    scopes,
  );
  const prompt = createRegisterPrompt(deps.logger, server, getClient, scopes);
  const register = { tool, resource, resourceTemplate, prompt };
  void register; // suppress unused warnings

  tool(tool$linkedInScrapersCollectLikes);
  tool(tool$linkedInScrapersCollectComments);
  tool(tool$linkedInScrapersCollectCommentReplies);
  tool(tool$linkedInScrapersCollectPosts);
  tool(tool$linkedInScrapersVisitProfile);
  tool(tool$linkedInScrapersVisitCompany);
  tool(tool$linkedInSearchUnifiedSearch);
  tool(tool$linkedInSearchSearchPosts);
  tool(tool$linkedInSearchSearchPeople);
  tool(tool$linkedInSearchSearchCompanies);
  tool(tool$linkedInSearchSearchJobs);
  tool(tool$linkedInSearchSearchByUrl);
  tool(tool$linkedInSearchResolveParameters);
  tool(tool$linkedInActionsConnectProfile);
  tool(tool$linkedInActionsListInvitations);
  tool(tool$linkedInActionsAcceptInvitation);
  tool(tool$linkedInActionsSendMessage);
  tool(tool$linkedInActionsReplyToComment);
  tool(tool$linkedInActionsLikeComment);
  tool(tool$linkedInActionsPublishPost);
  tool(tool$profileGetProfile);
  tool(tool$profileRefresh);
  tool(tool$profileGetPosts);
  tool(tool$profileGetFollowers);
  tool(tool$profileGetLimits);
  tool(tool$campaignsFilter);

  if (deps.dynamic) {
    registerDynamicTools(deps.logger, server, getClient, toolMap, scopes);
  }

  return { server, tools };
}
