/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export type CollectLinkedInLikesRequest = {
  postUrl: string;
  start?: number | undefined;
  count?: number | undefined;
};

export const CollectLinkedInLikesRequest$zodSchema: z.ZodType<
  CollectLinkedInLikesRequest
> = z.object({
  count: z.int().optional(),
  postUrl: z.string(),
  start: z.int().optional(),
});

export type CollectLinkedInLikesInternalServerErrorDetails =
  | string
  | Array<string>;

export const CollectLinkedInLikesInternalServerErrorDetails$zodSchema:
  z.ZodType<CollectLinkedInLikesInternalServerErrorDetails> = z.union([
    z.string(),
    z.array(z.string()),
  ]);

export type CollectLinkedInLikesInternalServerErrorError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const CollectLinkedInLikesInternalServerErrorError$zodSchema: z.ZodType<
  CollectLinkedInLikesInternalServerErrorError
> = z.object({
  code: z.string(),
  details: z.union([
    z.string(),
    z.array(z.string()),
  ]).optional(),
  docs: z.string().optional(),
  message: z.string(),
});

/**
 * The server encountered a situation it does not know how to handle.
 */
export type CollectLinkedInLikesInternalServerErrorResponseBody = {
  success?: boolean | undefined;
  error: CollectLinkedInLikesInternalServerErrorError;
};

export const CollectLinkedInLikesInternalServerErrorResponseBody$zodSchema:
  z.ZodType<CollectLinkedInLikesInternalServerErrorResponseBody> = z.object({
    error: z.lazy(() => CollectLinkedInLikesInternalServerErrorError$zodSchema),
    success: z.boolean().default(false),
  }).describe(
    "The server encountered a situation it does not know how to handle.",
  );

export const CollectLinkedInLikesCode = {
  RateLimitExceeded: "rate_limit_exceeded",
} as const;
export type CollectLinkedInLikesCode = ClosedEnum<
  typeof CollectLinkedInLikesCode
>;

export const CollectLinkedInLikesCode$zodSchema = z.enum([
  "rate_limit_exceeded",
]);

/**
 * Current and max daily usage (null if no daily cap).
 */
export type CollectLinkedInLikesDaily = { current: number; limit: number };

export const CollectLinkedInLikesDaily$zodSchema: z.ZodType<
  CollectLinkedInLikesDaily
> = z.object({
  current: z.int(),
  limit: z.int(),
}).describe("Current and max daily usage (null if no daily cap).");

/**
 * Current and max weekly usage (null if no weekly cap).
 */
export type CollectLinkedInLikesWeekly = { current: number; limit: number };

export const CollectLinkedInLikesWeekly$zodSchema: z.ZodType<
  CollectLinkedInLikesWeekly
> = z.object({
  current: z.int(),
  limit: z.int(),
}).describe("Current and max weekly usage (null if no weekly cap).");

export type CollectLinkedInLikesTooManyRequestsError = {
  code: CollectLinkedInLikesCode;
  message: string;
  docs?: string | undefined;
  retryAfter: number;
  daily: CollectLinkedInLikesDaily | null;
  weekly: CollectLinkedInLikesWeekly | null;
};

export const CollectLinkedInLikesTooManyRequestsError$zodSchema: z.ZodType<
  CollectLinkedInLikesTooManyRequestsError
> = z.object({
  code: CollectLinkedInLikesCode$zodSchema,
  daily: z.lazy(() => CollectLinkedInLikesDaily$zodSchema).nullable(),
  docs: z.string().optional(),
  message: z.string(),
  retryAfter: z.int(),
  weekly: z.lazy(() => CollectLinkedInLikesWeekly$zodSchema).nullable(),
});

/**
 * Rate limit exceeded. Read error.retryAfter for the wait time in seconds.
 */
export type CollectLinkedInLikesTooManyRequestsResponseBody = {
  success?: boolean | undefined;
  error: CollectLinkedInLikesTooManyRequestsError;
};

export const CollectLinkedInLikesTooManyRequestsResponseBody$zodSchema:
  z.ZodType<CollectLinkedInLikesTooManyRequestsResponseBody> = z.object({
    error: z.lazy(() => CollectLinkedInLikesTooManyRequestsError$zodSchema),
    success: z.boolean().default(false),
  }).describe(
    "Rate limit exceeded. Read error.retryAfter for the wait time in seconds.",
  );

export type CollectLinkedInLikesUnprocessableEntityDetails =
  | string
  | Array<string>;

export const CollectLinkedInLikesUnprocessableEntityDetails$zodSchema:
  z.ZodType<CollectLinkedInLikesUnprocessableEntityDetails> = z.union([
    z.string(),
    z.array(z.string()),
  ]);

export type CollectLinkedInLikesUnprocessableEntityError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const CollectLinkedInLikesUnprocessableEntityError$zodSchema: z.ZodType<
  CollectLinkedInLikesUnprocessableEntityError
> = z.object({
  code: z.string(),
  details: z.union([
    z.string(),
    z.array(z.string()),
  ]).optional(),
  docs: z.string().optional(),
  message: z.string(),
});

/**
 * The request was well-formed but was unable to be followed due to semantic errors.
 */
export type CollectLinkedInLikesUnprocessableEntityResponseBody = {
  success?: boolean | undefined;
  error: CollectLinkedInLikesUnprocessableEntityError;
};

export const CollectLinkedInLikesUnprocessableEntityResponseBody$zodSchema:
  z.ZodType<CollectLinkedInLikesUnprocessableEntityResponseBody> = z.object({
    error: z.lazy(() => CollectLinkedInLikesUnprocessableEntityError$zodSchema),
    success: z.boolean().default(false),
  }).describe(
    "The request was well-formed but was unable to be followed due to semantic errors.",
  );

export type CollectLinkedInLikesGoneDetails = string | Array<string>;

export const CollectLinkedInLikesGoneDetails$zodSchema: z.ZodType<
  CollectLinkedInLikesGoneDetails
> = z.union([
  z.string(),
  z.array(z.string()),
]);

export type CollectLinkedInLikesGoneError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const CollectLinkedInLikesGoneError$zodSchema: z.ZodType<
  CollectLinkedInLikesGoneError
> = z.object({
  code: z.string(),
  details: z.union([
    z.string(),
    z.array(z.string()),
  ]).optional(),
  docs: z.string().optional(),
  message: z.string(),
});

/**
 * The requested content has been permanently deleted from the server.
 */
export type CollectLinkedInLikesGoneResponseBody = {
  success?: boolean | undefined;
  error: CollectLinkedInLikesGoneError;
};

export const CollectLinkedInLikesGoneResponseBody$zodSchema: z.ZodType<
  CollectLinkedInLikesGoneResponseBody
> = z.object({
  error: z.lazy(() => CollectLinkedInLikesGoneError$zodSchema),
  success: z.boolean().default(false),
}).describe(
  "The requested content has been permanently deleted from the server.",
);

export type CollectLinkedInLikesConflictDetails = string | Array<string>;

export const CollectLinkedInLikesConflictDetails$zodSchema: z.ZodType<
  CollectLinkedInLikesConflictDetails
> = z.union([
  z.string(),
  z.array(z.string()),
]);

export type CollectLinkedInLikesConflictError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const CollectLinkedInLikesConflictError$zodSchema: z.ZodType<
  CollectLinkedInLikesConflictError
> = z.object({
  code: z.string(),
  details: z.union([
    z.string(),
    z.array(z.string()),
  ]).optional(),
  docs: z.string().optional(),
  message: z.string(),
});

/**
 * The request conflicts with the current state of the server.
 */
export type CollectLinkedInLikesConflictResponseBody = {
  success?: boolean | undefined;
  error: CollectLinkedInLikesConflictError;
};

export const CollectLinkedInLikesConflictResponseBody$zodSchema: z.ZodType<
  CollectLinkedInLikesConflictResponseBody
> = z.object({
  error: z.lazy(() => CollectLinkedInLikesConflictError$zodSchema),
  success: z.boolean().default(false),
}).describe("The request conflicts with the current state of the server.");

export type CollectLinkedInLikesNotFoundDetails = string | Array<string>;

export const CollectLinkedInLikesNotFoundDetails$zodSchema: z.ZodType<
  CollectLinkedInLikesNotFoundDetails
> = z.union([
  z.string(),
  z.array(z.string()),
]);

export type CollectLinkedInLikesNotFoundError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const CollectLinkedInLikesNotFoundError$zodSchema: z.ZodType<
  CollectLinkedInLikesNotFoundError
> = z.object({
  code: z.string(),
  details: z.union([
    z.string(),
    z.array(z.string()),
  ]).optional(),
  docs: z.string().optional(),
  message: z.string(),
});

/**
 * The server cannot find the requested resource.
 */
export type CollectLinkedInLikesNotFoundResponseBody = {
  success?: boolean | undefined;
  error: CollectLinkedInLikesNotFoundError;
};

export const CollectLinkedInLikesNotFoundResponseBody$zodSchema: z.ZodType<
  CollectLinkedInLikesNotFoundResponseBody
> = z.object({
  error: z.lazy(() => CollectLinkedInLikesNotFoundError$zodSchema),
  success: z.boolean().default(false),
}).describe("The server cannot find the requested resource.");

export type CollectLinkedInLikesForbiddenDetails = string | Array<string>;

export const CollectLinkedInLikesForbiddenDetails$zodSchema: z.ZodType<
  CollectLinkedInLikesForbiddenDetails
> = z.union([
  z.string(),
  z.array(z.string()),
]);

export type CollectLinkedInLikesForbiddenError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const CollectLinkedInLikesForbiddenError$zodSchema: z.ZodType<
  CollectLinkedInLikesForbiddenError
> = z.object({
  code: z.string(),
  details: z.union([
    z.string(),
    z.array(z.string()),
  ]).optional(),
  docs: z.string().optional(),
  message: z.string(),
});

/**
 * The client does not have access rights to the content.
 */
export type CollectLinkedInLikesForbiddenResponseBody = {
  success?: boolean | undefined;
  error: CollectLinkedInLikesForbiddenError;
};

export const CollectLinkedInLikesForbiddenResponseBody$zodSchema: z.ZodType<
  CollectLinkedInLikesForbiddenResponseBody
> = z.object({
  error: z.lazy(() => CollectLinkedInLikesForbiddenError$zodSchema),
  success: z.boolean().default(false),
}).describe("The client does not have access rights to the content.");

export type CollectLinkedInLikesUnauthorizedDetails = string | Array<string>;

export const CollectLinkedInLikesUnauthorizedDetails$zodSchema: z.ZodType<
  CollectLinkedInLikesUnauthorizedDetails
> = z.union([
  z.string(),
  z.array(z.string()),
]);

export type CollectLinkedInLikesUnauthorizedError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const CollectLinkedInLikesUnauthorizedError$zodSchema: z.ZodType<
  CollectLinkedInLikesUnauthorizedError
> = z.object({
  code: z.string(),
  details: z.union([
    z.string(),
    z.array(z.string()),
  ]).optional(),
  docs: z.string().optional(),
  message: z.string(),
});

/**
 * Although HTTP specifies "unauthorized", this response means "unauthenticated". Authenticate to continue.
 */
export type CollectLinkedInLikesUnauthorizedResponseBody = {
  success?: boolean | undefined;
  error: CollectLinkedInLikesUnauthorizedError;
};

export const CollectLinkedInLikesUnauthorizedResponseBody$zodSchema: z.ZodType<
  CollectLinkedInLikesUnauthorizedResponseBody
> = z.object({
  error: z.lazy(() => CollectLinkedInLikesUnauthorizedError$zodSchema),
  success: z.boolean().default(false),
}).describe(
  "Although HTTP specifies \"unauthorized\", this response means \"unauthenticated\". Authenticate to continue.",
);

export type CollectLinkedInLikesBadRequestDetails = string | Array<string>;

export const CollectLinkedInLikesBadRequestDetails$zodSchema: z.ZodType<
  CollectLinkedInLikesBadRequestDetails
> = z.union([
  z.string(),
  z.array(z.string()),
]);

export type CollectLinkedInLikesBadRequestError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const CollectLinkedInLikesBadRequestError$zodSchema: z.ZodType<
  CollectLinkedInLikesBadRequestError
> = z.object({
  code: z.string(),
  details: z.union([
    z.string(),
    z.array(z.string()),
  ]).optional(),
  docs: z.string().optional(),
  message: z.string(),
});

/**
 * The server cannot or will not process the request due to something that is perceived to be a client error.
 */
export type CollectLinkedInLikesBadRequestResponseBody = {
  success?: boolean | undefined;
  error: CollectLinkedInLikesBadRequestError;
};

export const CollectLinkedInLikesBadRequestResponseBody$zodSchema: z.ZodType<
  CollectLinkedInLikesBadRequestResponseBody
> = z.object({
  error: z.lazy(() => CollectLinkedInLikesBadRequestError$zodSchema),
  success: z.boolean().default(false),
}).describe(
  "The server cannot or will not process the request due to something that is perceived to be a client error.",
);

export const CollectLinkedInLikesType = {
  Like: "like",
} as const;
export type CollectLinkedInLikesType = ClosedEnum<
  typeof CollectLinkedInLikesType
>;

export const CollectLinkedInLikesType$zodSchema = z.enum([
  "like",
]);

export type CollectLinkedInLikesProfile = {
  name: string;
  headline?: string | null | undefined;
  profileUrl?: string | null | undefined;
  imageUrl?: string | null | undefined;
  type: CollectLinkedInLikesType;
};

export const CollectLinkedInLikesProfile$zodSchema: z.ZodType<
  CollectLinkedInLikesProfile
> = z.object({
  headline: z.string().nullable().optional(),
  imageUrl: z.string().nullable().optional(),
  name: z.string(),
  profileUrl: z.string().nullable().optional(),
  type: CollectLinkedInLikesType$zodSchema,
});

/**
 * List of profiles who liked the post
 */
export type CollectLinkedInLikesResponseBody = {
  success: boolean;
  profiles: Array<CollectLinkedInLikesProfile>;
  count: number;
  total: number;
  start: number;
  hasMore: boolean;
  previousTotal: number | null;
  creditsUsed: number;
  retryAfter: number;
};

export const CollectLinkedInLikesResponseBody$zodSchema: z.ZodType<
  CollectLinkedInLikesResponseBody
> = z.object({
  count: z.int(),
  creditsUsed: z.int(),
  hasMore: z.boolean(),
  previousTotal: z.int().nullable(),
  profiles: z.array(z.lazy(() => CollectLinkedInLikesProfile$zodSchema)),
  retryAfter: z.int(),
  start: z.int(),
  success: z.boolean(),
  total: z.int(),
}).describe("List of profiles who liked the post");

export type CollectLinkedInLikesResponse =
  | CollectLinkedInLikesResponseBody
  | CollectLinkedInLikesBadRequestResponseBody
  | CollectLinkedInLikesUnauthorizedResponseBody
  | CollectLinkedInLikesForbiddenResponseBody
  | CollectLinkedInLikesNotFoundResponseBody
  | CollectLinkedInLikesConflictResponseBody
  | CollectLinkedInLikesGoneResponseBody
  | CollectLinkedInLikesUnprocessableEntityResponseBody
  | CollectLinkedInLikesTooManyRequestsResponseBody
  | CollectLinkedInLikesInternalServerErrorResponseBody;

export const CollectLinkedInLikesResponse$zodSchema: z.ZodType<
  CollectLinkedInLikesResponse
> = z.union([
  z.lazy(() => CollectLinkedInLikesResponseBody$zodSchema),
  z.lazy(() => CollectLinkedInLikesBadRequestResponseBody$zodSchema),
  z.lazy(() => CollectLinkedInLikesUnauthorizedResponseBody$zodSchema),
  z.lazy(() => CollectLinkedInLikesForbiddenResponseBody$zodSchema),
  z.lazy(() => CollectLinkedInLikesNotFoundResponseBody$zodSchema),
  z.lazy(() => CollectLinkedInLikesConflictResponseBody$zodSchema),
  z.lazy(() => CollectLinkedInLikesGoneResponseBody$zodSchema),
  z.lazy(() => CollectLinkedInLikesUnprocessableEntityResponseBody$zodSchema),
  z.lazy(() => CollectLinkedInLikesTooManyRequestsResponseBody$zodSchema),
  z.lazy(() => CollectLinkedInLikesInternalServerErrorResponseBody$zodSchema),
]);
