/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export type GetMyCreditsInternalServerErrorDetails = string | Array<string>;

export const GetMyCreditsInternalServerErrorDetails$zodSchema: z.ZodType<
  GetMyCreditsInternalServerErrorDetails
> = z.union([
  z.string(),
  z.array(z.string()),
]);

export type GetMyCreditsInternalServerErrorError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const GetMyCreditsInternalServerErrorError$zodSchema: z.ZodType<
  GetMyCreditsInternalServerErrorError
> = z.object({
  code: z.string(),
  details: z.union([
    z.string(),
    z.array(z.string()),
  ]).optional(),
  docs: z.string().optional(),
  message: z.string(),
});

/**
 * The server encountered a situation it does not know how to handle.
 */
export type GetMyCreditsInternalServerErrorResponseBody = {
  success?: boolean | undefined;
  error: GetMyCreditsInternalServerErrorError;
};

export const GetMyCreditsInternalServerErrorResponseBody$zodSchema: z.ZodType<
  GetMyCreditsInternalServerErrorResponseBody
> = z.object({
  error: z.lazy(() => GetMyCreditsInternalServerErrorError$zodSchema),
  success: z.boolean().default(false),
}).describe(
  "The server encountered a situation it does not know how to handle.",
);

export const GetMyCreditsCode = {
  RateLimitExceeded: "rate_limit_exceeded",
} as const;
export type GetMyCreditsCode = ClosedEnum<typeof GetMyCreditsCode>;

export const GetMyCreditsCode$zodSchema = z.enum([
  "rate_limit_exceeded",
]);

/**
 * Current and max daily usage (null if no daily cap).
 */
export type GetMyCreditsDaily = { current: number; limit: number };

export const GetMyCreditsDaily$zodSchema: z.ZodType<GetMyCreditsDaily> = z
  .object({
    current: z.int(),
    limit: z.int(),
  }).describe("Current and max daily usage (null if no daily cap).");

/**
 * Current and max weekly usage (null if no weekly cap).
 */
export type GetMyCreditsWeekly = { current: number; limit: number };

export const GetMyCreditsWeekly$zodSchema: z.ZodType<GetMyCreditsWeekly> = z
  .object({
    current: z.int(),
    limit: z.int(),
  }).describe("Current and max weekly usage (null if no weekly cap).");

export type GetMyCreditsTooManyRequestsError = {
  code: GetMyCreditsCode;
  message: string;
  docs?: string | undefined;
  retryAfter: number;
  daily: GetMyCreditsDaily | null;
  weekly: GetMyCreditsWeekly | null;
};

export const GetMyCreditsTooManyRequestsError$zodSchema: z.ZodType<
  GetMyCreditsTooManyRequestsError
> = z.object({
  code: GetMyCreditsCode$zodSchema,
  daily: z.lazy(() => GetMyCreditsDaily$zodSchema).nullable(),
  docs: z.string().optional(),
  message: z.string(),
  retryAfter: z.int(),
  weekly: z.lazy(() => GetMyCreditsWeekly$zodSchema).nullable(),
});

/**
 * Rate limit exceeded. Read error.retryAfter for the wait time in seconds.
 */
export type GetMyCreditsTooManyRequestsResponseBody = {
  success?: boolean | undefined;
  error: GetMyCreditsTooManyRequestsError;
};

export const GetMyCreditsTooManyRequestsResponseBody$zodSchema: z.ZodType<
  GetMyCreditsTooManyRequestsResponseBody
> = z.object({
  error: z.lazy(() => GetMyCreditsTooManyRequestsError$zodSchema),
  success: z.boolean().default(false),
}).describe(
  "Rate limit exceeded. Read error.retryAfter for the wait time in seconds.",
);

export type GetMyCreditsUnprocessableEntityDetails = string | Array<string>;

export const GetMyCreditsUnprocessableEntityDetails$zodSchema: z.ZodType<
  GetMyCreditsUnprocessableEntityDetails
> = z.union([
  z.string(),
  z.array(z.string()),
]);

export type GetMyCreditsUnprocessableEntityError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const GetMyCreditsUnprocessableEntityError$zodSchema: z.ZodType<
  GetMyCreditsUnprocessableEntityError
> = z.object({
  code: z.string(),
  details: z.union([
    z.string(),
    z.array(z.string()),
  ]).optional(),
  docs: z.string().optional(),
  message: z.string(),
});

/**
 * The request was well-formed but was unable to be followed due to semantic errors.
 */
export type GetMyCreditsUnprocessableEntityResponseBody = {
  success?: boolean | undefined;
  error: GetMyCreditsUnprocessableEntityError;
};

export const GetMyCreditsUnprocessableEntityResponseBody$zodSchema: z.ZodType<
  GetMyCreditsUnprocessableEntityResponseBody
> = z.object({
  error: z.lazy(() => GetMyCreditsUnprocessableEntityError$zodSchema),
  success: z.boolean().default(false),
}).describe(
  "The request was well-formed but was unable to be followed due to semantic errors.",
);

export type GetMyCreditsGoneDetails = string | Array<string>;

export const GetMyCreditsGoneDetails$zodSchema: z.ZodType<
  GetMyCreditsGoneDetails
> = z.union([
  z.string(),
  z.array(z.string()),
]);

export type GetMyCreditsGoneError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const GetMyCreditsGoneError$zodSchema: z.ZodType<GetMyCreditsGoneError> =
  z.object({
    code: z.string(),
    details: z.union([
      z.string(),
      z.array(z.string()),
    ]).optional(),
    docs: z.string().optional(),
    message: z.string(),
  });

/**
 * The requested content has been permanently deleted from the server.
 */
export type GetMyCreditsGoneResponseBody = {
  success?: boolean | undefined;
  error: GetMyCreditsGoneError;
};

export const GetMyCreditsGoneResponseBody$zodSchema: z.ZodType<
  GetMyCreditsGoneResponseBody
> = z.object({
  error: z.lazy(() => GetMyCreditsGoneError$zodSchema),
  success: z.boolean().default(false),
}).describe(
  "The requested content has been permanently deleted from the server.",
);

export type GetMyCreditsConflictDetails = string | Array<string>;

export const GetMyCreditsConflictDetails$zodSchema: z.ZodType<
  GetMyCreditsConflictDetails
> = z.union([
  z.string(),
  z.array(z.string()),
]);

export type GetMyCreditsConflictError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const GetMyCreditsConflictError$zodSchema: z.ZodType<
  GetMyCreditsConflictError
> = z.object({
  code: z.string(),
  details: z.union([
    z.string(),
    z.array(z.string()),
  ]).optional(),
  docs: z.string().optional(),
  message: z.string(),
});

/**
 * The request conflicts with the current state of the server.
 */
export type GetMyCreditsConflictResponseBody = {
  success?: boolean | undefined;
  error: GetMyCreditsConflictError;
};

export const GetMyCreditsConflictResponseBody$zodSchema: z.ZodType<
  GetMyCreditsConflictResponseBody
> = z.object({
  error: z.lazy(() => GetMyCreditsConflictError$zodSchema),
  success: z.boolean().default(false),
}).describe("The request conflicts with the current state of the server.");

export type GetMyCreditsNotFoundDetails = string | Array<string>;

export const GetMyCreditsNotFoundDetails$zodSchema: z.ZodType<
  GetMyCreditsNotFoundDetails
> = z.union([
  z.string(),
  z.array(z.string()),
]);

export type GetMyCreditsNotFoundError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const GetMyCreditsNotFoundError$zodSchema: z.ZodType<
  GetMyCreditsNotFoundError
> = z.object({
  code: z.string(),
  details: z.union([
    z.string(),
    z.array(z.string()),
  ]).optional(),
  docs: z.string().optional(),
  message: z.string(),
});

/**
 * The server cannot find the requested resource.
 */
export type GetMyCreditsNotFoundResponseBody = {
  success?: boolean | undefined;
  error: GetMyCreditsNotFoundError;
};

export const GetMyCreditsNotFoundResponseBody$zodSchema: z.ZodType<
  GetMyCreditsNotFoundResponseBody
> = z.object({
  error: z.lazy(() => GetMyCreditsNotFoundError$zodSchema),
  success: z.boolean().default(false),
}).describe("The server cannot find the requested resource.");

export type GetMyCreditsForbiddenDetails = string | Array<string>;

export const GetMyCreditsForbiddenDetails$zodSchema: z.ZodType<
  GetMyCreditsForbiddenDetails
> = z.union([
  z.string(),
  z.array(z.string()),
]);

export type GetMyCreditsForbiddenError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const GetMyCreditsForbiddenError$zodSchema: z.ZodType<
  GetMyCreditsForbiddenError
> = z.object({
  code: z.string(),
  details: z.union([
    z.string(),
    z.array(z.string()),
  ]).optional(),
  docs: z.string().optional(),
  message: z.string(),
});

/**
 * The client does not have access rights to the content.
 */
export type GetMyCreditsForbiddenResponseBody = {
  success?: boolean | undefined;
  error: GetMyCreditsForbiddenError;
};

export const GetMyCreditsForbiddenResponseBody$zodSchema: z.ZodType<
  GetMyCreditsForbiddenResponseBody
> = z.object({
  error: z.lazy(() => GetMyCreditsForbiddenError$zodSchema),
  success: z.boolean().default(false),
}).describe("The client does not have access rights to the content.");

export type GetMyCreditsUnauthorizedDetails = string | Array<string>;

export const GetMyCreditsUnauthorizedDetails$zodSchema: z.ZodType<
  GetMyCreditsUnauthorizedDetails
> = z.union([
  z.string(),
  z.array(z.string()),
]);

export type GetMyCreditsUnauthorizedError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const GetMyCreditsUnauthorizedError$zodSchema: z.ZodType<
  GetMyCreditsUnauthorizedError
> = z.object({
  code: z.string(),
  details: z.union([
    z.string(),
    z.array(z.string()),
  ]).optional(),
  docs: z.string().optional(),
  message: z.string(),
});

/**
 * Although HTTP specifies "unauthorized", this response means "unauthenticated". Authenticate to continue.
 */
export type GetMyCreditsUnauthorizedResponseBody = {
  success?: boolean | undefined;
  error: GetMyCreditsUnauthorizedError;
};

export const GetMyCreditsUnauthorizedResponseBody$zodSchema: z.ZodType<
  GetMyCreditsUnauthorizedResponseBody
> = z.object({
  error: z.lazy(() => GetMyCreditsUnauthorizedError$zodSchema),
  success: z.boolean().default(false),
}).describe(
  "Although HTTP specifies \"unauthorized\", this response means \"unauthenticated\". Authenticate to continue.",
);

export type GetMyCreditsBadRequestDetails = string | Array<string>;

export const GetMyCreditsBadRequestDetails$zodSchema: z.ZodType<
  GetMyCreditsBadRequestDetails
> = z.union([
  z.string(),
  z.array(z.string()),
]);

export type GetMyCreditsBadRequestError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const GetMyCreditsBadRequestError$zodSchema: z.ZodType<
  GetMyCreditsBadRequestError
> = z.object({
  code: z.string(),
  details: z.union([
    z.string(),
    z.array(z.string()),
  ]).optional(),
  docs: z.string().optional(),
  message: z.string(),
});

/**
 * The server cannot or will not process the request due to something that is perceived to be a client error.
 */
export type GetMyCreditsBadRequestResponseBody = {
  success?: boolean | undefined;
  error: GetMyCreditsBadRequestError;
};

export const GetMyCreditsBadRequestResponseBody$zodSchema: z.ZodType<
  GetMyCreditsBadRequestResponseBody
> = z.object({
  error: z.lazy(() => GetMyCreditsBadRequestError$zodSchema),
  success: z.boolean().default(false),
}).describe(
  "The server cannot or will not process the request due to something that is perceived to be a client error.",
);

export type Credits = {
  current: number;
  limit: number;
  remaining: number;
  percentage: number;
};

export const Credits$zodSchema: z.ZodType<Credits> = z.object({
  current: z.int(),
  limit: z.int(),
  percentage: z.number(),
  remaining: z.int(),
});

/**
 * Credit balance for the workspace
 */
export type GetMyCreditsResponseBody = {
  success: boolean;
  credits: Credits;
  creditsUsed: number;
  retryAfter: number;
};

export const GetMyCreditsResponseBody$zodSchema: z.ZodType<
  GetMyCreditsResponseBody
> = z.object({
  credits: z.lazy(() => Credits$zodSchema),
  creditsUsed: z.int(),
  retryAfter: z.int(),
  success: z.boolean(),
}).describe("Credit balance for the workspace");

export type GetMyCreditsResponse =
  | GetMyCreditsResponseBody
  | GetMyCreditsBadRequestResponseBody
  | GetMyCreditsUnauthorizedResponseBody
  | GetMyCreditsForbiddenResponseBody
  | GetMyCreditsNotFoundResponseBody
  | GetMyCreditsConflictResponseBody
  | GetMyCreditsGoneResponseBody
  | GetMyCreditsUnprocessableEntityResponseBody
  | GetMyCreditsTooManyRequestsResponseBody
  | GetMyCreditsInternalServerErrorResponseBody;

export const GetMyCreditsResponse$zodSchema: z.ZodType<GetMyCreditsResponse> = z
  .union([
    z.lazy(() => GetMyCreditsResponseBody$zodSchema),
    z.lazy(() => GetMyCreditsBadRequestResponseBody$zodSchema),
    z.lazy(() => GetMyCreditsUnauthorizedResponseBody$zodSchema),
    z.lazy(() => GetMyCreditsForbiddenResponseBody$zodSchema),
    z.lazy(() => GetMyCreditsNotFoundResponseBody$zodSchema),
    z.lazy(() => GetMyCreditsConflictResponseBody$zodSchema),
    z.lazy(() => GetMyCreditsGoneResponseBody$zodSchema),
    z.lazy(() => GetMyCreditsUnprocessableEntityResponseBody$zodSchema),
    z.lazy(() => GetMyCreditsTooManyRequestsResponseBody$zodSchema),
    z.lazy(() => GetMyCreditsInternalServerErrorResponseBody$zodSchema),
  ]);
