/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export type ListInboxConversationsRequest = { nextCursor?: string | undefined };

export const ListInboxConversationsRequest$zodSchema: z.ZodType<
  ListInboxConversationsRequest
> = z.object({
  nextCursor: z.string().optional(),
});

export type ListInboxConversationsInternalServerErrorDetails =
  | string
  | Array<string>;

export const ListInboxConversationsInternalServerErrorDetails$zodSchema:
  z.ZodType<ListInboxConversationsInternalServerErrorDetails> = z.union([
    z.string(),
    z.array(z.string()),
  ]);

export type ListInboxConversationsInternalServerErrorError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const ListInboxConversationsInternalServerErrorError$zodSchema:
  z.ZodType<ListInboxConversationsInternalServerErrorError> = z.object({
    code: z.string(),
    details: z.union([
      z.string(),
      z.array(z.string()),
    ]).optional(),
    docs: z.string().optional(),
    message: z.string(),
  });

/**
 * The server encountered a situation it does not know how to handle.
 */
export type ListInboxConversationsInternalServerErrorResponseBody = {
  success?: boolean | undefined;
  error: ListInboxConversationsInternalServerErrorError;
};

export const ListInboxConversationsInternalServerErrorResponseBody$zodSchema:
  z.ZodType<ListInboxConversationsInternalServerErrorResponseBody> = z.object({
    error: z.lazy(() =>
      ListInboxConversationsInternalServerErrorError$zodSchema
    ),
    success: z.boolean().default(false),
  }).describe(
    "The server encountered a situation it does not know how to handle.",
  );

export const ListInboxConversationsCode = {
  RateLimitExceeded: "rate_limit_exceeded",
} as const;
export type ListInboxConversationsCode = ClosedEnum<
  typeof ListInboxConversationsCode
>;

export const ListInboxConversationsCode$zodSchema = z.enum([
  "rate_limit_exceeded",
]);

/**
 * Current and max daily usage (null if no daily cap).
 */
export type ListInboxConversationsDaily = { current: number; limit: number };

export const ListInboxConversationsDaily$zodSchema: z.ZodType<
  ListInboxConversationsDaily
> = z.object({
  current: z.int(),
  limit: z.int(),
}).describe("Current and max daily usage (null if no daily cap).");

/**
 * Current and max weekly usage (null if no weekly cap).
 */
export type ListInboxConversationsWeekly = { current: number; limit: number };

export const ListInboxConversationsWeekly$zodSchema: z.ZodType<
  ListInboxConversationsWeekly
> = z.object({
  current: z.int(),
  limit: z.int(),
}).describe("Current and max weekly usage (null if no weekly cap).");

export type ListInboxConversationsTooManyRequestsError = {
  code: ListInboxConversationsCode;
  message: string;
  docs?: string | undefined;
  retryAfter: number;
  daily: ListInboxConversationsDaily | null;
  weekly: ListInboxConversationsWeekly | null;
};

export const ListInboxConversationsTooManyRequestsError$zodSchema: z.ZodType<
  ListInboxConversationsTooManyRequestsError
> = z.object({
  code: ListInboxConversationsCode$zodSchema,
  daily: z.lazy(() => ListInboxConversationsDaily$zodSchema).nullable(),
  docs: z.string().optional(),
  message: z.string(),
  retryAfter: z.int(),
  weekly: z.lazy(() => ListInboxConversationsWeekly$zodSchema).nullable(),
});

/**
 * Rate limit exceeded. Read error.retryAfter for the wait time in seconds.
 */
export type ListInboxConversationsTooManyRequestsResponseBody = {
  success?: boolean | undefined;
  error: ListInboxConversationsTooManyRequestsError;
};

export const ListInboxConversationsTooManyRequestsResponseBody$zodSchema:
  z.ZodType<ListInboxConversationsTooManyRequestsResponseBody> = z.object({
    error: z.lazy(() => ListInboxConversationsTooManyRequestsError$zodSchema),
    success: z.boolean().default(false),
  }).describe(
    "Rate limit exceeded. Read error.retryAfter for the wait time in seconds.",
  );

export type ListInboxConversationsUnprocessableEntityDetails =
  | string
  | Array<string>;

export const ListInboxConversationsUnprocessableEntityDetails$zodSchema:
  z.ZodType<ListInboxConversationsUnprocessableEntityDetails> = z.union([
    z.string(),
    z.array(z.string()),
  ]);

export type ListInboxConversationsUnprocessableEntityError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const ListInboxConversationsUnprocessableEntityError$zodSchema:
  z.ZodType<ListInboxConversationsUnprocessableEntityError> = z.object({
    code: z.string(),
    details: z.union([
      z.string(),
      z.array(z.string()),
    ]).optional(),
    docs: z.string().optional(),
    message: z.string(),
  });

/**
 * The request was well-formed but was unable to be followed due to semantic errors.
 */
export type ListInboxConversationsUnprocessableEntityResponseBody = {
  success?: boolean | undefined;
  error: ListInboxConversationsUnprocessableEntityError;
};

export const ListInboxConversationsUnprocessableEntityResponseBody$zodSchema:
  z.ZodType<ListInboxConversationsUnprocessableEntityResponseBody> = z.object({
    error: z.lazy(() =>
      ListInboxConversationsUnprocessableEntityError$zodSchema
    ),
    success: z.boolean().default(false),
  }).describe(
    "The request was well-formed but was unable to be followed due to semantic errors.",
  );

export type ListInboxConversationsGoneDetails = string | Array<string>;

export const ListInboxConversationsGoneDetails$zodSchema: z.ZodType<
  ListInboxConversationsGoneDetails
> = z.union([
  z.string(),
  z.array(z.string()),
]);

export type ListInboxConversationsGoneError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const ListInboxConversationsGoneError$zodSchema: z.ZodType<
  ListInboxConversationsGoneError
> = z.object({
  code: z.string(),
  details: z.union([
    z.string(),
    z.array(z.string()),
  ]).optional(),
  docs: z.string().optional(),
  message: z.string(),
});

/**
 * The requested content has been permanently deleted from the server.
 */
export type ListInboxConversationsGoneResponseBody = {
  success?: boolean | undefined;
  error: ListInboxConversationsGoneError;
};

export const ListInboxConversationsGoneResponseBody$zodSchema: z.ZodType<
  ListInboxConversationsGoneResponseBody
> = z.object({
  error: z.lazy(() => ListInboxConversationsGoneError$zodSchema),
  success: z.boolean().default(false),
}).describe(
  "The requested content has been permanently deleted from the server.",
);

export type ListInboxConversationsConflictDetails = string | Array<string>;

export const ListInboxConversationsConflictDetails$zodSchema: z.ZodType<
  ListInboxConversationsConflictDetails
> = z.union([
  z.string(),
  z.array(z.string()),
]);

export type ListInboxConversationsConflictError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const ListInboxConversationsConflictError$zodSchema: z.ZodType<
  ListInboxConversationsConflictError
> = z.object({
  code: z.string(),
  details: z.union([
    z.string(),
    z.array(z.string()),
  ]).optional(),
  docs: z.string().optional(),
  message: z.string(),
});

/**
 * The request conflicts with the current state of the server.
 */
export type ListInboxConversationsConflictResponseBody = {
  success?: boolean | undefined;
  error: ListInboxConversationsConflictError;
};

export const ListInboxConversationsConflictResponseBody$zodSchema: z.ZodType<
  ListInboxConversationsConflictResponseBody
> = z.object({
  error: z.lazy(() => ListInboxConversationsConflictError$zodSchema),
  success: z.boolean().default(false),
}).describe("The request conflicts with the current state of the server.");

export type ListInboxConversationsNotFoundDetails = string | Array<string>;

export const ListInboxConversationsNotFoundDetails$zodSchema: z.ZodType<
  ListInboxConversationsNotFoundDetails
> = z.union([
  z.string(),
  z.array(z.string()),
]);

export type ListInboxConversationsNotFoundError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const ListInboxConversationsNotFoundError$zodSchema: z.ZodType<
  ListInboxConversationsNotFoundError
> = z.object({
  code: z.string(),
  details: z.union([
    z.string(),
    z.array(z.string()),
  ]).optional(),
  docs: z.string().optional(),
  message: z.string(),
});

/**
 * The server cannot find the requested resource.
 */
export type ListInboxConversationsNotFoundResponseBody = {
  success?: boolean | undefined;
  error: ListInboxConversationsNotFoundError;
};

export const ListInboxConversationsNotFoundResponseBody$zodSchema: z.ZodType<
  ListInboxConversationsNotFoundResponseBody
> = z.object({
  error: z.lazy(() => ListInboxConversationsNotFoundError$zodSchema),
  success: z.boolean().default(false),
}).describe("The server cannot find the requested resource.");

export type ListInboxConversationsForbiddenDetails = string | Array<string>;

export const ListInboxConversationsForbiddenDetails$zodSchema: z.ZodType<
  ListInboxConversationsForbiddenDetails
> = z.union([
  z.string(),
  z.array(z.string()),
]);

export type ListInboxConversationsForbiddenError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const ListInboxConversationsForbiddenError$zodSchema: z.ZodType<
  ListInboxConversationsForbiddenError
> = z.object({
  code: z.string(),
  details: z.union([
    z.string(),
    z.array(z.string()),
  ]).optional(),
  docs: z.string().optional(),
  message: z.string(),
});

/**
 * The client does not have access rights to the content.
 */
export type ListInboxConversationsForbiddenResponseBody = {
  success?: boolean | undefined;
  error: ListInboxConversationsForbiddenError;
};

export const ListInboxConversationsForbiddenResponseBody$zodSchema: z.ZodType<
  ListInboxConversationsForbiddenResponseBody
> = z.object({
  error: z.lazy(() => ListInboxConversationsForbiddenError$zodSchema),
  success: z.boolean().default(false),
}).describe("The client does not have access rights to the content.");

export type ListInboxConversationsUnauthorizedDetails = string | Array<string>;

export const ListInboxConversationsUnauthorizedDetails$zodSchema: z.ZodType<
  ListInboxConversationsUnauthorizedDetails
> = z.union([
  z.string(),
  z.array(z.string()),
]);

export type ListInboxConversationsUnauthorizedError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const ListInboxConversationsUnauthorizedError$zodSchema: z.ZodType<
  ListInboxConversationsUnauthorizedError
> = z.object({
  code: z.string(),
  details: z.union([
    z.string(),
    z.array(z.string()),
  ]).optional(),
  docs: z.string().optional(),
  message: z.string(),
});

/**
 * Although HTTP specifies "unauthorized", this response means "unauthenticated". Authenticate to continue.
 */
export type ListInboxConversationsUnauthorizedResponseBody = {
  success?: boolean | undefined;
  error: ListInboxConversationsUnauthorizedError;
};

export const ListInboxConversationsUnauthorizedResponseBody$zodSchema:
  z.ZodType<ListInboxConversationsUnauthorizedResponseBody> = z.object({
    error: z.lazy(() => ListInboxConversationsUnauthorizedError$zodSchema),
    success: z.boolean().default(false),
  }).describe(
    "Although HTTP specifies \"unauthorized\", this response means \"unauthenticated\". Authenticate to continue.",
  );

export type ListInboxConversationsBadRequestDetails = string | Array<string>;

export const ListInboxConversationsBadRequestDetails$zodSchema: z.ZodType<
  ListInboxConversationsBadRequestDetails
> = z.union([
  z.string(),
  z.array(z.string()),
]);

export type ListInboxConversationsBadRequestError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const ListInboxConversationsBadRequestError$zodSchema: z.ZodType<
  ListInboxConversationsBadRequestError
> = z.object({
  code: z.string(),
  details: z.union([
    z.string(),
    z.array(z.string()),
  ]).optional(),
  docs: z.string().optional(),
  message: z.string(),
});

/**
 * The server cannot or will not process the request due to something that is perceived to be a client error.
 */
export type ListInboxConversationsBadRequestResponseBody = {
  success?: boolean | undefined;
  error: ListInboxConversationsBadRequestError;
};

export const ListInboxConversationsBadRequestResponseBody$zodSchema: z.ZodType<
  ListInboxConversationsBadRequestResponseBody
> = z.object({
  error: z.lazy(() => ListInboxConversationsBadRequestError$zodSchema),
  success: z.boolean().default(false),
}).describe(
  "The server cannot or will not process the request due to something that is perceived to be a client error.",
);

export type ListInboxConversationsParticipant = {
  profileUrn: string;
  firstName: string;
  lastName: string;
  profileUrl: string;
  headline: string | null;
  profilePicture: string | null;
};

export const ListInboxConversationsParticipant$zodSchema: z.ZodType<
  ListInboxConversationsParticipant
> = z.object({
  firstName: z.string(),
  headline: z.string().nullable(),
  lastName: z.string(),
  profilePicture: z.string().nullable(),
  profileUrl: z.string(),
  profileUrn: z.string(),
});

export type ListInboxConversationsLastMessage = {
  text: string;
  deliveredAt: number;
  senderProfileUrn: string;
};

export const ListInboxConversationsLastMessage$zodSchema: z.ZodType<
  ListInboxConversationsLastMessage
> = z.object({
  deliveredAt: z.int(),
  senderProfileUrn: z.string(),
  text: z.string(),
});

export type ListInboxConversationsConversation = {
  conversationUrn: string;
  conversationUrl: string;
  lastActivityAt: number;
  createdAt: number;
  read: boolean;
  unreadCount: number;
  groupChat: boolean;
  participants: Array<ListInboxConversationsParticipant>;
  lastMessage: ListInboxConversationsLastMessage | null;
};

export const ListInboxConversationsConversation$zodSchema: z.ZodType<
  ListInboxConversationsConversation
> = z.object({
  conversationUrl: z.string(),
  conversationUrn: z.string(),
  createdAt: z.int(),
  groupChat: z.boolean(),
  lastActivityAt: z.int(),
  lastMessage: z.lazy(() => ListInboxConversationsLastMessage$zodSchema)
    .nullable(),
  participants: z.array(
    z.lazy(() => ListInboxConversationsParticipant$zodSchema),
  ),
  read: z.boolean(),
  unreadCount: z.int(),
});

/**
 * Inbox conversations
 */
export type ListInboxConversationsResponseBody = {
  success: boolean;
  conversations: Array<ListInboxConversationsConversation>;
  nextCursor: string | null;
  creditsUsed: number;
  retryAfter: number;
};

export const ListInboxConversationsResponseBody$zodSchema: z.ZodType<
  ListInboxConversationsResponseBody
> = z.object({
  conversations: z.array(
    z.lazy(() => ListInboxConversationsConversation$zodSchema),
  ),
  creditsUsed: z.int(),
  nextCursor: z.string().nullable(),
  retryAfter: z.int(),
  success: z.boolean(),
}).describe("Inbox conversations");

export type ListInboxConversationsResponse =
  | ListInboxConversationsResponseBody
  | ListInboxConversationsBadRequestResponseBody
  | ListInboxConversationsUnauthorizedResponseBody
  | ListInboxConversationsForbiddenResponseBody
  | ListInboxConversationsNotFoundResponseBody
  | ListInboxConversationsConflictResponseBody
  | ListInboxConversationsGoneResponseBody
  | ListInboxConversationsUnprocessableEntityResponseBody
  | ListInboxConversationsTooManyRequestsResponseBody
  | ListInboxConversationsInternalServerErrorResponseBody;

export const ListInboxConversationsResponse$zodSchema: z.ZodType<
  ListInboxConversationsResponse
> = z.union([
  z.lazy(() => ListInboxConversationsResponseBody$zodSchema),
  z.lazy(() => ListInboxConversationsBadRequestResponseBody$zodSchema),
  z.lazy(() => ListInboxConversationsUnauthorizedResponseBody$zodSchema),
  z.lazy(() => ListInboxConversationsForbiddenResponseBody$zodSchema),
  z.lazy(() => ListInboxConversationsNotFoundResponseBody$zodSchema),
  z.lazy(() => ListInboxConversationsConflictResponseBody$zodSchema),
  z.lazy(() => ListInboxConversationsGoneResponseBody$zodSchema),
  z.lazy(() => ListInboxConversationsUnprocessableEntityResponseBody$zodSchema),
  z.lazy(() => ListInboxConversationsTooManyRequestsResponseBody$zodSchema),
  z.lazy(() => ListInboxConversationsInternalServerErrorResponseBody$zodSchema),
]);
