/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Publish mode: 'instant' publishes immediately, 'scheduled' schedules for later
 */
export const Mode = {
  Scheduled: "scheduled",
  Instant: "instant",
} as const;
/**
 * Publish mode: 'instant' publishes immediately, 'scheduled' schedules for later
 */
export type Mode = ClosedEnum<typeof Mode>;

export const Mode$zodSchema = z.enum([
  "scheduled",
  "instant",
]).describe(
  "Publish mode: 'instant' publishes immediately, 'scheduled' schedules for later",
);

/**
 * Post visibility
 */
export const Visibility = {
  Anyone: "ANYONE",
  Connections: "CONNECTIONS",
} as const;
/**
 * Post visibility
 */
export type Visibility = ClosedEnum<typeof Visibility>;

export const Visibility$zodSchema = z.enum([
  "ANYONE",
  "CONNECTIONS",
]).describe("Post visibility");

export type Mention = { profileUrn: string; start: number; length: number };

export const Mention$zodSchema: z.ZodType<Mention> = z.object({
  length: z.int(),
  profileUrn: z.string(),
  start: z.int(),
});

export type PublishLinkedInPostRequest = {
  text: string;
  mode: Mode;
  scheduledAt?: number | undefined;
  imageUrl?: string | undefined;
  visibility?: Visibility | undefined;
  mentions?: Array<Mention> | undefined;
  campaignSlug?: string | undefined;
  actionSlug?: string | undefined;
};

export const PublishLinkedInPostRequest$zodSchema: z.ZodType<
  PublishLinkedInPostRequest
> = z.object({
  actionSlug: z.string().optional(),
  campaignSlug: z.string().optional(),
  imageUrl: z.string().optional(),
  mentions: z.array(z.lazy(() => Mention$zodSchema)).optional(),
  mode: Mode$zodSchema,
  scheduledAt: z.int().optional(),
  text: z.string(),
  visibility: Visibility$zodSchema.default("ANYONE"),
});

export type PublishLinkedInPostInternalServerErrorDetails =
  | string
  | Array<string>;

export const PublishLinkedInPostInternalServerErrorDetails$zodSchema: z.ZodType<
  PublishLinkedInPostInternalServerErrorDetails
> = z.union([
  z.string(),
  z.array(z.string()),
]);

export type PublishLinkedInPostInternalServerErrorError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const PublishLinkedInPostInternalServerErrorError$zodSchema: z.ZodType<
  PublishLinkedInPostInternalServerErrorError
> = z.object({
  code: z.string(),
  details: z.union([
    z.string(),
    z.array(z.string()),
  ]).optional(),
  docs: z.string().optional(),
  message: z.string(),
});

/**
 * The server encountered a situation it does not know how to handle.
 */
export type PublishLinkedInPostInternalServerErrorResponseBody = {
  success?: boolean | undefined;
  error: PublishLinkedInPostInternalServerErrorError;
};

export const PublishLinkedInPostInternalServerErrorResponseBody$zodSchema:
  z.ZodType<PublishLinkedInPostInternalServerErrorResponseBody> = z.object({
    error: z.lazy(() => PublishLinkedInPostInternalServerErrorError$zodSchema),
    success: z.boolean().default(false),
  }).describe(
    "The server encountered a situation it does not know how to handle.",
  );

export const PublishLinkedInPostCode = {
  RateLimitExceeded: "rate_limit_exceeded",
} as const;
export type PublishLinkedInPostCode = ClosedEnum<
  typeof PublishLinkedInPostCode
>;

export const PublishLinkedInPostCode$zodSchema = z.enum([
  "rate_limit_exceeded",
]);

/**
 * Current and max daily usage (null if no daily cap).
 */
export type PublishLinkedInPostDaily = { current: number; limit: number };

export const PublishLinkedInPostDaily$zodSchema: z.ZodType<
  PublishLinkedInPostDaily
> = z.object({
  current: z.int(),
  limit: z.int(),
}).describe("Current and max daily usage (null if no daily cap).");

/**
 * Current and max weekly usage (null if no weekly cap).
 */
export type PublishLinkedInPostWeekly = { current: number; limit: number };

export const PublishLinkedInPostWeekly$zodSchema: z.ZodType<
  PublishLinkedInPostWeekly
> = z.object({
  current: z.int(),
  limit: z.int(),
}).describe("Current and max weekly usage (null if no weekly cap).");

export type PublishLinkedInPostTooManyRequestsError = {
  code: PublishLinkedInPostCode;
  message: string;
  docs?: string | undefined;
  retryAfter: number;
  daily: PublishLinkedInPostDaily | null;
  weekly: PublishLinkedInPostWeekly | null;
};

export const PublishLinkedInPostTooManyRequestsError$zodSchema: z.ZodType<
  PublishLinkedInPostTooManyRequestsError
> = z.object({
  code: PublishLinkedInPostCode$zodSchema,
  daily: z.lazy(() => PublishLinkedInPostDaily$zodSchema).nullable(),
  docs: z.string().optional(),
  message: z.string(),
  retryAfter: z.int(),
  weekly: z.lazy(() => PublishLinkedInPostWeekly$zodSchema).nullable(),
});

/**
 * Rate limit exceeded. Read error.retryAfter for the wait time in seconds.
 */
export type PublishLinkedInPostTooManyRequestsResponseBody = {
  success?: boolean | undefined;
  error: PublishLinkedInPostTooManyRequestsError;
};

export const PublishLinkedInPostTooManyRequestsResponseBody$zodSchema:
  z.ZodType<PublishLinkedInPostTooManyRequestsResponseBody> = z.object({
    error: z.lazy(() => PublishLinkedInPostTooManyRequestsError$zodSchema),
    success: z.boolean().default(false),
  }).describe(
    "Rate limit exceeded. Read error.retryAfter for the wait time in seconds.",
  );

export type PublishLinkedInPostUnprocessableEntityDetails =
  | string
  | Array<string>;

export const PublishLinkedInPostUnprocessableEntityDetails$zodSchema: z.ZodType<
  PublishLinkedInPostUnprocessableEntityDetails
> = z.union([
  z.string(),
  z.array(z.string()),
]);

export type PublishLinkedInPostUnprocessableEntityError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const PublishLinkedInPostUnprocessableEntityError$zodSchema: z.ZodType<
  PublishLinkedInPostUnprocessableEntityError
> = z.object({
  code: z.string(),
  details: z.union([
    z.string(),
    z.array(z.string()),
  ]).optional(),
  docs: z.string().optional(),
  message: z.string(),
});

/**
 * The request was well-formed but was unable to be followed due to semantic errors.
 */
export type PublishLinkedInPostUnprocessableEntityResponseBody = {
  success?: boolean | undefined;
  error: PublishLinkedInPostUnprocessableEntityError;
};

export const PublishLinkedInPostUnprocessableEntityResponseBody$zodSchema:
  z.ZodType<PublishLinkedInPostUnprocessableEntityResponseBody> = z.object({
    error: z.lazy(() => PublishLinkedInPostUnprocessableEntityError$zodSchema),
    success: z.boolean().default(false),
  }).describe(
    "The request was well-formed but was unable to be followed due to semantic errors.",
  );

export type PublishLinkedInPostGoneDetails = string | Array<string>;

export const PublishLinkedInPostGoneDetails$zodSchema: z.ZodType<
  PublishLinkedInPostGoneDetails
> = z.union([
  z.string(),
  z.array(z.string()),
]);

export type PublishLinkedInPostGoneError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const PublishLinkedInPostGoneError$zodSchema: z.ZodType<
  PublishLinkedInPostGoneError
> = z.object({
  code: z.string(),
  details: z.union([
    z.string(),
    z.array(z.string()),
  ]).optional(),
  docs: z.string().optional(),
  message: z.string(),
});

/**
 * The requested content has been permanently deleted from the server.
 */
export type PublishLinkedInPostGoneResponseBody = {
  success?: boolean | undefined;
  error: PublishLinkedInPostGoneError;
};

export const PublishLinkedInPostGoneResponseBody$zodSchema: z.ZodType<
  PublishLinkedInPostGoneResponseBody
> = z.object({
  error: z.lazy(() => PublishLinkedInPostGoneError$zodSchema),
  success: z.boolean().default(false),
}).describe(
  "The requested content has been permanently deleted from the server.",
);

export type PublishLinkedInPostConflictDetails = string | Array<string>;

export const PublishLinkedInPostConflictDetails$zodSchema: z.ZodType<
  PublishLinkedInPostConflictDetails
> = z.union([
  z.string(),
  z.array(z.string()),
]);

export type PublishLinkedInPostConflictError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const PublishLinkedInPostConflictError$zodSchema: z.ZodType<
  PublishLinkedInPostConflictError
> = z.object({
  code: z.string(),
  details: z.union([
    z.string(),
    z.array(z.string()),
  ]).optional(),
  docs: z.string().optional(),
  message: z.string(),
});

/**
 * The request conflicts with the current state of the server.
 */
export type PublishLinkedInPostConflictResponseBody = {
  success?: boolean | undefined;
  error: PublishLinkedInPostConflictError;
};

export const PublishLinkedInPostConflictResponseBody$zodSchema: z.ZodType<
  PublishLinkedInPostConflictResponseBody
> = z.object({
  error: z.lazy(() => PublishLinkedInPostConflictError$zodSchema),
  success: z.boolean().default(false),
}).describe("The request conflicts with the current state of the server.");

export type PublishLinkedInPostNotFoundDetails = string | Array<string>;

export const PublishLinkedInPostNotFoundDetails$zodSchema: z.ZodType<
  PublishLinkedInPostNotFoundDetails
> = z.union([
  z.string(),
  z.array(z.string()),
]);

export type PublishLinkedInPostNotFoundError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const PublishLinkedInPostNotFoundError$zodSchema: z.ZodType<
  PublishLinkedInPostNotFoundError
> = z.object({
  code: z.string(),
  details: z.union([
    z.string(),
    z.array(z.string()),
  ]).optional(),
  docs: z.string().optional(),
  message: z.string(),
});

/**
 * The server cannot find the requested resource.
 */
export type PublishLinkedInPostNotFoundResponseBody = {
  success?: boolean | undefined;
  error: PublishLinkedInPostNotFoundError;
};

export const PublishLinkedInPostNotFoundResponseBody$zodSchema: z.ZodType<
  PublishLinkedInPostNotFoundResponseBody
> = z.object({
  error: z.lazy(() => PublishLinkedInPostNotFoundError$zodSchema),
  success: z.boolean().default(false),
}).describe("The server cannot find the requested resource.");

export type PublishLinkedInPostForbiddenDetails = string | Array<string>;

export const PublishLinkedInPostForbiddenDetails$zodSchema: z.ZodType<
  PublishLinkedInPostForbiddenDetails
> = z.union([
  z.string(),
  z.array(z.string()),
]);

export type PublishLinkedInPostForbiddenError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const PublishLinkedInPostForbiddenError$zodSchema: z.ZodType<
  PublishLinkedInPostForbiddenError
> = z.object({
  code: z.string(),
  details: z.union([
    z.string(),
    z.array(z.string()),
  ]).optional(),
  docs: z.string().optional(),
  message: z.string(),
});

/**
 * The client does not have access rights to the content.
 */
export type PublishLinkedInPostForbiddenResponseBody = {
  success?: boolean | undefined;
  error: PublishLinkedInPostForbiddenError;
};

export const PublishLinkedInPostForbiddenResponseBody$zodSchema: z.ZodType<
  PublishLinkedInPostForbiddenResponseBody
> = z.object({
  error: z.lazy(() => PublishLinkedInPostForbiddenError$zodSchema),
  success: z.boolean().default(false),
}).describe("The client does not have access rights to the content.");

export type PublishLinkedInPostUnauthorizedDetails = string | Array<string>;

export const PublishLinkedInPostUnauthorizedDetails$zodSchema: z.ZodType<
  PublishLinkedInPostUnauthorizedDetails
> = z.union([
  z.string(),
  z.array(z.string()),
]);

export type PublishLinkedInPostUnauthorizedError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const PublishLinkedInPostUnauthorizedError$zodSchema: z.ZodType<
  PublishLinkedInPostUnauthorizedError
> = z.object({
  code: z.string(),
  details: z.union([
    z.string(),
    z.array(z.string()),
  ]).optional(),
  docs: z.string().optional(),
  message: z.string(),
});

/**
 * Although HTTP specifies "unauthorized", this response means "unauthenticated". Authenticate to continue.
 */
export type PublishLinkedInPostUnauthorizedResponseBody = {
  success?: boolean | undefined;
  error: PublishLinkedInPostUnauthorizedError;
};

export const PublishLinkedInPostUnauthorizedResponseBody$zodSchema: z.ZodType<
  PublishLinkedInPostUnauthorizedResponseBody
> = z.object({
  error: z.lazy(() => PublishLinkedInPostUnauthorizedError$zodSchema),
  success: z.boolean().default(false),
}).describe(
  "Although HTTP specifies \"unauthorized\", this response means \"unauthenticated\". Authenticate to continue.",
);

export type PublishLinkedInPostBadRequestDetails = string | Array<string>;

export const PublishLinkedInPostBadRequestDetails$zodSchema: z.ZodType<
  PublishLinkedInPostBadRequestDetails
> = z.union([
  z.string(),
  z.array(z.string()),
]);

export type PublishLinkedInPostBadRequestError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const PublishLinkedInPostBadRequestError$zodSchema: z.ZodType<
  PublishLinkedInPostBadRequestError
> = z.object({
  code: z.string(),
  details: z.union([
    z.string(),
    z.array(z.string()),
  ]).optional(),
  docs: z.string().optional(),
  message: z.string(),
});

/**
 * The server cannot or will not process the request due to something that is perceived to be a client error.
 */
export type PublishLinkedInPostBadRequestResponseBody = {
  success?: boolean | undefined;
  error: PublishLinkedInPostBadRequestError;
};

export const PublishLinkedInPostBadRequestResponseBody$zodSchema: z.ZodType<
  PublishLinkedInPostBadRequestResponseBody
> = z.object({
  error: z.lazy(() => PublishLinkedInPostBadRequestError$zodSchema),
  success: z.boolean().default(false),
}).describe(
  "The server cannot or will not process the request due to something that is perceived to be a client error.",
);

/**
 * Post published or scheduled successfully
 */
export type PublishLinkedInPostResponseBody = {
  success: boolean;
  shareUrn: string;
  activityUrn: string | null;
  duplicate?: boolean | undefined;
  creditsUsed: number;
  retryAfter: number;
};

export const PublishLinkedInPostResponseBody$zodSchema: z.ZodType<
  PublishLinkedInPostResponseBody
> = z.object({
  activityUrn: z.string().nullable(),
  creditsUsed: z.int(),
  duplicate: z.boolean().optional(),
  retryAfter: z.int(),
  shareUrn: z.string(),
  success: z.boolean(),
}).describe("Post published or scheduled successfully");

export type PublishLinkedInPostResponse =
  | PublishLinkedInPostResponseBody
  | PublishLinkedInPostBadRequestResponseBody
  | PublishLinkedInPostUnauthorizedResponseBody
  | PublishLinkedInPostForbiddenResponseBody
  | PublishLinkedInPostNotFoundResponseBody
  | PublishLinkedInPostConflictResponseBody
  | PublishLinkedInPostGoneResponseBody
  | PublishLinkedInPostUnprocessableEntityResponseBody
  | PublishLinkedInPostTooManyRequestsResponseBody
  | PublishLinkedInPostInternalServerErrorResponseBody;

export const PublishLinkedInPostResponse$zodSchema: z.ZodType<
  PublishLinkedInPostResponse
> = z.union([
  z.lazy(() => PublishLinkedInPostResponseBody$zodSchema),
  z.lazy(() => PublishLinkedInPostBadRequestResponseBody$zodSchema),
  z.lazy(() => PublishLinkedInPostUnauthorizedResponseBody$zodSchema),
  z.lazy(() => PublishLinkedInPostForbiddenResponseBody$zodSchema),
  z.lazy(() => PublishLinkedInPostNotFoundResponseBody$zodSchema),
  z.lazy(() => PublishLinkedInPostConflictResponseBody$zodSchema),
  z.lazy(() => PublishLinkedInPostGoneResponseBody$zodSchema),
  z.lazy(() => PublishLinkedInPostUnprocessableEntityResponseBody$zodSchema),
  z.lazy(() => PublishLinkedInPostTooManyRequestsResponseBody$zodSchema),
  z.lazy(() => PublishLinkedInPostInternalServerErrorResponseBody$zodSchema),
]);
