/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { campaignsFilter } from "../funcs/campaigns-filter.js";
import { campaignsGetStats } from "../funcs/campaigns-get-stats.js";
import { campaignsGetStatus } from "../funcs/campaigns-get-status.js";
import { campaignsSync } from "../funcs/campaigns-sync.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Campaigns extends ClientSDK {
  /**
   * Check if campaign actions are completed
   *
   * @remarks
   * Check if all provided actionSlugs are completed for a given campaignSlug. Used by n8n workflows to determine if a flow should be skipped.
   *
   * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  async filter(
    request: operations.FilterCampaignRequest,
    options?: RequestOptions,
  ): Promise<operations.FilterCampaignResponse> {
    return unwrapAsync(campaignsFilter(
      this,
      request,
      options,
    ));
  }

  /**
   * Query per-profile action status within a campaign
   *
   * @remarks
   * Returns which actions (message, reply, like, visit, connect) have been completed for each profile within a campaign. Replaces the slug-based filter endpoint — query by profile URLs instead of building slug lists. 0 credits, no rate limit.
   */
  async getStatus(
    request: operations.GetCampaignStatusRequest,
    options?: RequestOptions,
  ): Promise<operations.GetCampaignStatusResponse> {
    return unwrapAsync(campaignsGetStatus(
      this,
      request,
      options,
    ));
  }

  /**
   * Mark actions as completed without performing them
   *
   * @remarks
   * Manually mark actions as completed for profiles within a campaign. Use when actions were performed outside the API (e.g. manual DMs) and need to be synced. 0 credits, no rate limit.
   */
  async sync(
    request: operations.SyncCampaignActionsRequest,
    options?: RequestOptions,
  ): Promise<operations.SyncCampaignActionsResponse> {
    return unwrapAsync(campaignsSync(
      this,
      request,
      options,
    ));
  }

  /**
   * Get aggregate campaign statistics
   *
   * @remarks
   * Returns per-action counts, unique profile count, and total credits used for a campaign. 0 credits, no rate limit.
   */
  async getStats(
    request: operations.GetCampaignStatsRequest,
    options?: RequestOptions,
  ): Promise<operations.GetCampaignStatsResponse> {
    return unwrapAsync(campaignsGetStats(
      this,
      request,
      options,
    ));
  }
}
