/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { contextDelete } from "../funcs/context-delete.js";
import { contextListEntries } from "../funcs/context-list-entries.js";
import { contextSet } from "../funcs/context-set.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Context extends ClientSDK {
  /**
   * List context entries
   *
   * @remarks
   * List saved context entries (user profile, ICP, Messaging Playbook). Always filter by type and scope; unfiltered reads return hundreds of rows. Entries come back as a 200-char preview to protect the context budget; pass fullContent=true to read one entry in full, which is how to read a specific saved context such as an ICP or playbook. context_get is the expensive full session snapshot, session-init only: never call it mid-conversation to read one entry.
   */
  async listEntries(
    request?: operations.ContextListRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ContextListResponse> {
    return unwrapAsync(contextListEntries(
      this,
      request,
      options,
    ));
  }

  /**
   * Create or update a context entry
   *
   * @remarks
   * Save context (ICP, Messaging Playbook, user profile) the moment the user says save or remember, identity facts as type "user-profile". A playbook write AMENDS the saved document: send the fields that change, a field left out is kept, a field sent as null is removed. Every other type replaces the whole entry, so merge the new information into what is already saved. Renaming is not a rewrite: send the type and the saved scope with the new label and no content.
   */
  async set(
    request: operations.ContextSetRequest,
    options?: RequestOptions,
  ): Promise<operations.ContextSetResponse> {
    return unwrapAsync(contextSet(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a context entry
   *
   * @remarks
   * Delete a context entry by type and scope..
   */
  async delete(
    request: operations.ContextDeleteRequest,
    options?: RequestOptions,
  ): Promise<operations.ContextDeleteResponse> {
    return unwrapAsync(contextDelete(
      this,
      request,
      options,
    ));
  }
}
