/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { linkedinChatGetMessages } from "../funcs/linkedin-chat-get-messages.js";
import { linkedinChatGetUnreadCount } from "../funcs/linkedin-chat-get-unread-count.js";
import { linkedinChatListArchived } from "../funcs/linkedin-chat-list-archived.js";
import { linkedinChatListInboxConversations } from "../funcs/linkedin-chat-list-inbox-conversations.js";
import { linkedinChatMarkAllRead } from "../funcs/linkedin-chat-mark-all-read.js";
import { linkedinChatReact } from "../funcs/linkedin-chat-react.js";
import { linkedinChatSendTypingIndicator } from "../funcs/linkedin-chat-send-typing-indicator.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class LinkedinChat1 extends ClientSDK {
  /**
   * List LinkedIn inbox conversations
   *
   * @remarks
   * List inbox conversations for the authenticated user. Returns conversations with participants, last message, and read status. Paginate via nextCursor.
   */
  async listInboxConversations(
    request: operations.ListInboxConversationsRequest,
    options?: RequestOptions,
  ): Promise<operations.ListInboxConversationsResponse> {
    return unwrapAsync(linkedinChatListInboxConversations(
      this,
      request,
      options,
    ));
  }

  /**
   * Read messages from a conversation
   *
   * @remarks
   * Fetch messages from a specific LinkedIn conversation. 0 credits.
   *
   * Pass the full `conversationUrn` as returned by `/chats/linkedin` or `/chats/linkedin/search`. No parsing required — the server handles extraction internally.
   *
   * Example: `{ "conversationUrn": "urn:li:msg_conversation:(urn:li:fsd_profile:ACoAAXXX,2-YWUx...)" }`
   */
  async getMessages(
    request: operations.GetConversationMessagesRequest,
    options?: RequestOptions,
  ): Promise<operations.GetConversationMessagesResponse> {
    return unwrapAsync(linkedinChatGetMessages(
      this,
      request,
      options,
    ));
  }

  /**
   * Mark all conversations as read
   *
   * @remarks
   * Mark all LinkedIn inbox conversations as read. 0 credits.
   */
  async markAllRead(
    request?: operations.MarkAllConversationsReadRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.MarkAllConversationsReadResponse> {
    return unwrapAsync(linkedinChatMarkAllRead(
      this,
      request,
      options,
    ));
  }

  /**
   * List archived conversations
   *
   * @remarks
   * List archived LinkedIn conversations. 0 credits.
   */
  async listArchived(
    request?: operations.ListArchivedConversationsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListArchivedConversationsResponse> {
    return unwrapAsync(linkedinChatListArchived(
      this,
      request,
      options,
    ));
  }

  /**
   * React to a message with emoji
   *
   * @remarks
   * Add an emoji reaction to a LinkedIn message. 0 credits.
   */
  async react(
    request: operations.ReactToMessageRequest,
    options?: RequestOptions,
  ): Promise<operations.ReactToMessageResponse> {
    return unwrapAsync(linkedinChatReact(
      this,
      request,
      options,
    ));
  }

  /**
   * Send typing indicator
   *
   * @remarks
   * Send a typing indicator to a LinkedIn conversation, simulating natural typing behavior. 0 credits.
   */
  async sendTypingIndicator(
    request: operations.SendTypingIndicatorRequest,
    options?: RequestOptions,
  ): Promise<operations.SendTypingIndicatorResponse> {
    return unwrapAsync(linkedinChatSendTypingIndicator(
      this,
      request,
      options,
    ));
  }

  /**
   * Get unread message count
   *
   * @remarks
   * Get the number of unread LinkedIn messages/conversations. 0 credits.
   */
  async getUnreadCount(
    request?: operations.GetUnreadCountRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetUnreadCountResponse> {
    return unwrapAsync(linkedinChatGetUnreadCount(
      this,
      request,
      options,
    ));
  }
}
