workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    BeReach API:
        inputs:
            - location: http://api.berea.ch
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/bereach/bereach/be-reach-api
targets:
    bereach:
        target: typescript
        source: BeReach API
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/bereach/bereach/be-reach-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
