workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    BeReach API:
        inputs:
            - location: https://api.berea.ch
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/bereach-h29/bereach/be-reach-api
targets:
    bereach:
        target: typescript
        source: BeReach API
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/bereach-h29/bereach/be-reach-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
