/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  ContextSetEntry,
  ContextSetEntry$inboundSchema,
  ContextSetMeta,
  ContextSetMeta$inboundSchema,
} from "./context-set-meta.js";

/**
 * Context saved
 */
export type ContextSetResponse = {
  success: true;
  entry: ContextSetEntry;
  /**
   * Credits consumed by this call. 0 for free endpoints, cached results, duplicates, and for every query that does not touch LinkedIn.
   */
  creditsUsed: number;
  /**
   * Seconds to wait before another call of the same type. 0 means no wait is needed.
   */
  retryAfter: number;
  /**
   * Credit balance carried on every response so a caller never has to ask for it separately. Absent when the caller has no connected account.
   */
  meta?: ContextSetMeta | undefined;
};

export type ContextDeleteRequest = {
  /**
   * Context type to delete
   */
  type: string;
  /**
   * Scope (defaults to "user")
   */
  scope?: string | undefined;
};

export type ContextDeleteCredits = {
  /**
   * Credits spent this period.
   */
  current: number;
  /**
   * Period allowance, or null when unlimited.
   */
  limit: number | null;
  /**
   * Allowance left, or null when unlimited.
   */
  remaining: number | null;
  /**
   * Share of the allowance spent, 0 to 100.
   */
  percentage: number;
  isUnlimited: boolean;
};

/**
 * Credit balance carried on every response so a caller never has to ask for it separately. Absent when the caller has no connected account.
 */
export type ContextDeleteMeta = {
  credits: ContextDeleteCredits;
};

/**
 * Context deleted
 */
export type ContextDeleteResponse = {
  success: true;
  /**
   * Credits consumed by this call. 0 for free endpoints, cached results, duplicates, and for every query that does not touch LinkedIn.
   */
  creditsUsed: number;
  /**
   * Seconds to wait before another call of the same type. 0 means no wait is needed.
   */
  retryAfter: number;
  /**
   * Credit balance carried on every response so a caller never has to ask for it separately. Absent when the caller has no connected account.
   */
  meta?: ContextDeleteMeta | undefined;
};

export type EventsFeedRequest = {
  /**
   * ISO timestamp or epoch ms (default: 2 hours ago)
   */
  since?: string | undefined;
  limit?: number | undefined;
};

export const EventsFeedType = {
  ReplyReceived: "reply:received",
  ConnectionAccepted: "connection:accepted",
  CampaignRateLimited: "campaign:rate_limited",
  CampaignLinkedinExpired: "campaign:linkedin_expired",
  CredentialLlmError: "credential:llm_error",
  CredentialLinkedinLongBroken: "credential:linkedin_long_broken",
} as const;
export type EventsFeedType = OpenEnum<typeof EventsFeedType>;

export type Event = {
  id: string;
  type: EventsFeedType;
  campaignId?: string | undefined;
  campaignName?: string | undefined;
  /**
   * Human-readable one-line summary
   */
  summary: string;
  metadata: { [k: string]: any };
  /**
   * Unix epoch ms
   */
  timestamp: number;
};

/**
 * Events
 */
export type EventsFeedResponse = {
  events: Array<Event>;
  /**
   * Timestamp of most recent event (pass as 'since' for next poll)
   */
  cursor?: number | undefined;
};

export type Context = {
  type: string;
  label: string | null;
  content: string;
  scope: string;
};

export const ActiveAccountStatus = {
  Connected: "connected",
  Expired: "expired",
} as const;
export type ActiveAccountStatus = OpenEnum<typeof ActiveAccountStatus>;

export type ActiveAccount = {
  id: string;
  name: string | null;
  plan: string;
  headline: string | null;
  status: ActiveAccountStatus;
  isUnlimited: boolean;
  /**
   * The workspace's shared credit limit, the same on every account row.
   */
  creditsLimit: number;
  /**
   * Credits the workspace has used this cycle, the same on every account row.
   */
  creditsCount: number;
  simulateWrites: boolean;
  isCurrent: boolean;
};

export const ContextGetAccountStatus = {
  Connected: "connected",
  Expired: "expired",
} as const;
export type ContextGetAccountStatus = OpenEnum<typeof ContextGetAccountStatus>;

export type ContextGetAccount = {
  id: string;
  name: string | null;
  plan: string;
  headline: string | null;
  status: ContextGetAccountStatus;
  isUnlimited: boolean;
  /**
   * The workspace's shared credit limit, the same on every account row.
   */
  creditsLimit: number;
  /**
   * Credits the workspace has used this cycle, the same on every account row.
   */
  creditsCount: number;
  simulateWrites: boolean;
  isCurrent: boolean;
};

export type ContextGetStageCounts = {
  contact: number;
  lead: number;
  qualified: number;
  rejected: number;
  total: number;
};

export type ActiveCampaign = {
  id: string;
  name: string;
  stageCounts: ContextGetStageCounts;
};

export const ContextGetType = {
  ReplyReceived: "reply:received",
  ConnectionAccepted: "connection:accepted",
  CampaignRateLimited: "campaign:rate_limited",
  CampaignLinkedinExpired: "campaign:linkedin_expired",
  CredentialLlmError: "credential:llm_error",
  CredentialLinkedinLongBroken: "credential:linkedin_long_broken",
} as const;
export type ContextGetType = OpenEnum<typeof ContextGetType>;

export type RecentEvent = {
  id: string;
  type: ContextGetType;
  campaignId?: string | undefined;
  campaignName?: string | undefined;
  /**
   * Human-readable one-line summary
   */
  summary: string;
  metadata: { [k: string]: any };
  /**
   * Unix epoch ms
   */
  timestamp: number;
};

/**
 * Session snapshot
 */
export type ContextGetResponse = {
  /**
   * Credit balance and usage
   */
  credits?: any | null | undefined;
  /**
   * List memberships counted by stage, with a total that includes removed. A person on two lists counts twice.
   */
  pipeline: { [k: string]: number };
  contexts: Array<Context>;
  pendingDrafts: number;
  failedDrafts: number;
  pendingSentInvitations: number;
  activeAccount: ActiveAccount | null;
  accounts: Array<ContextGetAccount>;
  activeCampaigns: Array<ActiveCampaign>;
  recentEvents: Array<RecentEvent>;
  /**
   * Set when the LLM circuit breaker has tripped for this credential.
   */
  llmStatus?: string | null | undefined;
  /**
   * Epoch ms the breaker first tripped, so a caller can say how long it has been paused.
   */
  llmFirstTrippedAt?: number | null | undefined;
};

export type GetDmPollingSettingsSettings = {
  dmWebhookUrl: string | null;
  connectionLastPolledAt: string | null;
};

export type GetDmPollingSettingsCredits = {
  /**
   * Credits spent this period.
   */
  current: number;
  /**
   * Period allowance, or null when unlimited.
   */
  limit: number | null;
  /**
   * Allowance left, or null when unlimited.
   */
  remaining: number | null;
  /**
   * Share of the allowance spent, 0 to 100.
   */
  percentage: number;
  isUnlimited: boolean;
};

/**
 * Credit balance carried on every response so a caller never has to ask for it separately. Absent when the caller has no connected account.
 */
export type GetDmPollingSettingsMeta = {
  credits: GetDmPollingSettingsCredits;
};

/**
 * Polling settings
 */
export type GetDmPollingSettingsResponse = {
  success: true;
  settings: GetDmPollingSettingsSettings;
  /**
   * Credits consumed by this call. 0 for free endpoints, cached results, duplicates, and for every query that does not touch LinkedIn.
   */
  creditsUsed: number;
  /**
   * Seconds to wait before another call of the same type. 0 means no wait is needed.
   */
  retryAfter: number;
  /**
   * Credit balance carried on every response so a caller never has to ask for it separately. Absent when the caller has no connected account.
   */
  meta?: GetDmPollingSettingsMeta | undefined;
};

export type PatchDmPollingSettingsRequest = {
  /**
   * Webhook URL for connection_accepted + conversation_updated events
   */
  dmWebhookUrl?: string | null | undefined;
};

export type PatchDmPollingSettingsSettings = {
  dmWebhookUrl: string | null;
  connectionLastPolledAt: string | null;
};

export type PatchDmPollingSettingsCredits = {
  /**
   * Credits spent this period.
   */
  current: number;
  /**
   * Period allowance, or null when unlimited.
   */
  limit: number | null;
  /**
   * Allowance left, or null when unlimited.
   */
  remaining: number | null;
  /**
   * Share of the allowance spent, 0 to 100.
   */
  percentage: number;
  isUnlimited: boolean;
};

/**
 * Credit balance carried on every response so a caller never has to ask for it separately. Absent when the caller has no connected account.
 */
export type PatchDmPollingSettingsMeta = {
  credits: PatchDmPollingSettingsCredits;
};

/**
 * Settings updated
 */
export type PatchDmPollingSettingsResponse = {
  success: true;
  settings: PatchDmPollingSettingsSettings;
  /**
   * Credits consumed by this call. 0 for free endpoints, cached results, duplicates, and for every query that does not touch LinkedIn.
   */
  creditsUsed: number;
  /**
   * Seconds to wait before another call of the same type. 0 means no wait is needed.
   */
  retryAfter: number;
  /**
   * Credit balance carried on every response so a caller never has to ask for it separately. Absent when the caller has no connected account.
   */
  meta?: PatchDmPollingSettingsMeta | undefined;
};

export type DeleteWorkspaceAccountRequest = {
  /**
   * LinkedIn credentials ID
   */
  id: string;
};

export type DeleteWorkspaceAccountCredits = {
  /**
   * Credits spent this period.
   */
  current: number;
  /**
   * Period allowance, or null when unlimited.
   */
  limit: number | null;
  /**
   * Allowance left, or null when unlimited.
   */
  remaining: number | null;
  /**
   * Share of the allowance spent, 0 to 100.
   */
  percentage: number;
  isUnlimited: boolean;
};

/**
 * Credit balance carried on every response so a caller never has to ask for it separately. Absent when the caller has no connected account.
 */
export type DeleteWorkspaceAccountMeta = {
  credits: DeleteWorkspaceAccountCredits;
};

/**
 * Account removed
 */
export type DeleteWorkspaceAccountResponse = {
  success: true;
  message: string;
  /**
   * Credits consumed by this call. 0 for free endpoints, cached results, duplicates, and for every query that does not touch LinkedIn.
   */
  creditsUsed: number;
  /**
   * Seconds to wait before another call of the same type. 0 means no wait is needed.
   */
  retryAfter: number;
  /**
   * Credit balance carried on every response so a caller never has to ask for it separately. Absent when the caller has no connected account.
   */
  meta?: DeleteWorkspaceAccountMeta | undefined;
};

export const UpgradeWorkspaceAccountAction = {
  Upgrade: "upgrade",
  Downgrade: "downgrade",
} as const;
export type UpgradeWorkspaceAccountAction = ClosedEnum<
  typeof UpgradeWorkspaceAccountAction
>;

export type UpgradeWorkspaceAccountRequest = {
  /**
   * LinkedIn credentials ID
   */
  credentialsId: string;
  action: UpgradeWorkspaceAccountAction;
};

export type UpgradeWorkspaceAccountCredits = {
  /**
   * Credits spent this period.
   */
  current: number;
  /**
   * Period allowance, or null when unlimited.
   */
  limit: number | null;
  /**
   * Allowance left, or null when unlimited.
   */
  remaining: number | null;
  /**
   * Share of the allowance spent, 0 to 100.
   */
  percentage: number;
  isUnlimited: boolean;
};

/**
 * Credit balance carried on every response so a caller never has to ask for it separately. Absent when the caller has no connected account.
 */
export type UpgradeWorkspaceAccountMeta = {
  credits: UpgradeWorkspaceAccountCredits;
};

/**
 * Plan changed
 */
export type UpgradeWorkspaceAccountResponse = {
  success: true;
  message: string;
  seatsUsed: number;
  seatsIncluded: number;
  /**
   * Credits consumed by this call. 0 for free endpoints, cached results, duplicates, and for every query that does not touch LinkedIn.
   */
  creditsUsed: number;
  /**
   * Seconds to wait before another call of the same type. 0 means no wait is needed.
   */
  retryAfter: number;
  /**
   * Credit balance carried on every response so a caller never has to ask for it separately. Absent when the caller has no connected account.
   */
  meta?: UpgradeWorkspaceAccountMeta | undefined;
};

/**
 * "create" to make a new invite, "list" to get existing
 */
export const CreateWorkspaceInviteAction = {
  Create: "create",
  List: "list",
} as const;
/**
 * "create" to make a new invite, "list" to get existing
 */
export type CreateWorkspaceInviteAction = ClosedEnum<
  typeof CreateWorkspaceInviteAction
>;

export type CreateWorkspaceInviteRequest = {
  /**
   * "create" to make a new invite, "list" to get existing
   */
  action: CreateWorkspaceInviteAction;
  /**
   * Invitee email (sends invite email)
   */
  email?: string | undefined;
  /**
   * Invitee name
   */
  name?: string | undefined;
  /**
   * Max times code can be used
   */
  maxUses?: number | undefined;
};

export type CreateWorkspaceInviteInvite2 = {
  id: string;
  email: string | null;
  name: string | null;
  code: string;
  status?: string | undefined;
  maxUses: number;
  useCount: number;
  expiresAt: string | null;
  createdAt: string;
};

export type Workspace = {
  tier: string;
  proSeatsIncluded: number;
  proSeatsUsed: number;
};

export type CreateWorkspaceInviteCredits2 = {
  /**
   * Credits spent this period.
   */
  current: number;
  /**
   * Period allowance, or null when unlimited.
   */
  limit: number | null;
  /**
   * Allowance left, or null when unlimited.
   */
  remaining: number | null;
  /**
   * Share of the allowance spent, 0 to 100.
   */
  percentage: number;
  isUnlimited: boolean;
};

/**
 * Credit balance carried on every response so a caller never has to ask for it separately. Absent when the caller has no connected account.
 */
export type CreateWorkspaceInviteMeta2 = {
  credits: CreateWorkspaceInviteCredits2;
};

export type CreateWorkspaceInviteResponseBody2 = {
  success: true;
  invites: Array<CreateWorkspaceInviteInvite2>;
  workspace: Workspace;
  /**
   * Credits consumed by this call. 0 for free endpoints, cached results, duplicates, and for every query that does not touch LinkedIn.
   */
  creditsUsed: number;
  /**
   * Seconds to wait before another call of the same type. 0 means no wait is needed.
   */
  retryAfter: number;
  /**
   * Credit balance carried on every response so a caller never has to ask for it separately. Absent when the caller has no connected account.
   */
  meta?: CreateWorkspaceInviteMeta2 | undefined;
};

export type CreateWorkspaceInviteInvite1 = {
  id: string;
  email: string | null;
  name: string | null;
  code: string;
  status?: string | undefined;
  maxUses: number;
  useCount: number;
  expiresAt: string | null;
  createdAt: string;
};

export type CreateWorkspaceInviteCredits1 = {
  /**
   * Credits spent this period.
   */
  current: number;
  /**
   * Period allowance, or null when unlimited.
   */
  limit: number | null;
  /**
   * Allowance left, or null when unlimited.
   */
  remaining: number | null;
  /**
   * Share of the allowance spent, 0 to 100.
   */
  percentage: number;
  isUnlimited: boolean;
};

/**
 * Credit balance carried on every response so a caller never has to ask for it separately. Absent when the caller has no connected account.
 */
export type CreateWorkspaceInviteMeta1 = {
  credits: CreateWorkspaceInviteCredits1;
};

export type CreateWorkspaceInviteResponseBody1 = {
  success: true;
  invite: CreateWorkspaceInviteInvite1;
  /**
   * Credits consumed by this call. 0 for free endpoints, cached results, duplicates, and for every query that does not touch LinkedIn.
   */
  creditsUsed: number;
  /**
   * Seconds to wait before another call of the same type. 0 means no wait is needed.
   */
  retryAfter: number;
  /**
   * Credit balance carried on every response so a caller never has to ask for it separately. Absent when the caller has no connected account.
   */
  meta?: CreateWorkspaceInviteMeta1 | undefined;
};

/**
 * Invite created or listed
 */
export type CreateWorkspaceInviteResponse =
  | CreateWorkspaceInviteResponseBody2
  | CreateWorkspaceInviteResponseBody1;

export type DeleteWorkspaceInviteRequest = {
  /**
   * Invite ID to delete
   */
  inviteId: string;
};

export type DeleteWorkspaceInviteCredits = {
  /**
   * Credits spent this period.
   */
  current: number;
  /**
   * Period allowance, or null when unlimited.
   */
  limit: number | null;
  /**
   * Allowance left, or null when unlimited.
   */
  remaining: number | null;
  /**
   * Share of the allowance spent, 0 to 100.
   */
  percentage: number;
  isUnlimited: boolean;
};

/**
 * Credit balance carried on every response so a caller never has to ask for it separately. Absent when the caller has no connected account.
 */
export type DeleteWorkspaceInviteMeta = {
  credits: DeleteWorkspaceInviteCredits;
};

/**
 * Invite deleted
 */
export type DeleteWorkspaceInviteResponse = {
  success: true;
  /**
   * Credits consumed by this call. 0 for free endpoints, cached results, duplicates, and for every query that does not touch LinkedIn.
   */
  creditsUsed: number;
  /**
   * Seconds to wait before another call of the same type. 0 means no wait is needed.
   */
  retryAfter: number;
  /**
   * Credit balance carried on every response so a caller never has to ask for it separately. Absent when the caller has no connected account.
   */
  meta?: DeleteWorkspaceInviteMeta | undefined;
};

/** @internal */
export const ContextSetResponse$inboundSchema: z.ZodMiniType<
  ContextSetResponse,
  unknown
> = z.pipe(
  z.object({
    success: types.literal(true),
    entry: ContextSetEntry$inboundSchema,
    creditsUsed: types.number(),
    retryAfter: types.number(),
    _meta: types.optional(ContextSetMeta$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "_meta": "meta",
    });
  }),
);

export function contextSetResponseFromJSON(
  jsonString: string,
): SafeParseResult<ContextSetResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ContextSetResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ContextSetResponse' from JSON`,
  );
}

/** @internal */
export type ContextDeleteRequest$Outbound = {
  type: string;
  scope?: string | undefined;
};

/** @internal */
export const ContextDeleteRequest$outboundSchema: z.ZodMiniType<
  ContextDeleteRequest$Outbound,
  ContextDeleteRequest
> = z.object({
  type: z.string(),
  scope: z.optional(z.string()),
});

export function contextDeleteRequestToJSON(
  contextDeleteRequest: ContextDeleteRequest,
): string {
  return JSON.stringify(
    ContextDeleteRequest$outboundSchema.parse(contextDeleteRequest),
  );
}

/** @internal */
export const ContextDeleteCredits$inboundSchema: z.ZodMiniType<
  ContextDeleteCredits,
  unknown
> = z.object({
  current: types.number(),
  limit: types.nullable(types.number()),
  remaining: types.nullable(types.number()),
  percentage: types.number(),
  isUnlimited: types.boolean(),
});

export function contextDeleteCreditsFromJSON(
  jsonString: string,
): SafeParseResult<ContextDeleteCredits, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ContextDeleteCredits$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ContextDeleteCredits' from JSON`,
  );
}

/** @internal */
export const ContextDeleteMeta$inboundSchema: z.ZodMiniType<
  ContextDeleteMeta,
  unknown
> = z.object({
  credits: z.lazy(() => ContextDeleteCredits$inboundSchema),
});

export function contextDeleteMetaFromJSON(
  jsonString: string,
): SafeParseResult<ContextDeleteMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ContextDeleteMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ContextDeleteMeta' from JSON`,
  );
}

/** @internal */
export const ContextDeleteResponse$inboundSchema: z.ZodMiniType<
  ContextDeleteResponse,
  unknown
> = z.pipe(
  z.object({
    success: types.literal(true),
    creditsUsed: types.number(),
    retryAfter: types.number(),
    _meta: types.optional(z.lazy(() => ContextDeleteMeta$inboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      "_meta": "meta",
    });
  }),
);

export function contextDeleteResponseFromJSON(
  jsonString: string,
): SafeParseResult<ContextDeleteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ContextDeleteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ContextDeleteResponse' from JSON`,
  );
}

/** @internal */
export type EventsFeedRequest$Outbound = {
  since?: string | undefined;
  limit: number;
};

/** @internal */
export const EventsFeedRequest$outboundSchema: z.ZodMiniType<
  EventsFeedRequest$Outbound,
  EventsFeedRequest
> = z.object({
  since: z.optional(z.string()),
  limit: z._default(z.int(), 20),
});

export function eventsFeedRequestToJSON(
  eventsFeedRequest: EventsFeedRequest,
): string {
  return JSON.stringify(
    EventsFeedRequest$outboundSchema.parse(eventsFeedRequest),
  );
}

/** @internal */
export const EventsFeedType$inboundSchema: z.ZodMiniType<
  EventsFeedType,
  unknown
> = openEnums.inboundSchema(EventsFeedType);

/** @internal */
export const Event$inboundSchema: z.ZodMiniType<Event, unknown> = z.object({
  id: types.string(),
  type: EventsFeedType$inboundSchema,
  campaignId: types.optional(types.string()),
  campaignName: types.optional(types.string()),
  summary: types.string(),
  metadata: z.record(z.string(), z.any()),
  timestamp: types.number(),
});

export function eventFromJSON(
  jsonString: string,
): SafeParseResult<Event, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Event$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Event' from JSON`,
  );
}

/** @internal */
export const EventsFeedResponse$inboundSchema: z.ZodMiniType<
  EventsFeedResponse,
  unknown
> = z.object({
  events: z.array(z.lazy(() => Event$inboundSchema)),
  cursor: types.optional(types.number()),
});

export function eventsFeedResponseFromJSON(
  jsonString: string,
): SafeParseResult<EventsFeedResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EventsFeedResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EventsFeedResponse' from JSON`,
  );
}

/** @internal */
export const Context$inboundSchema: z.ZodMiniType<Context, unknown> = z.object({
  type: types.string(),
  label: types.nullable(types.string()),
  content: types.string(),
  scope: types.string(),
});

export function contextFromJSON(
  jsonString: string,
): SafeParseResult<Context, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Context$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Context' from JSON`,
  );
}

/** @internal */
export const ActiveAccountStatus$inboundSchema: z.ZodMiniType<
  ActiveAccountStatus,
  unknown
> = openEnums.inboundSchema(ActiveAccountStatus);

/** @internal */
export const ActiveAccount$inboundSchema: z.ZodMiniType<
  ActiveAccount,
  unknown
> = z.object({
  id: types.string(),
  name: types.nullable(types.string()),
  plan: types.string(),
  headline: types.nullable(types.string()),
  status: ActiveAccountStatus$inboundSchema,
  isUnlimited: types.boolean(),
  creditsLimit: types.number(),
  creditsCount: types.number(),
  simulateWrites: types.boolean(),
  isCurrent: types.boolean(),
});

export function activeAccountFromJSON(
  jsonString: string,
): SafeParseResult<ActiveAccount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActiveAccount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActiveAccount' from JSON`,
  );
}

/** @internal */
export const ContextGetAccountStatus$inboundSchema: z.ZodMiniType<
  ContextGetAccountStatus,
  unknown
> = openEnums.inboundSchema(ContextGetAccountStatus);

/** @internal */
export const ContextGetAccount$inboundSchema: z.ZodMiniType<
  ContextGetAccount,
  unknown
> = z.object({
  id: types.string(),
  name: types.nullable(types.string()),
  plan: types.string(),
  headline: types.nullable(types.string()),
  status: ContextGetAccountStatus$inboundSchema,
  isUnlimited: types.boolean(),
  creditsLimit: types.number(),
  creditsCount: types.number(),
  simulateWrites: types.boolean(),
  isCurrent: types.boolean(),
});

export function contextGetAccountFromJSON(
  jsonString: string,
): SafeParseResult<ContextGetAccount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ContextGetAccount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ContextGetAccount' from JSON`,
  );
}

/** @internal */
export const ContextGetStageCounts$inboundSchema: z.ZodMiniType<
  ContextGetStageCounts,
  unknown
> = z.object({
  contact: types.number(),
  lead: types.number(),
  qualified: types.number(),
  rejected: types.number(),
  total: types.number(),
});

export function contextGetStageCountsFromJSON(
  jsonString: string,
): SafeParseResult<ContextGetStageCounts, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ContextGetStageCounts$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ContextGetStageCounts' from JSON`,
  );
}

/** @internal */
export const ActiveCampaign$inboundSchema: z.ZodMiniType<
  ActiveCampaign,
  unknown
> = z.object({
  id: types.string(),
  name: types.string(),
  stageCounts: z.lazy(() => ContextGetStageCounts$inboundSchema),
});

export function activeCampaignFromJSON(
  jsonString: string,
): SafeParseResult<ActiveCampaign, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActiveCampaign$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActiveCampaign' from JSON`,
  );
}

/** @internal */
export const ContextGetType$inboundSchema: z.ZodMiniType<
  ContextGetType,
  unknown
> = openEnums.inboundSchema(ContextGetType);

/** @internal */
export const RecentEvent$inboundSchema: z.ZodMiniType<RecentEvent, unknown> = z
  .object({
    id: types.string(),
    type: ContextGetType$inboundSchema,
    campaignId: types.optional(types.string()),
    campaignName: types.optional(types.string()),
    summary: types.string(),
    metadata: z.record(z.string(), z.any()),
    timestamp: types.number(),
  });

export function recentEventFromJSON(
  jsonString: string,
): SafeParseResult<RecentEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RecentEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RecentEvent' from JSON`,
  );
}

/** @internal */
export const ContextGetResponse$inboundSchema: z.ZodMiniType<
  ContextGetResponse,
  unknown
> = z.object({
  credits: z.optional(z.nullable(z.any())),
  pipeline: z.record(z.string(), types.number()),
  contexts: z.array(z.lazy(() => Context$inboundSchema)),
  pendingDrafts: types.number(),
  failedDrafts: types.number(),
  pendingSentInvitations: types.number(),
  activeAccount: types.nullable(z.lazy(() => ActiveAccount$inboundSchema)),
  accounts: z.array(z.lazy(() => ContextGetAccount$inboundSchema)),
  activeCampaigns: z.array(z.lazy(() => ActiveCampaign$inboundSchema)),
  recentEvents: z.array(z.lazy(() => RecentEvent$inboundSchema)),
  llmStatus: z.optional(z.nullable(types.string())),
  llmFirstTrippedAt: z.optional(z.nullable(types.number())),
});

export function contextGetResponseFromJSON(
  jsonString: string,
): SafeParseResult<ContextGetResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ContextGetResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ContextGetResponse' from JSON`,
  );
}

/** @internal */
export const GetDmPollingSettingsSettings$inboundSchema: z.ZodMiniType<
  GetDmPollingSettingsSettings,
  unknown
> = z.object({
  dmWebhookUrl: types.nullable(types.string()),
  connectionLastPolledAt: types.nullable(types.string()),
});

export function getDmPollingSettingsSettingsFromJSON(
  jsonString: string,
): SafeParseResult<GetDmPollingSettingsSettings, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetDmPollingSettingsSettings$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetDmPollingSettingsSettings' from JSON`,
  );
}

/** @internal */
export const GetDmPollingSettingsCredits$inboundSchema: z.ZodMiniType<
  GetDmPollingSettingsCredits,
  unknown
> = z.object({
  current: types.number(),
  limit: types.nullable(types.number()),
  remaining: types.nullable(types.number()),
  percentage: types.number(),
  isUnlimited: types.boolean(),
});

export function getDmPollingSettingsCreditsFromJSON(
  jsonString: string,
): SafeParseResult<GetDmPollingSettingsCredits, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetDmPollingSettingsCredits$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetDmPollingSettingsCredits' from JSON`,
  );
}

/** @internal */
export const GetDmPollingSettingsMeta$inboundSchema: z.ZodMiniType<
  GetDmPollingSettingsMeta,
  unknown
> = z.object({
  credits: z.lazy(() => GetDmPollingSettingsCredits$inboundSchema),
});

export function getDmPollingSettingsMetaFromJSON(
  jsonString: string,
): SafeParseResult<GetDmPollingSettingsMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetDmPollingSettingsMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetDmPollingSettingsMeta' from JSON`,
  );
}

/** @internal */
export const GetDmPollingSettingsResponse$inboundSchema: z.ZodMiniType<
  GetDmPollingSettingsResponse,
  unknown
> = z.pipe(
  z.object({
    success: types.literal(true),
    settings: z.lazy(() => GetDmPollingSettingsSettings$inboundSchema),
    creditsUsed: types.number(),
    retryAfter: types.number(),
    _meta: types.optional(z.lazy(() => GetDmPollingSettingsMeta$inboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      "_meta": "meta",
    });
  }),
);

export function getDmPollingSettingsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetDmPollingSettingsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetDmPollingSettingsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetDmPollingSettingsResponse' from JSON`,
  );
}

/** @internal */
export type PatchDmPollingSettingsRequest$Outbound = {
  dmWebhookUrl?: string | null | undefined;
};

/** @internal */
export const PatchDmPollingSettingsRequest$outboundSchema: z.ZodMiniType<
  PatchDmPollingSettingsRequest$Outbound,
  PatchDmPollingSettingsRequest
> = z.object({
  dmWebhookUrl: z.optional(z.nullable(z.string())),
});

export function patchDmPollingSettingsRequestToJSON(
  patchDmPollingSettingsRequest: PatchDmPollingSettingsRequest,
): string {
  return JSON.stringify(
    PatchDmPollingSettingsRequest$outboundSchema.parse(
      patchDmPollingSettingsRequest,
    ),
  );
}

/** @internal */
export const PatchDmPollingSettingsSettings$inboundSchema: z.ZodMiniType<
  PatchDmPollingSettingsSettings,
  unknown
> = z.object({
  dmWebhookUrl: types.nullable(types.string()),
  connectionLastPolledAt: types.nullable(types.string()),
});

export function patchDmPollingSettingsSettingsFromJSON(
  jsonString: string,
): SafeParseResult<PatchDmPollingSettingsSettings, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchDmPollingSettingsSettings$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchDmPollingSettingsSettings' from JSON`,
  );
}

/** @internal */
export const PatchDmPollingSettingsCredits$inboundSchema: z.ZodMiniType<
  PatchDmPollingSettingsCredits,
  unknown
> = z.object({
  current: types.number(),
  limit: types.nullable(types.number()),
  remaining: types.nullable(types.number()),
  percentage: types.number(),
  isUnlimited: types.boolean(),
});

export function patchDmPollingSettingsCreditsFromJSON(
  jsonString: string,
): SafeParseResult<PatchDmPollingSettingsCredits, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchDmPollingSettingsCredits$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchDmPollingSettingsCredits' from JSON`,
  );
}

/** @internal */
export const PatchDmPollingSettingsMeta$inboundSchema: z.ZodMiniType<
  PatchDmPollingSettingsMeta,
  unknown
> = z.object({
  credits: z.lazy(() => PatchDmPollingSettingsCredits$inboundSchema),
});

export function patchDmPollingSettingsMetaFromJSON(
  jsonString: string,
): SafeParseResult<PatchDmPollingSettingsMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchDmPollingSettingsMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchDmPollingSettingsMeta' from JSON`,
  );
}

/** @internal */
export const PatchDmPollingSettingsResponse$inboundSchema: z.ZodMiniType<
  PatchDmPollingSettingsResponse,
  unknown
> = z.pipe(
  z.object({
    success: types.literal(true),
    settings: z.lazy(() => PatchDmPollingSettingsSettings$inboundSchema),
    creditsUsed: types.number(),
    retryAfter: types.number(),
    _meta: types.optional(
      z.lazy(() => PatchDmPollingSettingsMeta$inboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "_meta": "meta",
    });
  }),
);

export function patchDmPollingSettingsResponseFromJSON(
  jsonString: string,
): SafeParseResult<PatchDmPollingSettingsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchDmPollingSettingsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchDmPollingSettingsResponse' from JSON`,
  );
}

/** @internal */
export type DeleteWorkspaceAccountRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteWorkspaceAccountRequest$outboundSchema: z.ZodMiniType<
  DeleteWorkspaceAccountRequest$Outbound,
  DeleteWorkspaceAccountRequest
> = z.object({
  id: z.string(),
});

export function deleteWorkspaceAccountRequestToJSON(
  deleteWorkspaceAccountRequest: DeleteWorkspaceAccountRequest,
): string {
  return JSON.stringify(
    DeleteWorkspaceAccountRequest$outboundSchema.parse(
      deleteWorkspaceAccountRequest,
    ),
  );
}

/** @internal */
export const DeleteWorkspaceAccountCredits$inboundSchema: z.ZodMiniType<
  DeleteWorkspaceAccountCredits,
  unknown
> = z.object({
  current: types.number(),
  limit: types.nullable(types.number()),
  remaining: types.nullable(types.number()),
  percentage: types.number(),
  isUnlimited: types.boolean(),
});

export function deleteWorkspaceAccountCreditsFromJSON(
  jsonString: string,
): SafeParseResult<DeleteWorkspaceAccountCredits, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteWorkspaceAccountCredits$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteWorkspaceAccountCredits' from JSON`,
  );
}

/** @internal */
export const DeleteWorkspaceAccountMeta$inboundSchema: z.ZodMiniType<
  DeleteWorkspaceAccountMeta,
  unknown
> = z.object({
  credits: z.lazy(() => DeleteWorkspaceAccountCredits$inboundSchema),
});

export function deleteWorkspaceAccountMetaFromJSON(
  jsonString: string,
): SafeParseResult<DeleteWorkspaceAccountMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteWorkspaceAccountMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteWorkspaceAccountMeta' from JSON`,
  );
}

/** @internal */
export const DeleteWorkspaceAccountResponse$inboundSchema: z.ZodMiniType<
  DeleteWorkspaceAccountResponse,
  unknown
> = z.pipe(
  z.object({
    success: types.literal(true),
    message: types.string(),
    creditsUsed: types.number(),
    retryAfter: types.number(),
    _meta: types.optional(
      z.lazy(() => DeleteWorkspaceAccountMeta$inboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "_meta": "meta",
    });
  }),
);

export function deleteWorkspaceAccountResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteWorkspaceAccountResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteWorkspaceAccountResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteWorkspaceAccountResponse' from JSON`,
  );
}

/** @internal */
export const UpgradeWorkspaceAccountAction$outboundSchema: z.ZodMiniEnum<
  typeof UpgradeWorkspaceAccountAction
> = z.enum(UpgradeWorkspaceAccountAction);

/** @internal */
export type UpgradeWorkspaceAccountRequest$Outbound = {
  credentialsId: string;
  action: string;
};

/** @internal */
export const UpgradeWorkspaceAccountRequest$outboundSchema: z.ZodMiniType<
  UpgradeWorkspaceAccountRequest$Outbound,
  UpgradeWorkspaceAccountRequest
> = z.object({
  credentialsId: z.string(),
  action: UpgradeWorkspaceAccountAction$outboundSchema,
});

export function upgradeWorkspaceAccountRequestToJSON(
  upgradeWorkspaceAccountRequest: UpgradeWorkspaceAccountRequest,
): string {
  return JSON.stringify(
    UpgradeWorkspaceAccountRequest$outboundSchema.parse(
      upgradeWorkspaceAccountRequest,
    ),
  );
}

/** @internal */
export const UpgradeWorkspaceAccountCredits$inboundSchema: z.ZodMiniType<
  UpgradeWorkspaceAccountCredits,
  unknown
> = z.object({
  current: types.number(),
  limit: types.nullable(types.number()),
  remaining: types.nullable(types.number()),
  percentage: types.number(),
  isUnlimited: types.boolean(),
});

export function upgradeWorkspaceAccountCreditsFromJSON(
  jsonString: string,
): SafeParseResult<UpgradeWorkspaceAccountCredits, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpgradeWorkspaceAccountCredits$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpgradeWorkspaceAccountCredits' from JSON`,
  );
}

/** @internal */
export const UpgradeWorkspaceAccountMeta$inboundSchema: z.ZodMiniType<
  UpgradeWorkspaceAccountMeta,
  unknown
> = z.object({
  credits: z.lazy(() => UpgradeWorkspaceAccountCredits$inboundSchema),
});

export function upgradeWorkspaceAccountMetaFromJSON(
  jsonString: string,
): SafeParseResult<UpgradeWorkspaceAccountMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpgradeWorkspaceAccountMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpgradeWorkspaceAccountMeta' from JSON`,
  );
}

/** @internal */
export const UpgradeWorkspaceAccountResponse$inboundSchema: z.ZodMiniType<
  UpgradeWorkspaceAccountResponse,
  unknown
> = z.pipe(
  z.object({
    success: types.literal(true),
    message: types.string(),
    seatsUsed: types.number(),
    seatsIncluded: types.number(),
    creditsUsed: types.number(),
    retryAfter: types.number(),
    _meta: types.optional(
      z.lazy(() => UpgradeWorkspaceAccountMeta$inboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "_meta": "meta",
    });
  }),
);

export function upgradeWorkspaceAccountResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpgradeWorkspaceAccountResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpgradeWorkspaceAccountResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpgradeWorkspaceAccountResponse' from JSON`,
  );
}

/** @internal */
export const CreateWorkspaceInviteAction$outboundSchema: z.ZodMiniEnum<
  typeof CreateWorkspaceInviteAction
> = z.enum(CreateWorkspaceInviteAction);

/** @internal */
export type CreateWorkspaceInviteRequest$Outbound = {
  action: string;
  email?: string | undefined;
  name?: string | undefined;
  maxUses: number;
};

/** @internal */
export const CreateWorkspaceInviteRequest$outboundSchema: z.ZodMiniType<
  CreateWorkspaceInviteRequest$Outbound,
  CreateWorkspaceInviteRequest
> = z.object({
  action: CreateWorkspaceInviteAction$outboundSchema,
  email: z.optional(z.string()),
  name: z.optional(z.string()),
  maxUses: z._default(z.int(), 1),
});

export function createWorkspaceInviteRequestToJSON(
  createWorkspaceInviteRequest: CreateWorkspaceInviteRequest,
): string {
  return JSON.stringify(
    CreateWorkspaceInviteRequest$outboundSchema.parse(
      createWorkspaceInviteRequest,
    ),
  );
}

/** @internal */
export const CreateWorkspaceInviteInvite2$inboundSchema: z.ZodMiniType<
  CreateWorkspaceInviteInvite2,
  unknown
> = z.object({
  id: types.string(),
  email: types.nullable(types.string()),
  name: types.nullable(types.string()),
  code: types.string(),
  status: types.optional(types.string()),
  maxUses: types.number(),
  useCount: types.number(),
  expiresAt: types.nullable(types.string()),
  createdAt: types.string(),
});

export function createWorkspaceInviteInvite2FromJSON(
  jsonString: string,
): SafeParseResult<CreateWorkspaceInviteInvite2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateWorkspaceInviteInvite2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateWorkspaceInviteInvite2' from JSON`,
  );
}

/** @internal */
export const Workspace$inboundSchema: z.ZodMiniType<Workspace, unknown> = z
  .object({
    tier: types.string(),
    proSeatsIncluded: types.number(),
    proSeatsUsed: types.number(),
  });

export function workspaceFromJSON(
  jsonString: string,
): SafeParseResult<Workspace, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Workspace$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Workspace' from JSON`,
  );
}

/** @internal */
export const CreateWorkspaceInviteCredits2$inboundSchema: z.ZodMiniType<
  CreateWorkspaceInviteCredits2,
  unknown
> = z.object({
  current: types.number(),
  limit: types.nullable(types.number()),
  remaining: types.nullable(types.number()),
  percentage: types.number(),
  isUnlimited: types.boolean(),
});

export function createWorkspaceInviteCredits2FromJSON(
  jsonString: string,
): SafeParseResult<CreateWorkspaceInviteCredits2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateWorkspaceInviteCredits2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateWorkspaceInviteCredits2' from JSON`,
  );
}

/** @internal */
export const CreateWorkspaceInviteMeta2$inboundSchema: z.ZodMiniType<
  CreateWorkspaceInviteMeta2,
  unknown
> = z.object({
  credits: z.lazy(() => CreateWorkspaceInviteCredits2$inboundSchema),
});

export function createWorkspaceInviteMeta2FromJSON(
  jsonString: string,
): SafeParseResult<CreateWorkspaceInviteMeta2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateWorkspaceInviteMeta2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateWorkspaceInviteMeta2' from JSON`,
  );
}

/** @internal */
export const CreateWorkspaceInviteResponseBody2$inboundSchema: z.ZodMiniType<
  CreateWorkspaceInviteResponseBody2,
  unknown
> = z.pipe(
  z.object({
    success: types.literal(true),
    invites: z.array(z.lazy(() => CreateWorkspaceInviteInvite2$inboundSchema)),
    workspace: z.lazy(() => Workspace$inboundSchema),
    creditsUsed: types.number(),
    retryAfter: types.number(),
    _meta: types.optional(
      z.lazy(() => CreateWorkspaceInviteMeta2$inboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "_meta": "meta",
    });
  }),
);

export function createWorkspaceInviteResponseBody2FromJSON(
  jsonString: string,
): SafeParseResult<CreateWorkspaceInviteResponseBody2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CreateWorkspaceInviteResponseBody2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateWorkspaceInviteResponseBody2' from JSON`,
  );
}

/** @internal */
export const CreateWorkspaceInviteInvite1$inboundSchema: z.ZodMiniType<
  CreateWorkspaceInviteInvite1,
  unknown
> = z.object({
  id: types.string(),
  email: types.nullable(types.string()),
  name: types.nullable(types.string()),
  code: types.string(),
  status: types.optional(types.string()),
  maxUses: types.number(),
  useCount: types.number(),
  expiresAt: types.nullable(types.string()),
  createdAt: types.string(),
});

export function createWorkspaceInviteInvite1FromJSON(
  jsonString: string,
): SafeParseResult<CreateWorkspaceInviteInvite1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateWorkspaceInviteInvite1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateWorkspaceInviteInvite1' from JSON`,
  );
}

/** @internal */
export const CreateWorkspaceInviteCredits1$inboundSchema: z.ZodMiniType<
  CreateWorkspaceInviteCredits1,
  unknown
> = z.object({
  current: types.number(),
  limit: types.nullable(types.number()),
  remaining: types.nullable(types.number()),
  percentage: types.number(),
  isUnlimited: types.boolean(),
});

export function createWorkspaceInviteCredits1FromJSON(
  jsonString: string,
): SafeParseResult<CreateWorkspaceInviteCredits1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateWorkspaceInviteCredits1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateWorkspaceInviteCredits1' from JSON`,
  );
}

/** @internal */
export const CreateWorkspaceInviteMeta1$inboundSchema: z.ZodMiniType<
  CreateWorkspaceInviteMeta1,
  unknown
> = z.object({
  credits: z.lazy(() => CreateWorkspaceInviteCredits1$inboundSchema),
});

export function createWorkspaceInviteMeta1FromJSON(
  jsonString: string,
): SafeParseResult<CreateWorkspaceInviteMeta1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateWorkspaceInviteMeta1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateWorkspaceInviteMeta1' from JSON`,
  );
}

/** @internal */
export const CreateWorkspaceInviteResponseBody1$inboundSchema: z.ZodMiniType<
  CreateWorkspaceInviteResponseBody1,
  unknown
> = z.pipe(
  z.object({
    success: types.literal(true),
    invite: z.lazy(() => CreateWorkspaceInviteInvite1$inboundSchema),
    creditsUsed: types.number(),
    retryAfter: types.number(),
    _meta: types.optional(
      z.lazy(() => CreateWorkspaceInviteMeta1$inboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "_meta": "meta",
    });
  }),
);

export function createWorkspaceInviteResponseBody1FromJSON(
  jsonString: string,
): SafeParseResult<CreateWorkspaceInviteResponseBody1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CreateWorkspaceInviteResponseBody1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateWorkspaceInviteResponseBody1' from JSON`,
  );
}

/** @internal */
export const CreateWorkspaceInviteResponse$inboundSchema: z.ZodMiniType<
  CreateWorkspaceInviteResponse,
  unknown
> = smartUnion([
  z.lazy(() => CreateWorkspaceInviteResponseBody2$inboundSchema),
  z.lazy(() => CreateWorkspaceInviteResponseBody1$inboundSchema),
]);

export function createWorkspaceInviteResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateWorkspaceInviteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateWorkspaceInviteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateWorkspaceInviteResponse' from JSON`,
  );
}

/** @internal */
export type DeleteWorkspaceInviteRequest$Outbound = {
  inviteId: string;
};

/** @internal */
export const DeleteWorkspaceInviteRequest$outboundSchema: z.ZodMiniType<
  DeleteWorkspaceInviteRequest$Outbound,
  DeleteWorkspaceInviteRequest
> = z.object({
  inviteId: z.string(),
});

export function deleteWorkspaceInviteRequestToJSON(
  deleteWorkspaceInviteRequest: DeleteWorkspaceInviteRequest,
): string {
  return JSON.stringify(
    DeleteWorkspaceInviteRequest$outboundSchema.parse(
      deleteWorkspaceInviteRequest,
    ),
  );
}

/** @internal */
export const DeleteWorkspaceInviteCredits$inboundSchema: z.ZodMiniType<
  DeleteWorkspaceInviteCredits,
  unknown
> = z.object({
  current: types.number(),
  limit: types.nullable(types.number()),
  remaining: types.nullable(types.number()),
  percentage: types.number(),
  isUnlimited: types.boolean(),
});

export function deleteWorkspaceInviteCreditsFromJSON(
  jsonString: string,
): SafeParseResult<DeleteWorkspaceInviteCredits, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteWorkspaceInviteCredits$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteWorkspaceInviteCredits' from JSON`,
  );
}

/** @internal */
export const DeleteWorkspaceInviteMeta$inboundSchema: z.ZodMiniType<
  DeleteWorkspaceInviteMeta,
  unknown
> = z.object({
  credits: z.lazy(() => DeleteWorkspaceInviteCredits$inboundSchema),
});

export function deleteWorkspaceInviteMetaFromJSON(
  jsonString: string,
): SafeParseResult<DeleteWorkspaceInviteMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteWorkspaceInviteMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteWorkspaceInviteMeta' from JSON`,
  );
}

/** @internal */
export const DeleteWorkspaceInviteResponse$inboundSchema: z.ZodMiniType<
  DeleteWorkspaceInviteResponse,
  unknown
> = z.pipe(
  z.object({
    success: types.literal(true),
    creditsUsed: types.number(),
    retryAfter: types.number(),
    _meta: types.optional(
      z.lazy(() => DeleteWorkspaceInviteMeta$inboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "_meta": "meta",
    });
  }),
);

export function deleteWorkspaceInviteResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteWorkspaceInviteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteWorkspaceInviteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteWorkspaceInviteResponse' from JSON`,
  );
}
