/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type EditLinkedInCommentRequest = {
  /**
   * urn:li:fsd_comment:(COMMENT_ID,urn:li:ugcPost:POST_ID) - from comment API response
   */
  fsdCommentUrn?: string | undefined;
  /**
   * Legacy comment URN format
   */
  commentUrn?: string | undefined;
  /**
   * New comment text
   */
  text: string;
};

export type EditLinkedInCommentInternalServerErrorDetails =
  | string
  | Array<string>;

export type EditLinkedInCommentInternalServerErrorError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const EditLinkedInCommentCode = {
  RateLimitExceeded: "rate_limit_exceeded",
} as const;
export type EditLinkedInCommentCode = ClosedEnum<
  typeof EditLinkedInCommentCode
>;

/**
 * Current and max daily usage (null if no daily cap).
 */
export type EditLinkedInCommentDaily = {
  current: number;
  limit: number;
};

/**
 * Current and max weekly usage (null if no weekly cap).
 */
export type EditLinkedInCommentWeekly = {
  current: number;
  limit: number;
};

export type EditLinkedInCommentTooManyRequestsError = {
  code: EditLinkedInCommentCode;
  message: string;
  docs?: string | undefined;
  /**
   * Seconds to wait before retrying.
   */
  retryAfter: number;
  /**
   * Current and max daily usage (null if no daily cap).
   */
  daily: EditLinkedInCommentDaily | null;
  /**
   * Current and max weekly usage (null if no weekly cap).
   */
  weekly: EditLinkedInCommentWeekly | null;
};

export type EditLinkedInCommentUnprocessableEntityDetails =
  | string
  | Array<string>;

export type EditLinkedInCommentUnprocessableEntityError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export type EditLinkedInCommentGoneDetails = string | Array<string>;

export type EditLinkedInCommentGoneError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export type EditLinkedInCommentConflictDetails = string | Array<string>;

export type EditLinkedInCommentConflictError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export type EditLinkedInCommentNotFoundDetails = string | Array<string>;

export type EditLinkedInCommentNotFoundError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export type EditLinkedInCommentForbiddenDetails = string | Array<string>;

export type EditLinkedInCommentForbiddenError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export type EditLinkedInCommentUnauthorizedDetails = string | Array<string>;

export type EditLinkedInCommentUnauthorizedError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export type EditLinkedInCommentBadRequestDetails = string | Array<string>;

export type EditLinkedInCommentBadRequestError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

/**
 * Comment edited
 */
export type EditLinkedInCommentResponse = {
  success: true;
  /**
   * Credits consumed by this call (0 for free endpoints, cached results, or duplicates).
   */
  creditsUsed: number;
  /**
   * Seconds to wait before making another call of the same type. 0 means no wait needed.
   */
  retryAfter: number;
};

/** @internal */
export type EditLinkedInCommentRequest$Outbound = {
  fsdCommentUrn?: string | undefined;
  commentUrn?: string | undefined;
  text: string;
};

/** @internal */
export const EditLinkedInCommentRequest$outboundSchema: z.ZodMiniType<
  EditLinkedInCommentRequest$Outbound,
  EditLinkedInCommentRequest
> = z.object({
  fsdCommentUrn: z.optional(z.string()),
  commentUrn: z.optional(z.string()),
  text: z.string(),
});

export function editLinkedInCommentRequestToJSON(
  editLinkedInCommentRequest: EditLinkedInCommentRequest,
): string {
  return JSON.stringify(
    EditLinkedInCommentRequest$outboundSchema.parse(editLinkedInCommentRequest),
  );
}

/** @internal */
export const EditLinkedInCommentInternalServerErrorDetails$inboundSchema:
  z.ZodMiniType<EditLinkedInCommentInternalServerErrorDetails, unknown> =
    smartUnion([types.string(), z.array(types.string())]);

export function editLinkedInCommentInternalServerErrorDetailsFromJSON(
  jsonString: string,
): SafeParseResult<
  EditLinkedInCommentInternalServerErrorDetails,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      EditLinkedInCommentInternalServerErrorDetails$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'EditLinkedInCommentInternalServerErrorDetails' from JSON`,
  );
}

/** @internal */
export const EditLinkedInCommentInternalServerErrorError$inboundSchema:
  z.ZodMiniType<EditLinkedInCommentInternalServerErrorError, unknown> = z
    .object({
      code: types.string(),
      message: types.string(),
      docs: types.optional(types.string()),
      details: types.optional(
        smartUnion([types.string(), z.array(types.string())]),
      ),
    });

export function editLinkedInCommentInternalServerErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<
  EditLinkedInCommentInternalServerErrorError,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      EditLinkedInCommentInternalServerErrorError$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'EditLinkedInCommentInternalServerErrorError' from JSON`,
  );
}

/** @internal */
export const EditLinkedInCommentCode$inboundSchema: z.ZodMiniEnum<
  typeof EditLinkedInCommentCode
> = z.enum(EditLinkedInCommentCode);

/** @internal */
export const EditLinkedInCommentDaily$inboundSchema: z.ZodMiniType<
  EditLinkedInCommentDaily,
  unknown
> = z.object({
  current: types.number(),
  limit: types.number(),
});

export function editLinkedInCommentDailyFromJSON(
  jsonString: string,
): SafeParseResult<EditLinkedInCommentDaily, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EditLinkedInCommentDaily$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EditLinkedInCommentDaily' from JSON`,
  );
}

/** @internal */
export const EditLinkedInCommentWeekly$inboundSchema: z.ZodMiniType<
  EditLinkedInCommentWeekly,
  unknown
> = z.object({
  current: types.number(),
  limit: types.number(),
});

export function editLinkedInCommentWeeklyFromJSON(
  jsonString: string,
): SafeParseResult<EditLinkedInCommentWeekly, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EditLinkedInCommentWeekly$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EditLinkedInCommentWeekly' from JSON`,
  );
}

/** @internal */
export const EditLinkedInCommentTooManyRequestsError$inboundSchema:
  z.ZodMiniType<EditLinkedInCommentTooManyRequestsError, unknown> = z.object({
    code: EditLinkedInCommentCode$inboundSchema,
    message: types.string(),
    docs: types.optional(types.string()),
    retryAfter: types.number(),
    daily: types.nullable(z.lazy(() => EditLinkedInCommentDaily$inboundSchema)),
    weekly: types.nullable(
      z.lazy(() => EditLinkedInCommentWeekly$inboundSchema),
    ),
  });

export function editLinkedInCommentTooManyRequestsErrorFromJSON(
  jsonString: string,
): SafeParseResult<
  EditLinkedInCommentTooManyRequestsError,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      EditLinkedInCommentTooManyRequestsError$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'EditLinkedInCommentTooManyRequestsError' from JSON`,
  );
}

/** @internal */
export const EditLinkedInCommentUnprocessableEntityDetails$inboundSchema:
  z.ZodMiniType<EditLinkedInCommentUnprocessableEntityDetails, unknown> =
    smartUnion([types.string(), z.array(types.string())]);

export function editLinkedInCommentUnprocessableEntityDetailsFromJSON(
  jsonString: string,
): SafeParseResult<
  EditLinkedInCommentUnprocessableEntityDetails,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      EditLinkedInCommentUnprocessableEntityDetails$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'EditLinkedInCommentUnprocessableEntityDetails' from JSON`,
  );
}

/** @internal */
export const EditLinkedInCommentUnprocessableEntityError$inboundSchema:
  z.ZodMiniType<EditLinkedInCommentUnprocessableEntityError, unknown> = z
    .object({
      code: types.string(),
      message: types.string(),
      docs: types.optional(types.string()),
      details: types.optional(
        smartUnion([types.string(), z.array(types.string())]),
      ),
    });

export function editLinkedInCommentUnprocessableEntityErrorFromJSON(
  jsonString: string,
): SafeParseResult<
  EditLinkedInCommentUnprocessableEntityError,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      EditLinkedInCommentUnprocessableEntityError$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'EditLinkedInCommentUnprocessableEntityError' from JSON`,
  );
}

/** @internal */
export const EditLinkedInCommentGoneDetails$inboundSchema: z.ZodMiniType<
  EditLinkedInCommentGoneDetails,
  unknown
> = smartUnion([types.string(), z.array(types.string())]);

export function editLinkedInCommentGoneDetailsFromJSON(
  jsonString: string,
): SafeParseResult<EditLinkedInCommentGoneDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EditLinkedInCommentGoneDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EditLinkedInCommentGoneDetails' from JSON`,
  );
}

/** @internal */
export const EditLinkedInCommentGoneError$inboundSchema: z.ZodMiniType<
  EditLinkedInCommentGoneError,
  unknown
> = z.object({
  code: types.string(),
  message: types.string(),
  docs: types.optional(types.string()),
  details: types.optional(
    smartUnion([types.string(), z.array(types.string())]),
  ),
});

export function editLinkedInCommentGoneErrorFromJSON(
  jsonString: string,
): SafeParseResult<EditLinkedInCommentGoneError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EditLinkedInCommentGoneError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EditLinkedInCommentGoneError' from JSON`,
  );
}

/** @internal */
export const EditLinkedInCommentConflictDetails$inboundSchema: z.ZodMiniType<
  EditLinkedInCommentConflictDetails,
  unknown
> = smartUnion([types.string(), z.array(types.string())]);

export function editLinkedInCommentConflictDetailsFromJSON(
  jsonString: string,
): SafeParseResult<EditLinkedInCommentConflictDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      EditLinkedInCommentConflictDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EditLinkedInCommentConflictDetails' from JSON`,
  );
}

/** @internal */
export const EditLinkedInCommentConflictError$inboundSchema: z.ZodMiniType<
  EditLinkedInCommentConflictError,
  unknown
> = z.object({
  code: types.string(),
  message: types.string(),
  docs: types.optional(types.string()),
  details: types.optional(
    smartUnion([types.string(), z.array(types.string())]),
  ),
});

export function editLinkedInCommentConflictErrorFromJSON(
  jsonString: string,
): SafeParseResult<EditLinkedInCommentConflictError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EditLinkedInCommentConflictError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EditLinkedInCommentConflictError' from JSON`,
  );
}

/** @internal */
export const EditLinkedInCommentNotFoundDetails$inboundSchema: z.ZodMiniType<
  EditLinkedInCommentNotFoundDetails,
  unknown
> = smartUnion([types.string(), z.array(types.string())]);

export function editLinkedInCommentNotFoundDetailsFromJSON(
  jsonString: string,
): SafeParseResult<EditLinkedInCommentNotFoundDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      EditLinkedInCommentNotFoundDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EditLinkedInCommentNotFoundDetails' from JSON`,
  );
}

/** @internal */
export const EditLinkedInCommentNotFoundError$inboundSchema: z.ZodMiniType<
  EditLinkedInCommentNotFoundError,
  unknown
> = z.object({
  code: types.string(),
  message: types.string(),
  docs: types.optional(types.string()),
  details: types.optional(
    smartUnion([types.string(), z.array(types.string())]),
  ),
});

export function editLinkedInCommentNotFoundErrorFromJSON(
  jsonString: string,
): SafeParseResult<EditLinkedInCommentNotFoundError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EditLinkedInCommentNotFoundError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EditLinkedInCommentNotFoundError' from JSON`,
  );
}

/** @internal */
export const EditLinkedInCommentForbiddenDetails$inboundSchema: z.ZodMiniType<
  EditLinkedInCommentForbiddenDetails,
  unknown
> = smartUnion([types.string(), z.array(types.string())]);

export function editLinkedInCommentForbiddenDetailsFromJSON(
  jsonString: string,
): SafeParseResult<EditLinkedInCommentForbiddenDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      EditLinkedInCommentForbiddenDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EditLinkedInCommentForbiddenDetails' from JSON`,
  );
}

/** @internal */
export const EditLinkedInCommentForbiddenError$inboundSchema: z.ZodMiniType<
  EditLinkedInCommentForbiddenError,
  unknown
> = z.object({
  code: types.string(),
  message: types.string(),
  docs: types.optional(types.string()),
  details: types.optional(
    smartUnion([types.string(), z.array(types.string())]),
  ),
});

export function editLinkedInCommentForbiddenErrorFromJSON(
  jsonString: string,
): SafeParseResult<EditLinkedInCommentForbiddenError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EditLinkedInCommentForbiddenError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EditLinkedInCommentForbiddenError' from JSON`,
  );
}

/** @internal */
export const EditLinkedInCommentUnauthorizedDetails$inboundSchema:
  z.ZodMiniType<EditLinkedInCommentUnauthorizedDetails, unknown> = smartUnion([
    types.string(),
    z.array(types.string()),
  ]);

export function editLinkedInCommentUnauthorizedDetailsFromJSON(
  jsonString: string,
): SafeParseResult<EditLinkedInCommentUnauthorizedDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      EditLinkedInCommentUnauthorizedDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EditLinkedInCommentUnauthorizedDetails' from JSON`,
  );
}

/** @internal */
export const EditLinkedInCommentUnauthorizedError$inboundSchema: z.ZodMiniType<
  EditLinkedInCommentUnauthorizedError,
  unknown
> = z.object({
  code: types.string(),
  message: types.string(),
  docs: types.optional(types.string()),
  details: types.optional(
    smartUnion([types.string(), z.array(types.string())]),
  ),
});

export function editLinkedInCommentUnauthorizedErrorFromJSON(
  jsonString: string,
): SafeParseResult<EditLinkedInCommentUnauthorizedError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      EditLinkedInCommentUnauthorizedError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EditLinkedInCommentUnauthorizedError' from JSON`,
  );
}

/** @internal */
export const EditLinkedInCommentBadRequestDetails$inboundSchema: z.ZodMiniType<
  EditLinkedInCommentBadRequestDetails,
  unknown
> = smartUnion([types.string(), z.array(types.string())]);

export function editLinkedInCommentBadRequestDetailsFromJSON(
  jsonString: string,
): SafeParseResult<EditLinkedInCommentBadRequestDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      EditLinkedInCommentBadRequestDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EditLinkedInCommentBadRequestDetails' from JSON`,
  );
}

/** @internal */
export const EditLinkedInCommentBadRequestError$inboundSchema: z.ZodMiniType<
  EditLinkedInCommentBadRequestError,
  unknown
> = z.object({
  code: types.string(),
  message: types.string(),
  docs: types.optional(types.string()),
  details: types.optional(
    smartUnion([types.string(), z.array(types.string())]),
  ),
});

export function editLinkedInCommentBadRequestErrorFromJSON(
  jsonString: string,
): SafeParseResult<EditLinkedInCommentBadRequestError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      EditLinkedInCommentBadRequestError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EditLinkedInCommentBadRequestError' from JSON`,
  );
}

/** @internal */
export const EditLinkedInCommentResponse$inboundSchema: z.ZodMiniType<
  EditLinkedInCommentResponse,
  unknown
> = z.object({
  success: types.literal(true),
  creditsUsed: types.number(),
  retryAfter: types.number(),
});

export function editLinkedInCommentResponseFromJSON(
  jsonString: string,
): SafeParseResult<EditLinkedInCommentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EditLinkedInCommentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EditLinkedInCommentResponse' from JSON`,
  );
}
