/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type FindLinkedInConversationRequest = {
  /**
   * Profile URL or URN (e.g. 'https://linkedin.com/in/marie-sandre' or 'urn:li:fsd_profile:ACoAA...'). Direct O(1) conversation lookup via LinkedIn's compose API — no search, no inbox scan. 0 credits.
   */
  profile: string;
  /**
   * If true, also return the conversation's recent messages (0 extra credits).
   */
  includeMessages?: boolean | undefined;
};

export type FindLinkedInConversationInternalServerErrorDetails =
  | string
  | Array<string>;

export type FindLinkedInConversationInternalServerErrorError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const FindLinkedInConversationCode = {
  RateLimitExceeded: "rate_limit_exceeded",
} as const;
export type FindLinkedInConversationCode = ClosedEnum<
  typeof FindLinkedInConversationCode
>;

/**
 * Current and max daily usage (null if no daily cap).
 */
export type FindLinkedInConversationDaily = {
  current: number;
  limit: number;
};

/**
 * Current and max weekly usage (null if no weekly cap).
 */
export type FindLinkedInConversationWeekly = {
  current: number;
  limit: number;
};

export type FindLinkedInConversationTooManyRequestsError = {
  code: FindLinkedInConversationCode;
  message: string;
  docs?: string | undefined;
  /**
   * Seconds to wait before retrying.
   */
  retryAfter: number;
  /**
   * Current and max daily usage (null if no daily cap).
   */
  daily: FindLinkedInConversationDaily | null;
  /**
   * Current and max weekly usage (null if no weekly cap).
   */
  weekly: FindLinkedInConversationWeekly | null;
};

export type FindLinkedInConversationUnprocessableEntityDetails =
  | string
  | Array<string>;

export type FindLinkedInConversationUnprocessableEntityError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export type FindLinkedInConversationGoneDetails = string | Array<string>;

export type FindLinkedInConversationGoneError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export type FindLinkedInConversationConflictDetails = string | Array<string>;

export type FindLinkedInConversationConflictError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export type FindLinkedInConversationNotFoundDetails = string | Array<string>;

export type FindLinkedInConversationNotFoundError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export type FindLinkedInConversationForbiddenDetails = string | Array<string>;

export type FindLinkedInConversationForbiddenError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export type FindLinkedInConversationUnauthorizedDetails =
  | string
  | Array<string>;

export type FindLinkedInConversationUnauthorizedError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export type FindLinkedInConversationBadRequestDetails = string | Array<string>;

export type FindLinkedInConversationBadRequestError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

/**
 * Lightweight conversation reference (O(1) lookup returns URN only, not full details).
 */
export type FindLinkedInConversationConversation = {
  conversationUrn: string;
};

export type FindLinkedInConversationSender = {
  firstName: string;
  lastName: string;
  profileUrl: string | null;
  headline: string | null;
  profilePicture: string | null;
};

export const FindLinkedInConversationType = {
  Audio: "audio",
  SharedPost: "shared_post",
  RepliedMessage: "replied_message",
  Image: "image",
  File: "file",
  Unknown: "unknown",
} as const;
export type FindLinkedInConversationType = OpenEnum<
  typeof FindLinkedInConversationType
>;

export type FindLinkedInConversationAttachment = {
  type: FindLinkedInConversationType;
  audioUrl?: string | undefined;
  audioDuration?: number | undefined;
  hostUrn?: string | undefined;
  repliedText?: string | undefined;
  repliedSenderName?: string | undefined;
  imageUrl?: string | undefined;
  fileName?: string | undefined;
  fileUrl?: string | undefined;
};

export type FindLinkedInConversationMessage = {
  messageUrn: string;
  text: string | null;
  deliveredAt: number;
  senderProfileUrn: string;
  sender: FindLinkedInConversationSender;
  attachments: Array<FindLinkedInConversationAttachment>;
};

/**
 * Conversation found (or not)
 */
export type FindLinkedInConversationResponse = {
  success: true;
  found: boolean;
  /**
   * Lightweight conversation reference (O(1) lookup returns URN only, not full details).
   */
  conversation: FindLinkedInConversationConversation | null;
  messages: Array<FindLinkedInConversationMessage> | null;
  /**
   * Credits consumed by this call (0 for free endpoints, cached results, or duplicates).
   */
  creditsUsed: number;
  /**
   * Seconds to wait before making another call of the same type. 0 means no wait needed.
   */
  retryAfter: number;
};

/** @internal */
export type FindLinkedInConversationRequest$Outbound = {
  profile: string;
  includeMessages: boolean;
};

/** @internal */
export const FindLinkedInConversationRequest$outboundSchema: z.ZodMiniType<
  FindLinkedInConversationRequest$Outbound,
  FindLinkedInConversationRequest
> = z.object({
  profile: z.string(),
  includeMessages: z._default(z.boolean(), false),
});

export function findLinkedInConversationRequestToJSON(
  findLinkedInConversationRequest: FindLinkedInConversationRequest,
): string {
  return JSON.stringify(
    FindLinkedInConversationRequest$outboundSchema.parse(
      findLinkedInConversationRequest,
    ),
  );
}

/** @internal */
export const FindLinkedInConversationInternalServerErrorDetails$inboundSchema:
  z.ZodMiniType<FindLinkedInConversationInternalServerErrorDetails, unknown> =
    smartUnion([types.string(), z.array(types.string())]);

export function findLinkedInConversationInternalServerErrorDetailsFromJSON(
  jsonString: string,
): SafeParseResult<
  FindLinkedInConversationInternalServerErrorDetails,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      FindLinkedInConversationInternalServerErrorDetails$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'FindLinkedInConversationInternalServerErrorDetails' from JSON`,
  );
}

/** @internal */
export const FindLinkedInConversationInternalServerErrorError$inboundSchema:
  z.ZodMiniType<FindLinkedInConversationInternalServerErrorError, unknown> = z
    .object({
      code: types.string(),
      message: types.string(),
      docs: types.optional(types.string()),
      details: types.optional(
        smartUnion([types.string(), z.array(types.string())]),
      ),
    });

export function findLinkedInConversationInternalServerErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<
  FindLinkedInConversationInternalServerErrorError,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      FindLinkedInConversationInternalServerErrorError$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'FindLinkedInConversationInternalServerErrorError' from JSON`,
  );
}

/** @internal */
export const FindLinkedInConversationCode$inboundSchema: z.ZodMiniEnum<
  typeof FindLinkedInConversationCode
> = z.enum(FindLinkedInConversationCode);

/** @internal */
export const FindLinkedInConversationDaily$inboundSchema: z.ZodMiniType<
  FindLinkedInConversationDaily,
  unknown
> = z.object({
  current: types.number(),
  limit: types.number(),
});

export function findLinkedInConversationDailyFromJSON(
  jsonString: string,
): SafeParseResult<FindLinkedInConversationDaily, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FindLinkedInConversationDaily$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FindLinkedInConversationDaily' from JSON`,
  );
}

/** @internal */
export const FindLinkedInConversationWeekly$inboundSchema: z.ZodMiniType<
  FindLinkedInConversationWeekly,
  unknown
> = z.object({
  current: types.number(),
  limit: types.number(),
});

export function findLinkedInConversationWeeklyFromJSON(
  jsonString: string,
): SafeParseResult<FindLinkedInConversationWeekly, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FindLinkedInConversationWeekly$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FindLinkedInConversationWeekly' from JSON`,
  );
}

/** @internal */
export const FindLinkedInConversationTooManyRequestsError$inboundSchema:
  z.ZodMiniType<FindLinkedInConversationTooManyRequestsError, unknown> = z
    .object({
      code: FindLinkedInConversationCode$inboundSchema,
      message: types.string(),
      docs: types.optional(types.string()),
      retryAfter: types.number(),
      daily: types.nullable(
        z.lazy(() => FindLinkedInConversationDaily$inboundSchema),
      ),
      weekly: types.nullable(
        z.lazy(() => FindLinkedInConversationWeekly$inboundSchema),
      ),
    });

export function findLinkedInConversationTooManyRequestsErrorFromJSON(
  jsonString: string,
): SafeParseResult<
  FindLinkedInConversationTooManyRequestsError,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      FindLinkedInConversationTooManyRequestsError$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'FindLinkedInConversationTooManyRequestsError' from JSON`,
  );
}

/** @internal */
export const FindLinkedInConversationUnprocessableEntityDetails$inboundSchema:
  z.ZodMiniType<FindLinkedInConversationUnprocessableEntityDetails, unknown> =
    smartUnion([types.string(), z.array(types.string())]);

export function findLinkedInConversationUnprocessableEntityDetailsFromJSON(
  jsonString: string,
): SafeParseResult<
  FindLinkedInConversationUnprocessableEntityDetails,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      FindLinkedInConversationUnprocessableEntityDetails$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'FindLinkedInConversationUnprocessableEntityDetails' from JSON`,
  );
}

/** @internal */
export const FindLinkedInConversationUnprocessableEntityError$inboundSchema:
  z.ZodMiniType<FindLinkedInConversationUnprocessableEntityError, unknown> = z
    .object({
      code: types.string(),
      message: types.string(),
      docs: types.optional(types.string()),
      details: types.optional(
        smartUnion([types.string(), z.array(types.string())]),
      ),
    });

export function findLinkedInConversationUnprocessableEntityErrorFromJSON(
  jsonString: string,
): SafeParseResult<
  FindLinkedInConversationUnprocessableEntityError,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      FindLinkedInConversationUnprocessableEntityError$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'FindLinkedInConversationUnprocessableEntityError' from JSON`,
  );
}

/** @internal */
export const FindLinkedInConversationGoneDetails$inboundSchema: z.ZodMiniType<
  FindLinkedInConversationGoneDetails,
  unknown
> = smartUnion([types.string(), z.array(types.string())]);

export function findLinkedInConversationGoneDetailsFromJSON(
  jsonString: string,
): SafeParseResult<FindLinkedInConversationGoneDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      FindLinkedInConversationGoneDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FindLinkedInConversationGoneDetails' from JSON`,
  );
}

/** @internal */
export const FindLinkedInConversationGoneError$inboundSchema: z.ZodMiniType<
  FindLinkedInConversationGoneError,
  unknown
> = z.object({
  code: types.string(),
  message: types.string(),
  docs: types.optional(types.string()),
  details: types.optional(
    smartUnion([types.string(), z.array(types.string())]),
  ),
});

export function findLinkedInConversationGoneErrorFromJSON(
  jsonString: string,
): SafeParseResult<FindLinkedInConversationGoneError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FindLinkedInConversationGoneError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FindLinkedInConversationGoneError' from JSON`,
  );
}

/** @internal */
export const FindLinkedInConversationConflictDetails$inboundSchema:
  z.ZodMiniType<FindLinkedInConversationConflictDetails, unknown> = smartUnion([
    types.string(),
    z.array(types.string()),
  ]);

export function findLinkedInConversationConflictDetailsFromJSON(
  jsonString: string,
): SafeParseResult<
  FindLinkedInConversationConflictDetails,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      FindLinkedInConversationConflictDetails$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'FindLinkedInConversationConflictDetails' from JSON`,
  );
}

/** @internal */
export const FindLinkedInConversationConflictError$inboundSchema: z.ZodMiniType<
  FindLinkedInConversationConflictError,
  unknown
> = z.object({
  code: types.string(),
  message: types.string(),
  docs: types.optional(types.string()),
  details: types.optional(
    smartUnion([types.string(), z.array(types.string())]),
  ),
});

export function findLinkedInConversationConflictErrorFromJSON(
  jsonString: string,
): SafeParseResult<FindLinkedInConversationConflictError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      FindLinkedInConversationConflictError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FindLinkedInConversationConflictError' from JSON`,
  );
}

/** @internal */
export const FindLinkedInConversationNotFoundDetails$inboundSchema:
  z.ZodMiniType<FindLinkedInConversationNotFoundDetails, unknown> = smartUnion([
    types.string(),
    z.array(types.string()),
  ]);

export function findLinkedInConversationNotFoundDetailsFromJSON(
  jsonString: string,
): SafeParseResult<
  FindLinkedInConversationNotFoundDetails,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      FindLinkedInConversationNotFoundDetails$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'FindLinkedInConversationNotFoundDetails' from JSON`,
  );
}

/** @internal */
export const FindLinkedInConversationNotFoundError$inboundSchema: z.ZodMiniType<
  FindLinkedInConversationNotFoundError,
  unknown
> = z.object({
  code: types.string(),
  message: types.string(),
  docs: types.optional(types.string()),
  details: types.optional(
    smartUnion([types.string(), z.array(types.string())]),
  ),
});

export function findLinkedInConversationNotFoundErrorFromJSON(
  jsonString: string,
): SafeParseResult<FindLinkedInConversationNotFoundError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      FindLinkedInConversationNotFoundError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FindLinkedInConversationNotFoundError' from JSON`,
  );
}

/** @internal */
export const FindLinkedInConversationForbiddenDetails$inboundSchema:
  z.ZodMiniType<FindLinkedInConversationForbiddenDetails, unknown> = smartUnion(
    [types.string(), z.array(types.string())],
  );

export function findLinkedInConversationForbiddenDetailsFromJSON(
  jsonString: string,
): SafeParseResult<
  FindLinkedInConversationForbiddenDetails,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      FindLinkedInConversationForbiddenDetails$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'FindLinkedInConversationForbiddenDetails' from JSON`,
  );
}

/** @internal */
export const FindLinkedInConversationForbiddenError$inboundSchema:
  z.ZodMiniType<FindLinkedInConversationForbiddenError, unknown> = z.object({
    code: types.string(),
    message: types.string(),
    docs: types.optional(types.string()),
    details: types.optional(
      smartUnion([types.string(), z.array(types.string())]),
    ),
  });

export function findLinkedInConversationForbiddenErrorFromJSON(
  jsonString: string,
): SafeParseResult<FindLinkedInConversationForbiddenError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      FindLinkedInConversationForbiddenError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FindLinkedInConversationForbiddenError' from JSON`,
  );
}

/** @internal */
export const FindLinkedInConversationUnauthorizedDetails$inboundSchema:
  z.ZodMiniType<FindLinkedInConversationUnauthorizedDetails, unknown> =
    smartUnion([types.string(), z.array(types.string())]);

export function findLinkedInConversationUnauthorizedDetailsFromJSON(
  jsonString: string,
): SafeParseResult<
  FindLinkedInConversationUnauthorizedDetails,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      FindLinkedInConversationUnauthorizedDetails$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'FindLinkedInConversationUnauthorizedDetails' from JSON`,
  );
}

/** @internal */
export const FindLinkedInConversationUnauthorizedError$inboundSchema:
  z.ZodMiniType<FindLinkedInConversationUnauthorizedError, unknown> = z.object({
    code: types.string(),
    message: types.string(),
    docs: types.optional(types.string()),
    details: types.optional(
      smartUnion([types.string(), z.array(types.string())]),
    ),
  });

export function findLinkedInConversationUnauthorizedErrorFromJSON(
  jsonString: string,
): SafeParseResult<
  FindLinkedInConversationUnauthorizedError,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      FindLinkedInConversationUnauthorizedError$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'FindLinkedInConversationUnauthorizedError' from JSON`,
  );
}

/** @internal */
export const FindLinkedInConversationBadRequestDetails$inboundSchema:
  z.ZodMiniType<FindLinkedInConversationBadRequestDetails, unknown> =
    smartUnion([types.string(), z.array(types.string())]);

export function findLinkedInConversationBadRequestDetailsFromJSON(
  jsonString: string,
): SafeParseResult<
  FindLinkedInConversationBadRequestDetails,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      FindLinkedInConversationBadRequestDetails$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'FindLinkedInConversationBadRequestDetails' from JSON`,
  );
}

/** @internal */
export const FindLinkedInConversationBadRequestError$inboundSchema:
  z.ZodMiniType<FindLinkedInConversationBadRequestError, unknown> = z.object({
    code: types.string(),
    message: types.string(),
    docs: types.optional(types.string()),
    details: types.optional(
      smartUnion([types.string(), z.array(types.string())]),
    ),
  });

export function findLinkedInConversationBadRequestErrorFromJSON(
  jsonString: string,
): SafeParseResult<
  FindLinkedInConversationBadRequestError,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      FindLinkedInConversationBadRequestError$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'FindLinkedInConversationBadRequestError' from JSON`,
  );
}

/** @internal */
export const FindLinkedInConversationConversation$inboundSchema: z.ZodMiniType<
  FindLinkedInConversationConversation,
  unknown
> = z.object({
  conversationUrn: types.string(),
});

export function findLinkedInConversationConversationFromJSON(
  jsonString: string,
): SafeParseResult<FindLinkedInConversationConversation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      FindLinkedInConversationConversation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FindLinkedInConversationConversation' from JSON`,
  );
}

/** @internal */
export const FindLinkedInConversationSender$inboundSchema: z.ZodMiniType<
  FindLinkedInConversationSender,
  unknown
> = z.object({
  firstName: types.string(),
  lastName: types.string(),
  profileUrl: types.nullable(types.string()),
  headline: types.nullable(types.string()),
  profilePicture: types.nullable(types.string()),
});

export function findLinkedInConversationSenderFromJSON(
  jsonString: string,
): SafeParseResult<FindLinkedInConversationSender, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FindLinkedInConversationSender$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FindLinkedInConversationSender' from JSON`,
  );
}

/** @internal */
export const FindLinkedInConversationType$inboundSchema: z.ZodMiniType<
  FindLinkedInConversationType,
  unknown
> = openEnums.inboundSchema(FindLinkedInConversationType);

/** @internal */
export const FindLinkedInConversationAttachment$inboundSchema: z.ZodMiniType<
  FindLinkedInConversationAttachment,
  unknown
> = z.object({
  type: FindLinkedInConversationType$inboundSchema,
  audioUrl: types.optional(types.string()),
  audioDuration: types.optional(types.number()),
  hostUrn: types.optional(types.string()),
  repliedText: types.optional(types.string()),
  repliedSenderName: types.optional(types.string()),
  imageUrl: types.optional(types.string()),
  fileName: types.optional(types.string()),
  fileUrl: types.optional(types.string()),
});

export function findLinkedInConversationAttachmentFromJSON(
  jsonString: string,
): SafeParseResult<FindLinkedInConversationAttachment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      FindLinkedInConversationAttachment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FindLinkedInConversationAttachment' from JSON`,
  );
}

/** @internal */
export const FindLinkedInConversationMessage$inboundSchema: z.ZodMiniType<
  FindLinkedInConversationMessage,
  unknown
> = z.object({
  messageUrn: types.string(),
  text: types.nullable(types.string()),
  deliveredAt: types.number(),
  senderProfileUrn: types.string(),
  sender: z.lazy(() => FindLinkedInConversationSender$inboundSchema),
  attachments: z.array(
    z.lazy(() => FindLinkedInConversationAttachment$inboundSchema),
  ),
});

export function findLinkedInConversationMessageFromJSON(
  jsonString: string,
): SafeParseResult<FindLinkedInConversationMessage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FindLinkedInConversationMessage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FindLinkedInConversationMessage' from JSON`,
  );
}

/** @internal */
export const FindLinkedInConversationResponse$inboundSchema: z.ZodMiniType<
  FindLinkedInConversationResponse,
  unknown
> = z.object({
  success: types.literal(true),
  found: types.boolean(),
  conversation: types.nullable(
    z.lazy(() => FindLinkedInConversationConversation$inboundSchema),
  ),
  messages: types.nullable(
    z.array(z.lazy(() => FindLinkedInConversationMessage$inboundSchema)),
  ),
  creditsUsed: types.number(),
  retryAfter: types.number(),
});

export function findLinkedInConversationResponseFromJSON(
  jsonString: string,
): SafeParseResult<FindLinkedInConversationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FindLinkedInConversationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FindLinkedInConversationResponse' from JSON`,
  );
}
