/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type FollowLinkedInCompanyRequest = {
  /**
   * LinkedIn company URL or URN
   */
  company: string;
};

export type FollowLinkedInCompanyInternalServerErrorDetails =
  | string
  | Array<string>;

export type FollowLinkedInCompanyInternalServerErrorError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const FollowLinkedInCompanyCode = {
  RateLimitExceeded: "rate_limit_exceeded",
} as const;
export type FollowLinkedInCompanyCode = ClosedEnum<
  typeof FollowLinkedInCompanyCode
>;

/**
 * Current and max daily usage (null if no daily cap).
 */
export type FollowLinkedInCompanyDaily = {
  current: number;
  limit: number;
};

/**
 * Current and max weekly usage (null if no weekly cap).
 */
export type FollowLinkedInCompanyWeekly = {
  current: number;
  limit: number;
};

export type FollowLinkedInCompanyTooManyRequestsError = {
  code: FollowLinkedInCompanyCode;
  message: string;
  docs?: string | undefined;
  /**
   * Seconds to wait before retrying.
   */
  retryAfter: number;
  /**
   * Current and max daily usage (null if no daily cap).
   */
  daily: FollowLinkedInCompanyDaily | null;
  /**
   * Current and max weekly usage (null if no weekly cap).
   */
  weekly: FollowLinkedInCompanyWeekly | null;
};

export type FollowLinkedInCompanyUnprocessableEntityDetails =
  | string
  | Array<string>;

export type FollowLinkedInCompanyUnprocessableEntityError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export type FollowLinkedInCompanyGoneDetails = string | Array<string>;

export type FollowLinkedInCompanyGoneError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export type FollowLinkedInCompanyConflictDetails = string | Array<string>;

export type FollowLinkedInCompanyConflictError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export type FollowLinkedInCompanyNotFoundDetails = string | Array<string>;

export type FollowLinkedInCompanyNotFoundError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export type FollowLinkedInCompanyForbiddenDetails = string | Array<string>;

export type FollowLinkedInCompanyForbiddenError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export type FollowLinkedInCompanyUnauthorizedDetails = string | Array<string>;

export type FollowLinkedInCompanyUnauthorizedError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export type FollowLinkedInCompanyBadRequestDetails = string | Array<string>;

export type FollowLinkedInCompanyBadRequestError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

/**
 * Company followed
 */
export type FollowLinkedInCompanyResponse = {
  success: true;
  /**
   * Credits consumed by this call (0 for free endpoints, cached results, or duplicates).
   */
  creditsUsed: number;
  /**
   * Seconds to wait before making another call of the same type. 0 means no wait needed.
   */
  retryAfter: number;
};

/** @internal */
export type FollowLinkedInCompanyRequest$Outbound = {
  company: string;
};

/** @internal */
export const FollowLinkedInCompanyRequest$outboundSchema: z.ZodMiniType<
  FollowLinkedInCompanyRequest$Outbound,
  FollowLinkedInCompanyRequest
> = z.object({
  company: z.string(),
});

export function followLinkedInCompanyRequestToJSON(
  followLinkedInCompanyRequest: FollowLinkedInCompanyRequest,
): string {
  return JSON.stringify(
    FollowLinkedInCompanyRequest$outboundSchema.parse(
      followLinkedInCompanyRequest,
    ),
  );
}

/** @internal */
export const FollowLinkedInCompanyInternalServerErrorDetails$inboundSchema:
  z.ZodMiniType<FollowLinkedInCompanyInternalServerErrorDetails, unknown> =
    smartUnion([types.string(), z.array(types.string())]);

export function followLinkedInCompanyInternalServerErrorDetailsFromJSON(
  jsonString: string,
): SafeParseResult<
  FollowLinkedInCompanyInternalServerErrorDetails,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      FollowLinkedInCompanyInternalServerErrorDetails$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'FollowLinkedInCompanyInternalServerErrorDetails' from JSON`,
  );
}

/** @internal */
export const FollowLinkedInCompanyInternalServerErrorError$inboundSchema:
  z.ZodMiniType<FollowLinkedInCompanyInternalServerErrorError, unknown> = z
    .object({
      code: types.string(),
      message: types.string(),
      docs: types.optional(types.string()),
      details: types.optional(
        smartUnion([types.string(), z.array(types.string())]),
      ),
    });

export function followLinkedInCompanyInternalServerErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<
  FollowLinkedInCompanyInternalServerErrorError,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      FollowLinkedInCompanyInternalServerErrorError$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'FollowLinkedInCompanyInternalServerErrorError' from JSON`,
  );
}

/** @internal */
export const FollowLinkedInCompanyCode$inboundSchema: z.ZodMiniEnum<
  typeof FollowLinkedInCompanyCode
> = z.enum(FollowLinkedInCompanyCode);

/** @internal */
export const FollowLinkedInCompanyDaily$inboundSchema: z.ZodMiniType<
  FollowLinkedInCompanyDaily,
  unknown
> = z.object({
  current: types.number(),
  limit: types.number(),
});

export function followLinkedInCompanyDailyFromJSON(
  jsonString: string,
): SafeParseResult<FollowLinkedInCompanyDaily, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FollowLinkedInCompanyDaily$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FollowLinkedInCompanyDaily' from JSON`,
  );
}

/** @internal */
export const FollowLinkedInCompanyWeekly$inboundSchema: z.ZodMiniType<
  FollowLinkedInCompanyWeekly,
  unknown
> = z.object({
  current: types.number(),
  limit: types.number(),
});

export function followLinkedInCompanyWeeklyFromJSON(
  jsonString: string,
): SafeParseResult<FollowLinkedInCompanyWeekly, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FollowLinkedInCompanyWeekly$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FollowLinkedInCompanyWeekly' from JSON`,
  );
}

/** @internal */
export const FollowLinkedInCompanyTooManyRequestsError$inboundSchema:
  z.ZodMiniType<FollowLinkedInCompanyTooManyRequestsError, unknown> = z.object({
    code: FollowLinkedInCompanyCode$inboundSchema,
    message: types.string(),
    docs: types.optional(types.string()),
    retryAfter: types.number(),
    daily: types.nullable(
      z.lazy(() => FollowLinkedInCompanyDaily$inboundSchema),
    ),
    weekly: types.nullable(
      z.lazy(() => FollowLinkedInCompanyWeekly$inboundSchema),
    ),
  });

export function followLinkedInCompanyTooManyRequestsErrorFromJSON(
  jsonString: string,
): SafeParseResult<
  FollowLinkedInCompanyTooManyRequestsError,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      FollowLinkedInCompanyTooManyRequestsError$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'FollowLinkedInCompanyTooManyRequestsError' from JSON`,
  );
}

/** @internal */
export const FollowLinkedInCompanyUnprocessableEntityDetails$inboundSchema:
  z.ZodMiniType<FollowLinkedInCompanyUnprocessableEntityDetails, unknown> =
    smartUnion([types.string(), z.array(types.string())]);

export function followLinkedInCompanyUnprocessableEntityDetailsFromJSON(
  jsonString: string,
): SafeParseResult<
  FollowLinkedInCompanyUnprocessableEntityDetails,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      FollowLinkedInCompanyUnprocessableEntityDetails$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'FollowLinkedInCompanyUnprocessableEntityDetails' from JSON`,
  );
}

/** @internal */
export const FollowLinkedInCompanyUnprocessableEntityError$inboundSchema:
  z.ZodMiniType<FollowLinkedInCompanyUnprocessableEntityError, unknown> = z
    .object({
      code: types.string(),
      message: types.string(),
      docs: types.optional(types.string()),
      details: types.optional(
        smartUnion([types.string(), z.array(types.string())]),
      ),
    });

export function followLinkedInCompanyUnprocessableEntityErrorFromJSON(
  jsonString: string,
): SafeParseResult<
  FollowLinkedInCompanyUnprocessableEntityError,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      FollowLinkedInCompanyUnprocessableEntityError$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'FollowLinkedInCompanyUnprocessableEntityError' from JSON`,
  );
}

/** @internal */
export const FollowLinkedInCompanyGoneDetails$inboundSchema: z.ZodMiniType<
  FollowLinkedInCompanyGoneDetails,
  unknown
> = smartUnion([types.string(), z.array(types.string())]);

export function followLinkedInCompanyGoneDetailsFromJSON(
  jsonString: string,
): SafeParseResult<FollowLinkedInCompanyGoneDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FollowLinkedInCompanyGoneDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FollowLinkedInCompanyGoneDetails' from JSON`,
  );
}

/** @internal */
export const FollowLinkedInCompanyGoneError$inboundSchema: z.ZodMiniType<
  FollowLinkedInCompanyGoneError,
  unknown
> = z.object({
  code: types.string(),
  message: types.string(),
  docs: types.optional(types.string()),
  details: types.optional(
    smartUnion([types.string(), z.array(types.string())]),
  ),
});

export function followLinkedInCompanyGoneErrorFromJSON(
  jsonString: string,
): SafeParseResult<FollowLinkedInCompanyGoneError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FollowLinkedInCompanyGoneError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FollowLinkedInCompanyGoneError' from JSON`,
  );
}

/** @internal */
export const FollowLinkedInCompanyConflictDetails$inboundSchema: z.ZodMiniType<
  FollowLinkedInCompanyConflictDetails,
  unknown
> = smartUnion([types.string(), z.array(types.string())]);

export function followLinkedInCompanyConflictDetailsFromJSON(
  jsonString: string,
): SafeParseResult<FollowLinkedInCompanyConflictDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      FollowLinkedInCompanyConflictDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FollowLinkedInCompanyConflictDetails' from JSON`,
  );
}

/** @internal */
export const FollowLinkedInCompanyConflictError$inboundSchema: z.ZodMiniType<
  FollowLinkedInCompanyConflictError,
  unknown
> = z.object({
  code: types.string(),
  message: types.string(),
  docs: types.optional(types.string()),
  details: types.optional(
    smartUnion([types.string(), z.array(types.string())]),
  ),
});

export function followLinkedInCompanyConflictErrorFromJSON(
  jsonString: string,
): SafeParseResult<FollowLinkedInCompanyConflictError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      FollowLinkedInCompanyConflictError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FollowLinkedInCompanyConflictError' from JSON`,
  );
}

/** @internal */
export const FollowLinkedInCompanyNotFoundDetails$inboundSchema: z.ZodMiniType<
  FollowLinkedInCompanyNotFoundDetails,
  unknown
> = smartUnion([types.string(), z.array(types.string())]);

export function followLinkedInCompanyNotFoundDetailsFromJSON(
  jsonString: string,
): SafeParseResult<FollowLinkedInCompanyNotFoundDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      FollowLinkedInCompanyNotFoundDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FollowLinkedInCompanyNotFoundDetails' from JSON`,
  );
}

/** @internal */
export const FollowLinkedInCompanyNotFoundError$inboundSchema: z.ZodMiniType<
  FollowLinkedInCompanyNotFoundError,
  unknown
> = z.object({
  code: types.string(),
  message: types.string(),
  docs: types.optional(types.string()),
  details: types.optional(
    smartUnion([types.string(), z.array(types.string())]),
  ),
});

export function followLinkedInCompanyNotFoundErrorFromJSON(
  jsonString: string,
): SafeParseResult<FollowLinkedInCompanyNotFoundError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      FollowLinkedInCompanyNotFoundError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FollowLinkedInCompanyNotFoundError' from JSON`,
  );
}

/** @internal */
export const FollowLinkedInCompanyForbiddenDetails$inboundSchema: z.ZodMiniType<
  FollowLinkedInCompanyForbiddenDetails,
  unknown
> = smartUnion([types.string(), z.array(types.string())]);

export function followLinkedInCompanyForbiddenDetailsFromJSON(
  jsonString: string,
): SafeParseResult<FollowLinkedInCompanyForbiddenDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      FollowLinkedInCompanyForbiddenDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FollowLinkedInCompanyForbiddenDetails' from JSON`,
  );
}

/** @internal */
export const FollowLinkedInCompanyForbiddenError$inboundSchema: z.ZodMiniType<
  FollowLinkedInCompanyForbiddenError,
  unknown
> = z.object({
  code: types.string(),
  message: types.string(),
  docs: types.optional(types.string()),
  details: types.optional(
    smartUnion([types.string(), z.array(types.string())]),
  ),
});

export function followLinkedInCompanyForbiddenErrorFromJSON(
  jsonString: string,
): SafeParseResult<FollowLinkedInCompanyForbiddenError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      FollowLinkedInCompanyForbiddenError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FollowLinkedInCompanyForbiddenError' from JSON`,
  );
}

/** @internal */
export const FollowLinkedInCompanyUnauthorizedDetails$inboundSchema:
  z.ZodMiniType<FollowLinkedInCompanyUnauthorizedDetails, unknown> = smartUnion(
    [types.string(), z.array(types.string())],
  );

export function followLinkedInCompanyUnauthorizedDetailsFromJSON(
  jsonString: string,
): SafeParseResult<
  FollowLinkedInCompanyUnauthorizedDetails,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      FollowLinkedInCompanyUnauthorizedDetails$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'FollowLinkedInCompanyUnauthorizedDetails' from JSON`,
  );
}

/** @internal */
export const FollowLinkedInCompanyUnauthorizedError$inboundSchema:
  z.ZodMiniType<FollowLinkedInCompanyUnauthorizedError, unknown> = z.object({
    code: types.string(),
    message: types.string(),
    docs: types.optional(types.string()),
    details: types.optional(
      smartUnion([types.string(), z.array(types.string())]),
    ),
  });

export function followLinkedInCompanyUnauthorizedErrorFromJSON(
  jsonString: string,
): SafeParseResult<FollowLinkedInCompanyUnauthorizedError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      FollowLinkedInCompanyUnauthorizedError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FollowLinkedInCompanyUnauthorizedError' from JSON`,
  );
}

/** @internal */
export const FollowLinkedInCompanyBadRequestDetails$inboundSchema:
  z.ZodMiniType<FollowLinkedInCompanyBadRequestDetails, unknown> = smartUnion([
    types.string(),
    z.array(types.string()),
  ]);

export function followLinkedInCompanyBadRequestDetailsFromJSON(
  jsonString: string,
): SafeParseResult<FollowLinkedInCompanyBadRequestDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      FollowLinkedInCompanyBadRequestDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FollowLinkedInCompanyBadRequestDetails' from JSON`,
  );
}

/** @internal */
export const FollowLinkedInCompanyBadRequestError$inboundSchema: z.ZodMiniType<
  FollowLinkedInCompanyBadRequestError,
  unknown
> = z.object({
  code: types.string(),
  message: types.string(),
  docs: types.optional(types.string()),
  details: types.optional(
    smartUnion([types.string(), z.array(types.string())]),
  ),
});

export function followLinkedInCompanyBadRequestErrorFromJSON(
  jsonString: string,
): SafeParseResult<FollowLinkedInCompanyBadRequestError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      FollowLinkedInCompanyBadRequestError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FollowLinkedInCompanyBadRequestError' from JSON`,
  );
}

/** @internal */
export const FollowLinkedInCompanyResponse$inboundSchema: z.ZodMiniType<
  FollowLinkedInCompanyResponse,
  unknown
> = z.object({
  success: types.literal(true),
  creditsUsed: types.number(),
  retryAfter: types.number(),
});

export function followLinkedInCompanyResponseFromJSON(
  jsonString: string,
): SafeParseResult<FollowLinkedInCompanyResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FollowLinkedInCompanyResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FollowLinkedInCompanyResponse' from JSON`,
  );
}
