/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type ListLinkedInAccountsInternalServerErrorDetails =
  | string
  | Array<string>;

export type ListLinkedInAccountsInternalServerErrorError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const ListLinkedInAccountsCode = {
  RateLimitExceeded: "rate_limit_exceeded",
} as const;
export type ListLinkedInAccountsCode = ClosedEnum<
  typeof ListLinkedInAccountsCode
>;

/**
 * Current and max daily usage (null if no daily cap).
 */
export type ListLinkedInAccountsDaily = {
  current: number;
  limit: number;
};

/**
 * Current and max weekly usage (null if no weekly cap).
 */
export type ListLinkedInAccountsWeekly = {
  current: number;
  limit: number;
};

export type ListLinkedInAccountsTooManyRequestsError = {
  code: ListLinkedInAccountsCode;
  message: string;
  docs?: string | undefined;
  /**
   * Seconds to wait before retrying.
   */
  retryAfter: number;
  /**
   * Current and max daily usage (null if no daily cap).
   */
  daily: ListLinkedInAccountsDaily | null;
  /**
   * Current and max weekly usage (null if no weekly cap).
   */
  weekly: ListLinkedInAccountsWeekly | null;
};

export type ListLinkedInAccountsUnprocessableEntityDetails =
  | string
  | Array<string>;

export type ListLinkedInAccountsUnprocessableEntityError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export type ListLinkedInAccountsGoneDetails = string | Array<string>;

export type ListLinkedInAccountsGoneError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export type ListLinkedInAccountsConflictDetails = string | Array<string>;

export type ListLinkedInAccountsConflictError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export type ListLinkedInAccountsNotFoundDetails = string | Array<string>;

export type ListLinkedInAccountsNotFoundError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export type ListLinkedInAccountsForbiddenDetails = string | Array<string>;

export type ListLinkedInAccountsForbiddenError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export type ListLinkedInAccountsUnauthorizedDetails = string | Array<string>;

export type ListLinkedInAccountsUnauthorizedError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export type ListLinkedInAccountsBadRequestDetails = string | Array<string>;

export type ListLinkedInAccountsBadRequestError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export type ListLinkedInAccountsAccount = {
  id: string;
  label: string | null;
  isDefault: boolean;
  /**
   * Whether this account is the one used by the current API token.
   */
  isCurrent: boolean;
  linkedinProfileId: string | null;
  linkedinName: string | null;
  linkedinEmail: string | null;
  profileUrl: string | null;
  headline: string | null;
  profilePic: string | null;
  profileUrn: string | null;
  isActive: boolean;
  isValid: boolean;
  createdAt: string;
  updatedAt: string;
};

/**
 * List of LinkedIn accounts
 */
export type ListLinkedInAccountsResponse = {
  success: true;
  accounts: Array<ListLinkedInAccountsAccount>;
  total: number;
};

/** @internal */
export const ListLinkedInAccountsInternalServerErrorDetails$inboundSchema:
  z.ZodMiniType<ListLinkedInAccountsInternalServerErrorDetails, unknown> =
    smartUnion([types.string(), z.array(types.string())]);

export function listLinkedInAccountsInternalServerErrorDetailsFromJSON(
  jsonString: string,
): SafeParseResult<
  ListLinkedInAccountsInternalServerErrorDetails,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListLinkedInAccountsInternalServerErrorDetails$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ListLinkedInAccountsInternalServerErrorDetails' from JSON`,
  );
}

/** @internal */
export const ListLinkedInAccountsInternalServerErrorError$inboundSchema:
  z.ZodMiniType<ListLinkedInAccountsInternalServerErrorError, unknown> = z
    .object({
      code: types.string(),
      message: types.string(),
      docs: types.optional(types.string()),
      details: types.optional(
        smartUnion([types.string(), z.array(types.string())]),
      ),
    });

export function listLinkedInAccountsInternalServerErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<
  ListLinkedInAccountsInternalServerErrorError,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListLinkedInAccountsInternalServerErrorError$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ListLinkedInAccountsInternalServerErrorError' from JSON`,
  );
}

/** @internal */
export const ListLinkedInAccountsCode$inboundSchema: z.ZodMiniEnum<
  typeof ListLinkedInAccountsCode
> = z.enum(ListLinkedInAccountsCode);

/** @internal */
export const ListLinkedInAccountsDaily$inboundSchema: z.ZodMiniType<
  ListLinkedInAccountsDaily,
  unknown
> = z.object({
  current: types.number(),
  limit: types.number(),
});

export function listLinkedInAccountsDailyFromJSON(
  jsonString: string,
): SafeParseResult<ListLinkedInAccountsDaily, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListLinkedInAccountsDaily$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListLinkedInAccountsDaily' from JSON`,
  );
}

/** @internal */
export const ListLinkedInAccountsWeekly$inboundSchema: z.ZodMiniType<
  ListLinkedInAccountsWeekly,
  unknown
> = z.object({
  current: types.number(),
  limit: types.number(),
});

export function listLinkedInAccountsWeeklyFromJSON(
  jsonString: string,
): SafeParseResult<ListLinkedInAccountsWeekly, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListLinkedInAccountsWeekly$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListLinkedInAccountsWeekly' from JSON`,
  );
}

/** @internal */
export const ListLinkedInAccountsTooManyRequestsError$inboundSchema:
  z.ZodMiniType<ListLinkedInAccountsTooManyRequestsError, unknown> = z.object({
    code: ListLinkedInAccountsCode$inboundSchema,
    message: types.string(),
    docs: types.optional(types.string()),
    retryAfter: types.number(),
    daily: types.nullable(
      z.lazy(() => ListLinkedInAccountsDaily$inboundSchema),
    ),
    weekly: types.nullable(
      z.lazy(() => ListLinkedInAccountsWeekly$inboundSchema),
    ),
  });

export function listLinkedInAccountsTooManyRequestsErrorFromJSON(
  jsonString: string,
): SafeParseResult<
  ListLinkedInAccountsTooManyRequestsError,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListLinkedInAccountsTooManyRequestsError$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ListLinkedInAccountsTooManyRequestsError' from JSON`,
  );
}

/** @internal */
export const ListLinkedInAccountsUnprocessableEntityDetails$inboundSchema:
  z.ZodMiniType<ListLinkedInAccountsUnprocessableEntityDetails, unknown> =
    smartUnion([types.string(), z.array(types.string())]);

export function listLinkedInAccountsUnprocessableEntityDetailsFromJSON(
  jsonString: string,
): SafeParseResult<
  ListLinkedInAccountsUnprocessableEntityDetails,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListLinkedInAccountsUnprocessableEntityDetails$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ListLinkedInAccountsUnprocessableEntityDetails' from JSON`,
  );
}

/** @internal */
export const ListLinkedInAccountsUnprocessableEntityError$inboundSchema:
  z.ZodMiniType<ListLinkedInAccountsUnprocessableEntityError, unknown> = z
    .object({
      code: types.string(),
      message: types.string(),
      docs: types.optional(types.string()),
      details: types.optional(
        smartUnion([types.string(), z.array(types.string())]),
      ),
    });

export function listLinkedInAccountsUnprocessableEntityErrorFromJSON(
  jsonString: string,
): SafeParseResult<
  ListLinkedInAccountsUnprocessableEntityError,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListLinkedInAccountsUnprocessableEntityError$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ListLinkedInAccountsUnprocessableEntityError' from JSON`,
  );
}

/** @internal */
export const ListLinkedInAccountsGoneDetails$inboundSchema: z.ZodMiniType<
  ListLinkedInAccountsGoneDetails,
  unknown
> = smartUnion([types.string(), z.array(types.string())]);

export function listLinkedInAccountsGoneDetailsFromJSON(
  jsonString: string,
): SafeParseResult<ListLinkedInAccountsGoneDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListLinkedInAccountsGoneDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListLinkedInAccountsGoneDetails' from JSON`,
  );
}

/** @internal */
export const ListLinkedInAccountsGoneError$inboundSchema: z.ZodMiniType<
  ListLinkedInAccountsGoneError,
  unknown
> = z.object({
  code: types.string(),
  message: types.string(),
  docs: types.optional(types.string()),
  details: types.optional(
    smartUnion([types.string(), z.array(types.string())]),
  ),
});

export function listLinkedInAccountsGoneErrorFromJSON(
  jsonString: string,
): SafeParseResult<ListLinkedInAccountsGoneError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListLinkedInAccountsGoneError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListLinkedInAccountsGoneError' from JSON`,
  );
}

/** @internal */
export const ListLinkedInAccountsConflictDetails$inboundSchema: z.ZodMiniType<
  ListLinkedInAccountsConflictDetails,
  unknown
> = smartUnion([types.string(), z.array(types.string())]);

export function listLinkedInAccountsConflictDetailsFromJSON(
  jsonString: string,
): SafeParseResult<ListLinkedInAccountsConflictDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListLinkedInAccountsConflictDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListLinkedInAccountsConflictDetails' from JSON`,
  );
}

/** @internal */
export const ListLinkedInAccountsConflictError$inboundSchema: z.ZodMiniType<
  ListLinkedInAccountsConflictError,
  unknown
> = z.object({
  code: types.string(),
  message: types.string(),
  docs: types.optional(types.string()),
  details: types.optional(
    smartUnion([types.string(), z.array(types.string())]),
  ),
});

export function listLinkedInAccountsConflictErrorFromJSON(
  jsonString: string,
): SafeParseResult<ListLinkedInAccountsConflictError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListLinkedInAccountsConflictError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListLinkedInAccountsConflictError' from JSON`,
  );
}

/** @internal */
export const ListLinkedInAccountsNotFoundDetails$inboundSchema: z.ZodMiniType<
  ListLinkedInAccountsNotFoundDetails,
  unknown
> = smartUnion([types.string(), z.array(types.string())]);

export function listLinkedInAccountsNotFoundDetailsFromJSON(
  jsonString: string,
): SafeParseResult<ListLinkedInAccountsNotFoundDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListLinkedInAccountsNotFoundDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListLinkedInAccountsNotFoundDetails' from JSON`,
  );
}

/** @internal */
export const ListLinkedInAccountsNotFoundError$inboundSchema: z.ZodMiniType<
  ListLinkedInAccountsNotFoundError,
  unknown
> = z.object({
  code: types.string(),
  message: types.string(),
  docs: types.optional(types.string()),
  details: types.optional(
    smartUnion([types.string(), z.array(types.string())]),
  ),
});

export function listLinkedInAccountsNotFoundErrorFromJSON(
  jsonString: string,
): SafeParseResult<ListLinkedInAccountsNotFoundError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListLinkedInAccountsNotFoundError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListLinkedInAccountsNotFoundError' from JSON`,
  );
}

/** @internal */
export const ListLinkedInAccountsForbiddenDetails$inboundSchema: z.ZodMiniType<
  ListLinkedInAccountsForbiddenDetails,
  unknown
> = smartUnion([types.string(), z.array(types.string())]);

export function listLinkedInAccountsForbiddenDetailsFromJSON(
  jsonString: string,
): SafeParseResult<ListLinkedInAccountsForbiddenDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListLinkedInAccountsForbiddenDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListLinkedInAccountsForbiddenDetails' from JSON`,
  );
}

/** @internal */
export const ListLinkedInAccountsForbiddenError$inboundSchema: z.ZodMiniType<
  ListLinkedInAccountsForbiddenError,
  unknown
> = z.object({
  code: types.string(),
  message: types.string(),
  docs: types.optional(types.string()),
  details: types.optional(
    smartUnion([types.string(), z.array(types.string())]),
  ),
});

export function listLinkedInAccountsForbiddenErrorFromJSON(
  jsonString: string,
): SafeParseResult<ListLinkedInAccountsForbiddenError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListLinkedInAccountsForbiddenError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListLinkedInAccountsForbiddenError' from JSON`,
  );
}

/** @internal */
export const ListLinkedInAccountsUnauthorizedDetails$inboundSchema:
  z.ZodMiniType<ListLinkedInAccountsUnauthorizedDetails, unknown> = smartUnion([
    types.string(),
    z.array(types.string()),
  ]);

export function listLinkedInAccountsUnauthorizedDetailsFromJSON(
  jsonString: string,
): SafeParseResult<
  ListLinkedInAccountsUnauthorizedDetails,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListLinkedInAccountsUnauthorizedDetails$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ListLinkedInAccountsUnauthorizedDetails' from JSON`,
  );
}

/** @internal */
export const ListLinkedInAccountsUnauthorizedError$inboundSchema: z.ZodMiniType<
  ListLinkedInAccountsUnauthorizedError,
  unknown
> = z.object({
  code: types.string(),
  message: types.string(),
  docs: types.optional(types.string()),
  details: types.optional(
    smartUnion([types.string(), z.array(types.string())]),
  ),
});

export function listLinkedInAccountsUnauthorizedErrorFromJSON(
  jsonString: string,
): SafeParseResult<ListLinkedInAccountsUnauthorizedError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListLinkedInAccountsUnauthorizedError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListLinkedInAccountsUnauthorizedError' from JSON`,
  );
}

/** @internal */
export const ListLinkedInAccountsBadRequestDetails$inboundSchema: z.ZodMiniType<
  ListLinkedInAccountsBadRequestDetails,
  unknown
> = smartUnion([types.string(), z.array(types.string())]);

export function listLinkedInAccountsBadRequestDetailsFromJSON(
  jsonString: string,
): SafeParseResult<ListLinkedInAccountsBadRequestDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListLinkedInAccountsBadRequestDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListLinkedInAccountsBadRequestDetails' from JSON`,
  );
}

/** @internal */
export const ListLinkedInAccountsBadRequestError$inboundSchema: z.ZodMiniType<
  ListLinkedInAccountsBadRequestError,
  unknown
> = z.object({
  code: types.string(),
  message: types.string(),
  docs: types.optional(types.string()),
  details: types.optional(
    smartUnion([types.string(), z.array(types.string())]),
  ),
});

export function listLinkedInAccountsBadRequestErrorFromJSON(
  jsonString: string,
): SafeParseResult<ListLinkedInAccountsBadRequestError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListLinkedInAccountsBadRequestError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListLinkedInAccountsBadRequestError' from JSON`,
  );
}

/** @internal */
export const ListLinkedInAccountsAccount$inboundSchema: z.ZodMiniType<
  ListLinkedInAccountsAccount,
  unknown
> = z.object({
  id: types.string(),
  label: types.nullable(types.string()),
  isDefault: types.boolean(),
  isCurrent: types.boolean(),
  linkedinProfileId: types.nullable(types.string()),
  linkedinName: types.nullable(types.string()),
  linkedinEmail: types.nullable(types.string()),
  profileUrl: types.nullable(types.string()),
  headline: types.nullable(types.string()),
  profilePic: types.nullable(types.string()),
  profileUrn: types.nullable(types.string()),
  isActive: types.boolean(),
  isValid: types.boolean(),
  createdAt: types.string(),
  updatedAt: types.string(),
});

export function listLinkedInAccountsAccountFromJSON(
  jsonString: string,
): SafeParseResult<ListLinkedInAccountsAccount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListLinkedInAccountsAccount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListLinkedInAccountsAccount' from JSON`,
  );
}

/** @internal */
export const ListLinkedInAccountsResponse$inboundSchema: z.ZodMiniType<
  ListLinkedInAccountsResponse,
  unknown
> = z.object({
  success: types.literal(true),
  accounts: z.array(z.lazy(() => ListLinkedInAccountsAccount$inboundSchema)),
  total: types.number(),
});

export function listLinkedInAccountsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListLinkedInAccountsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListLinkedInAccountsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListLinkedInAccountsResponse' from JSON`,
  );
}
