/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type SearchLinkedInByUrlRequest = {
  /**
   * A LinkedIn search URL. The endpoint automatically extracts the category, keywords, and all filters from the URL. Example: 'https://www.linkedin.com/search/results/people/?keywords=engineer&network=%5B%22S%22%5D'
   */
  url: string;
  /**
   * Override pagination offset. If not provided, uses the page from the URL (or defaults to 0).
   */
  start?: number | undefined;
  /**
   * Override results per page (default 10, max 50).
   */
  count?: number | undefined;
};

export type SearchLinkedInByUrlInternalServerErrorDetails =
  | string
  | Array<string>;

export type SearchLinkedInByUrlInternalServerErrorError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const SearchLinkedInByUrlCode = {
  RateLimitExceeded: "rate_limit_exceeded",
} as const;
export type SearchLinkedInByUrlCode = ClosedEnum<
  typeof SearchLinkedInByUrlCode
>;

/**
 * Current and max daily usage (null if no daily cap).
 */
export type SearchLinkedInByUrlDaily = {
  current: number;
  limit: number;
};

/**
 * Current and max weekly usage (null if no weekly cap).
 */
export type SearchLinkedInByUrlWeekly = {
  current: number;
  limit: number;
};

export type SearchLinkedInByUrlTooManyRequestsError = {
  code: SearchLinkedInByUrlCode;
  message: string;
  docs?: string | undefined;
  /**
   * Seconds to wait before retrying.
   */
  retryAfter: number;
  /**
   * Current and max daily usage (null if no daily cap).
   */
  daily: SearchLinkedInByUrlDaily | null;
  /**
   * Current and max weekly usage (null if no weekly cap).
   */
  weekly: SearchLinkedInByUrlWeekly | null;
};

export type SearchLinkedInByUrlUnprocessableEntityDetails =
  | string
  | Array<string>;

export type SearchLinkedInByUrlUnprocessableEntityError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export type SearchLinkedInByUrlGoneDetails = string | Array<string>;

export type SearchLinkedInByUrlGoneError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export type SearchLinkedInByUrlConflictDetails = string | Array<string>;

export type SearchLinkedInByUrlConflictError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export type SearchLinkedInByUrlNotFoundDetails = string | Array<string>;

export type SearchLinkedInByUrlNotFoundError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export type SearchLinkedInByUrlForbiddenDetails = string | Array<string>;

export type SearchLinkedInByUrlForbiddenError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export type SearchLinkedInByUrlUnauthorizedDetails = string | Array<string>;

export type SearchLinkedInByUrlUnauthorizedError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export type SearchLinkedInByUrlBadRequestDetails = string | Array<string>;

export type SearchLinkedInByUrlBadRequestError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const SearchLinkedInByUrlCategory = {
  Posts: "posts",
  People: "people",
  Companies: "companies",
  Jobs: "jobs",
} as const;
export type SearchLinkedInByUrlCategory = OpenEnum<
  typeof SearchLinkedInByUrlCategory
>;

export const SearchLinkedInByUrlTypeJob = {
  Job: "JOB",
} as const;
export type SearchLinkedInByUrlTypeJob = ClosedEnum<
  typeof SearchLinkedInByUrlTypeJob
>;

export type SearchLinkedInByUrlItemsJob = {
  type: SearchLinkedInByUrlTypeJob;
  title: string;
  company: string | null;
  companyUrl: string | null;
  companyLogo: string | null;
  location: string | null;
  workplaceType: string | null;
  postedAt: string | null;
  jobUrl: string;
  listingId: string;
};

export const SearchLinkedInByUrlTypeCompany = {
  Company: "COMPANY",
} as const;
export type SearchLinkedInByUrlTypeCompany = ClosedEnum<
  typeof SearchLinkedInByUrlTypeCompany
>;

export type SearchLinkedInByUrlItemsCompany = {
  type: SearchLinkedInByUrlTypeCompany;
  name: string;
  profileUrl: string | null;
  summary: string | null;
  industry: string | null;
  location: string | null;
  followersCount: number | null;
};

export const SearchLinkedInByUrlTypePeople = {
  People: "PEOPLE",
} as const;
export type SearchLinkedInByUrlTypePeople = ClosedEnum<
  typeof SearchLinkedInByUrlTypePeople
>;

export const SearchLinkedInByUrlNetworkDistance = {
  Distance1: "DISTANCE_1",
  Distance2: "DISTANCE_2",
  Distance3: "DISTANCE_3",
  OutOfNetwork: "OUT_OF_NETWORK",
} as const;
export type SearchLinkedInByUrlNetworkDistance = OpenEnum<
  typeof SearchLinkedInByUrlNetworkDistance
>;

export type SearchLinkedInByUrlCurrentPosition = {
  company: string | null;
  role: string | null;
};

export type SearchLinkedInByUrlItemsPeople = {
  type: SearchLinkedInByUrlTypePeople;
  name: string;
  profileUrl: string | null;
  headline: string | null;
  location: string | null;
  profilePicture: string | null;
  networkDistance: SearchLinkedInByUrlNetworkDistance | null;
  currentPositions: Array<SearchLinkedInByUrlCurrentPosition>;
};

export const SearchLinkedInByUrlTypePost = {
  Post: "POST",
} as const;
export type SearchLinkedInByUrlTypePost = ClosedEnum<
  typeof SearchLinkedInByUrlTypePost
>;

export type SearchLinkedInByUrlAuthor = {
  name: string;
  profileUrl: string | null;
  headline: string | null;
  profilePicture: string | null;
  isCompany: boolean;
};

export type SearchLinkedInByUrlItemsPost = {
  type: SearchLinkedInByUrlTypePost;
  postUrl: string;
  text: string;
  date: number;
  likesCount: number;
  commentsCount: number;
  sharesCount: number;
  postUrn: string;
  postId: string;
  author: SearchLinkedInByUrlAuthor;
  isRepost: boolean;
};

export type SearchLinkedInByUrlItemsUnion =
  | Array<SearchLinkedInByUrlItemsPost>
  | Array<SearchLinkedInByUrlItemsPeople>
  | Array<SearchLinkedInByUrlItemsCompany>
  | Array<SearchLinkedInByUrlItemsJob>;

export type SearchLinkedInByUrlPaging = {
  start: number;
  count: number;
  total: number;
};

/**
 * Search results parsed from the LinkedIn URL
 */
export type SearchLinkedInByUrlResponse = {
  success: true;
  category: SearchLinkedInByUrlCategory;
  items:
    | Array<SearchLinkedInByUrlItemsPost>
    | Array<SearchLinkedInByUrlItemsPeople>
    | Array<SearchLinkedInByUrlItemsCompany>
    | Array<SearchLinkedInByUrlItemsJob>;
  paging: SearchLinkedInByUrlPaging;
  hasMore: boolean;
  /**
   * Credits consumed by this call (0 for free endpoints, cached results, or duplicates).
   */
  creditsUsed: number;
  /**
   * Seconds to wait before making another call of the same type. 0 means no wait needed.
   */
  retryAfter: number;
};

/** @internal */
export type SearchLinkedInByUrlRequest$Outbound = {
  url: string;
  start?: number | undefined;
  count?: number | undefined;
};

/** @internal */
export const SearchLinkedInByUrlRequest$outboundSchema: z.ZodMiniType<
  SearchLinkedInByUrlRequest$Outbound,
  SearchLinkedInByUrlRequest
> = z.object({
  url: z.string(),
  start: z.optional(z.int()),
  count: z.optional(z.int()),
});

export function searchLinkedInByUrlRequestToJSON(
  searchLinkedInByUrlRequest: SearchLinkedInByUrlRequest,
): string {
  return JSON.stringify(
    SearchLinkedInByUrlRequest$outboundSchema.parse(searchLinkedInByUrlRequest),
  );
}

/** @internal */
export const SearchLinkedInByUrlInternalServerErrorDetails$inboundSchema:
  z.ZodMiniType<SearchLinkedInByUrlInternalServerErrorDetails, unknown> =
    smartUnion([types.string(), z.array(types.string())]);

export function searchLinkedInByUrlInternalServerErrorDetailsFromJSON(
  jsonString: string,
): SafeParseResult<
  SearchLinkedInByUrlInternalServerErrorDetails,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      SearchLinkedInByUrlInternalServerErrorDetails$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'SearchLinkedInByUrlInternalServerErrorDetails' from JSON`,
  );
}

/** @internal */
export const SearchLinkedInByUrlInternalServerErrorError$inboundSchema:
  z.ZodMiniType<SearchLinkedInByUrlInternalServerErrorError, unknown> = z
    .object({
      code: types.string(),
      message: types.string(),
      docs: types.optional(types.string()),
      details: types.optional(
        smartUnion([types.string(), z.array(types.string())]),
      ),
    });

export function searchLinkedInByUrlInternalServerErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<
  SearchLinkedInByUrlInternalServerErrorError,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      SearchLinkedInByUrlInternalServerErrorError$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'SearchLinkedInByUrlInternalServerErrorError' from JSON`,
  );
}

/** @internal */
export const SearchLinkedInByUrlCode$inboundSchema: z.ZodMiniEnum<
  typeof SearchLinkedInByUrlCode
> = z.enum(SearchLinkedInByUrlCode);

/** @internal */
export const SearchLinkedInByUrlDaily$inboundSchema: z.ZodMiniType<
  SearchLinkedInByUrlDaily,
  unknown
> = z.object({
  current: types.number(),
  limit: types.number(),
});

export function searchLinkedInByUrlDailyFromJSON(
  jsonString: string,
): SafeParseResult<SearchLinkedInByUrlDaily, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchLinkedInByUrlDaily$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchLinkedInByUrlDaily' from JSON`,
  );
}

/** @internal */
export const SearchLinkedInByUrlWeekly$inboundSchema: z.ZodMiniType<
  SearchLinkedInByUrlWeekly,
  unknown
> = z.object({
  current: types.number(),
  limit: types.number(),
});

export function searchLinkedInByUrlWeeklyFromJSON(
  jsonString: string,
): SafeParseResult<SearchLinkedInByUrlWeekly, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchLinkedInByUrlWeekly$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchLinkedInByUrlWeekly' from JSON`,
  );
}

/** @internal */
export const SearchLinkedInByUrlTooManyRequestsError$inboundSchema:
  z.ZodMiniType<SearchLinkedInByUrlTooManyRequestsError, unknown> = z.object({
    code: SearchLinkedInByUrlCode$inboundSchema,
    message: types.string(),
    docs: types.optional(types.string()),
    retryAfter: types.number(),
    daily: types.nullable(z.lazy(() => SearchLinkedInByUrlDaily$inboundSchema)),
    weekly: types.nullable(
      z.lazy(() => SearchLinkedInByUrlWeekly$inboundSchema),
    ),
  });

export function searchLinkedInByUrlTooManyRequestsErrorFromJSON(
  jsonString: string,
): SafeParseResult<
  SearchLinkedInByUrlTooManyRequestsError,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      SearchLinkedInByUrlTooManyRequestsError$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'SearchLinkedInByUrlTooManyRequestsError' from JSON`,
  );
}

/** @internal */
export const SearchLinkedInByUrlUnprocessableEntityDetails$inboundSchema:
  z.ZodMiniType<SearchLinkedInByUrlUnprocessableEntityDetails, unknown> =
    smartUnion([types.string(), z.array(types.string())]);

export function searchLinkedInByUrlUnprocessableEntityDetailsFromJSON(
  jsonString: string,
): SafeParseResult<
  SearchLinkedInByUrlUnprocessableEntityDetails,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      SearchLinkedInByUrlUnprocessableEntityDetails$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'SearchLinkedInByUrlUnprocessableEntityDetails' from JSON`,
  );
}

/** @internal */
export const SearchLinkedInByUrlUnprocessableEntityError$inboundSchema:
  z.ZodMiniType<SearchLinkedInByUrlUnprocessableEntityError, unknown> = z
    .object({
      code: types.string(),
      message: types.string(),
      docs: types.optional(types.string()),
      details: types.optional(
        smartUnion([types.string(), z.array(types.string())]),
      ),
    });

export function searchLinkedInByUrlUnprocessableEntityErrorFromJSON(
  jsonString: string,
): SafeParseResult<
  SearchLinkedInByUrlUnprocessableEntityError,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      SearchLinkedInByUrlUnprocessableEntityError$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'SearchLinkedInByUrlUnprocessableEntityError' from JSON`,
  );
}

/** @internal */
export const SearchLinkedInByUrlGoneDetails$inboundSchema: z.ZodMiniType<
  SearchLinkedInByUrlGoneDetails,
  unknown
> = smartUnion([types.string(), z.array(types.string())]);

export function searchLinkedInByUrlGoneDetailsFromJSON(
  jsonString: string,
): SafeParseResult<SearchLinkedInByUrlGoneDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchLinkedInByUrlGoneDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchLinkedInByUrlGoneDetails' from JSON`,
  );
}

/** @internal */
export const SearchLinkedInByUrlGoneError$inboundSchema: z.ZodMiniType<
  SearchLinkedInByUrlGoneError,
  unknown
> = z.object({
  code: types.string(),
  message: types.string(),
  docs: types.optional(types.string()),
  details: types.optional(
    smartUnion([types.string(), z.array(types.string())]),
  ),
});

export function searchLinkedInByUrlGoneErrorFromJSON(
  jsonString: string,
): SafeParseResult<SearchLinkedInByUrlGoneError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchLinkedInByUrlGoneError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchLinkedInByUrlGoneError' from JSON`,
  );
}

/** @internal */
export const SearchLinkedInByUrlConflictDetails$inboundSchema: z.ZodMiniType<
  SearchLinkedInByUrlConflictDetails,
  unknown
> = smartUnion([types.string(), z.array(types.string())]);

export function searchLinkedInByUrlConflictDetailsFromJSON(
  jsonString: string,
): SafeParseResult<SearchLinkedInByUrlConflictDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      SearchLinkedInByUrlConflictDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchLinkedInByUrlConflictDetails' from JSON`,
  );
}

/** @internal */
export const SearchLinkedInByUrlConflictError$inboundSchema: z.ZodMiniType<
  SearchLinkedInByUrlConflictError,
  unknown
> = z.object({
  code: types.string(),
  message: types.string(),
  docs: types.optional(types.string()),
  details: types.optional(
    smartUnion([types.string(), z.array(types.string())]),
  ),
});

export function searchLinkedInByUrlConflictErrorFromJSON(
  jsonString: string,
): SafeParseResult<SearchLinkedInByUrlConflictError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchLinkedInByUrlConflictError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchLinkedInByUrlConflictError' from JSON`,
  );
}

/** @internal */
export const SearchLinkedInByUrlNotFoundDetails$inboundSchema: z.ZodMiniType<
  SearchLinkedInByUrlNotFoundDetails,
  unknown
> = smartUnion([types.string(), z.array(types.string())]);

export function searchLinkedInByUrlNotFoundDetailsFromJSON(
  jsonString: string,
): SafeParseResult<SearchLinkedInByUrlNotFoundDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      SearchLinkedInByUrlNotFoundDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchLinkedInByUrlNotFoundDetails' from JSON`,
  );
}

/** @internal */
export const SearchLinkedInByUrlNotFoundError$inboundSchema: z.ZodMiniType<
  SearchLinkedInByUrlNotFoundError,
  unknown
> = z.object({
  code: types.string(),
  message: types.string(),
  docs: types.optional(types.string()),
  details: types.optional(
    smartUnion([types.string(), z.array(types.string())]),
  ),
});

export function searchLinkedInByUrlNotFoundErrorFromJSON(
  jsonString: string,
): SafeParseResult<SearchLinkedInByUrlNotFoundError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchLinkedInByUrlNotFoundError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchLinkedInByUrlNotFoundError' from JSON`,
  );
}

/** @internal */
export const SearchLinkedInByUrlForbiddenDetails$inboundSchema: z.ZodMiniType<
  SearchLinkedInByUrlForbiddenDetails,
  unknown
> = smartUnion([types.string(), z.array(types.string())]);

export function searchLinkedInByUrlForbiddenDetailsFromJSON(
  jsonString: string,
): SafeParseResult<SearchLinkedInByUrlForbiddenDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      SearchLinkedInByUrlForbiddenDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchLinkedInByUrlForbiddenDetails' from JSON`,
  );
}

/** @internal */
export const SearchLinkedInByUrlForbiddenError$inboundSchema: z.ZodMiniType<
  SearchLinkedInByUrlForbiddenError,
  unknown
> = z.object({
  code: types.string(),
  message: types.string(),
  docs: types.optional(types.string()),
  details: types.optional(
    smartUnion([types.string(), z.array(types.string())]),
  ),
});

export function searchLinkedInByUrlForbiddenErrorFromJSON(
  jsonString: string,
): SafeParseResult<SearchLinkedInByUrlForbiddenError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchLinkedInByUrlForbiddenError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchLinkedInByUrlForbiddenError' from JSON`,
  );
}

/** @internal */
export const SearchLinkedInByUrlUnauthorizedDetails$inboundSchema:
  z.ZodMiniType<SearchLinkedInByUrlUnauthorizedDetails, unknown> = smartUnion([
    types.string(),
    z.array(types.string()),
  ]);

export function searchLinkedInByUrlUnauthorizedDetailsFromJSON(
  jsonString: string,
): SafeParseResult<SearchLinkedInByUrlUnauthorizedDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      SearchLinkedInByUrlUnauthorizedDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchLinkedInByUrlUnauthorizedDetails' from JSON`,
  );
}

/** @internal */
export const SearchLinkedInByUrlUnauthorizedError$inboundSchema: z.ZodMiniType<
  SearchLinkedInByUrlUnauthorizedError,
  unknown
> = z.object({
  code: types.string(),
  message: types.string(),
  docs: types.optional(types.string()),
  details: types.optional(
    smartUnion([types.string(), z.array(types.string())]),
  ),
});

export function searchLinkedInByUrlUnauthorizedErrorFromJSON(
  jsonString: string,
): SafeParseResult<SearchLinkedInByUrlUnauthorizedError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      SearchLinkedInByUrlUnauthorizedError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchLinkedInByUrlUnauthorizedError' from JSON`,
  );
}

/** @internal */
export const SearchLinkedInByUrlBadRequestDetails$inboundSchema: z.ZodMiniType<
  SearchLinkedInByUrlBadRequestDetails,
  unknown
> = smartUnion([types.string(), z.array(types.string())]);

export function searchLinkedInByUrlBadRequestDetailsFromJSON(
  jsonString: string,
): SafeParseResult<SearchLinkedInByUrlBadRequestDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      SearchLinkedInByUrlBadRequestDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchLinkedInByUrlBadRequestDetails' from JSON`,
  );
}

/** @internal */
export const SearchLinkedInByUrlBadRequestError$inboundSchema: z.ZodMiniType<
  SearchLinkedInByUrlBadRequestError,
  unknown
> = z.object({
  code: types.string(),
  message: types.string(),
  docs: types.optional(types.string()),
  details: types.optional(
    smartUnion([types.string(), z.array(types.string())]),
  ),
});

export function searchLinkedInByUrlBadRequestErrorFromJSON(
  jsonString: string,
): SafeParseResult<SearchLinkedInByUrlBadRequestError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      SearchLinkedInByUrlBadRequestError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchLinkedInByUrlBadRequestError' from JSON`,
  );
}

/** @internal */
export const SearchLinkedInByUrlCategory$inboundSchema: z.ZodMiniType<
  SearchLinkedInByUrlCategory,
  unknown
> = openEnums.inboundSchema(SearchLinkedInByUrlCategory);

/** @internal */
export const SearchLinkedInByUrlTypeJob$inboundSchema: z.ZodMiniEnum<
  typeof SearchLinkedInByUrlTypeJob
> = z.enum(SearchLinkedInByUrlTypeJob);

/** @internal */
export const SearchLinkedInByUrlItemsJob$inboundSchema: z.ZodMiniType<
  SearchLinkedInByUrlItemsJob,
  unknown
> = z.object({
  type: SearchLinkedInByUrlTypeJob$inboundSchema,
  title: types.string(),
  company: types.nullable(types.string()),
  companyUrl: types.nullable(types.string()),
  companyLogo: types.nullable(types.string()),
  location: types.nullable(types.string()),
  workplaceType: types.nullable(types.string()),
  postedAt: types.nullable(types.string()),
  jobUrl: types.string(),
  listingId: types.string(),
});

export function searchLinkedInByUrlItemsJobFromJSON(
  jsonString: string,
): SafeParseResult<SearchLinkedInByUrlItemsJob, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchLinkedInByUrlItemsJob$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchLinkedInByUrlItemsJob' from JSON`,
  );
}

/** @internal */
export const SearchLinkedInByUrlTypeCompany$inboundSchema: z.ZodMiniEnum<
  typeof SearchLinkedInByUrlTypeCompany
> = z.enum(SearchLinkedInByUrlTypeCompany);

/** @internal */
export const SearchLinkedInByUrlItemsCompany$inboundSchema: z.ZodMiniType<
  SearchLinkedInByUrlItemsCompany,
  unknown
> = z.object({
  type: SearchLinkedInByUrlTypeCompany$inboundSchema,
  name: types.string(),
  profileUrl: types.nullable(types.string()),
  summary: types.nullable(types.string()),
  industry: types.nullable(types.string()),
  location: types.nullable(types.string()),
  followersCount: types.nullable(types.number()),
});

export function searchLinkedInByUrlItemsCompanyFromJSON(
  jsonString: string,
): SafeParseResult<SearchLinkedInByUrlItemsCompany, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchLinkedInByUrlItemsCompany$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchLinkedInByUrlItemsCompany' from JSON`,
  );
}

/** @internal */
export const SearchLinkedInByUrlTypePeople$inboundSchema: z.ZodMiniEnum<
  typeof SearchLinkedInByUrlTypePeople
> = z.enum(SearchLinkedInByUrlTypePeople);

/** @internal */
export const SearchLinkedInByUrlNetworkDistance$inboundSchema: z.ZodMiniType<
  SearchLinkedInByUrlNetworkDistance,
  unknown
> = openEnums.inboundSchema(SearchLinkedInByUrlNetworkDistance);

/** @internal */
export const SearchLinkedInByUrlCurrentPosition$inboundSchema: z.ZodMiniType<
  SearchLinkedInByUrlCurrentPosition,
  unknown
> = z.object({
  company: types.nullable(types.string()),
  role: types.nullable(types.string()),
});

export function searchLinkedInByUrlCurrentPositionFromJSON(
  jsonString: string,
): SafeParseResult<SearchLinkedInByUrlCurrentPosition, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      SearchLinkedInByUrlCurrentPosition$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchLinkedInByUrlCurrentPosition' from JSON`,
  );
}

/** @internal */
export const SearchLinkedInByUrlItemsPeople$inboundSchema: z.ZodMiniType<
  SearchLinkedInByUrlItemsPeople,
  unknown
> = z.object({
  type: SearchLinkedInByUrlTypePeople$inboundSchema,
  name: types.string(),
  profileUrl: types.nullable(types.string()),
  headline: types.nullable(types.string()),
  location: types.nullable(types.string()),
  profilePicture: types.nullable(types.string()),
  networkDistance: types.nullable(
    SearchLinkedInByUrlNetworkDistance$inboundSchema,
  ),
  currentPositions: z.array(
    z.lazy(() => SearchLinkedInByUrlCurrentPosition$inboundSchema),
  ),
});

export function searchLinkedInByUrlItemsPeopleFromJSON(
  jsonString: string,
): SafeParseResult<SearchLinkedInByUrlItemsPeople, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchLinkedInByUrlItemsPeople$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchLinkedInByUrlItemsPeople' from JSON`,
  );
}

/** @internal */
export const SearchLinkedInByUrlTypePost$inboundSchema: z.ZodMiniEnum<
  typeof SearchLinkedInByUrlTypePost
> = z.enum(SearchLinkedInByUrlTypePost);

/** @internal */
export const SearchLinkedInByUrlAuthor$inboundSchema: z.ZodMiniType<
  SearchLinkedInByUrlAuthor,
  unknown
> = z.object({
  name: types.string(),
  profileUrl: types.nullable(types.string()),
  headline: types.nullable(types.string()),
  profilePicture: types.nullable(types.string()),
  isCompany: types.boolean(),
});

export function searchLinkedInByUrlAuthorFromJSON(
  jsonString: string,
): SafeParseResult<SearchLinkedInByUrlAuthor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchLinkedInByUrlAuthor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchLinkedInByUrlAuthor' from JSON`,
  );
}

/** @internal */
export const SearchLinkedInByUrlItemsPost$inboundSchema: z.ZodMiniType<
  SearchLinkedInByUrlItemsPost,
  unknown
> = z.object({
  type: SearchLinkedInByUrlTypePost$inboundSchema,
  postUrl: types.string(),
  text: types.string(),
  date: types.number(),
  likesCount: types.number(),
  commentsCount: types.number(),
  sharesCount: types.number(),
  postUrn: types.string(),
  postId: types.string(),
  author: z.lazy(() => SearchLinkedInByUrlAuthor$inboundSchema),
  isRepost: types.boolean(),
});

export function searchLinkedInByUrlItemsPostFromJSON(
  jsonString: string,
): SafeParseResult<SearchLinkedInByUrlItemsPost, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchLinkedInByUrlItemsPost$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchLinkedInByUrlItemsPost' from JSON`,
  );
}

/** @internal */
export const SearchLinkedInByUrlItemsUnion$inboundSchema: z.ZodMiniType<
  SearchLinkedInByUrlItemsUnion,
  unknown
> = smartUnion([
  z.array(z.lazy(() => SearchLinkedInByUrlItemsPost$inboundSchema)),
  z.array(z.lazy(() => SearchLinkedInByUrlItemsPeople$inboundSchema)),
  z.array(z.lazy(() => SearchLinkedInByUrlItemsCompany$inboundSchema)),
  z.array(z.lazy(() => SearchLinkedInByUrlItemsJob$inboundSchema)),
]);

export function searchLinkedInByUrlItemsUnionFromJSON(
  jsonString: string,
): SafeParseResult<SearchLinkedInByUrlItemsUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchLinkedInByUrlItemsUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchLinkedInByUrlItemsUnion' from JSON`,
  );
}

/** @internal */
export const SearchLinkedInByUrlPaging$inboundSchema: z.ZodMiniType<
  SearchLinkedInByUrlPaging,
  unknown
> = z.object({
  start: types.number(),
  count: types.number(),
  total: types.number(),
});

export function searchLinkedInByUrlPagingFromJSON(
  jsonString: string,
): SafeParseResult<SearchLinkedInByUrlPaging, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchLinkedInByUrlPaging$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchLinkedInByUrlPaging' from JSON`,
  );
}

/** @internal */
export const SearchLinkedInByUrlResponse$inboundSchema: z.ZodMiniType<
  SearchLinkedInByUrlResponse,
  unknown
> = z.object({
  success: types.literal(true),
  category: SearchLinkedInByUrlCategory$inboundSchema,
  items: smartUnion([
    z.array(z.lazy(() => SearchLinkedInByUrlItemsPost$inboundSchema)),
    z.array(z.lazy(() => SearchLinkedInByUrlItemsPeople$inboundSchema)),
    z.array(z.lazy(() => SearchLinkedInByUrlItemsCompany$inboundSchema)),
    z.array(z.lazy(() => SearchLinkedInByUrlItemsJob$inboundSchema)),
  ]),
  paging: z.lazy(() => SearchLinkedInByUrlPaging$inboundSchema),
  hasMore: types.boolean(),
  creditsUsed: types.number(),
  retryAfter: types.number(),
});

export function searchLinkedInByUrlResponseFromJSON(
  jsonString: string,
): SafeParseResult<SearchLinkedInByUrlResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchLinkedInByUrlResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchLinkedInByUrlResponse' from JSON`,
  );
}
