/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type SetEntry = {
  /**
   * Unique entry ID
   */
  id: string;
  type: string;
  label: string | null;
  content: string;
  scope: string;
  updatedAt: string;
};

/**
 * Context saved
 */
export type SetResponse = {
  success: true;
  entry: SetEntry;
  /**
   * Credits consumed (always 0 for workspace operations).
   */
  creditsUsed: number;
  /**
   * Seconds to wait (always 0 for workspace operations).
   */
  retryAfter: number;
};

export type DeleteRequest = {
  /**
   * Context type to delete
   */
  type: string;
  /**
   * Scope (defaults to "user")
   */
  scope?: string | undefined;
};

/**
 * Context deleted
 */
export type DeleteResponse = {
  success: true;
  /**
   * Credits consumed (always 0 for workspace operations).
   */
  creditsUsed: number;
  /**
   * Seconds to wait (always 0 for workspace operations).
   */
  retryAfter: number;
};

export type Schedule = {
  scheduleId: string;
  /**
   * Human-readable schedule name (e.g. 'DM Polling', 'Draft Send')
   */
  name: string;
  cron: string | null;
  isPaused: boolean;
  /**
   * ISO 8601 timestamp of last execution
   */
  lastRun: string | null;
  /**
   * ISO 8601 timestamp of next scheduled execution
   */
  nextRun: string | null;
  /**
   * Status of the last execution
   */
  lastStatus: any | null;
  /**
   * The endpoint URL this schedule invokes
   */
  destination: string;
};

/**
 * Cron schedules
 */
export type ListSchedulesResponse = {
  success: true;
  schedules: Array<Schedule>;
  /**
   * Credits consumed (always 0 for workspace operations).
   */
  creditsUsed: number;
  /**
   * Seconds to wait (always 0 for workspace operations).
   */
  retryAfter: number;
};

/**
 * Action to perform
 */
export const UpdateScheduleAction = {
  Pause: "pause",
  Resume: "resume",
  Delete: "delete",
} as const;
/**
 * Action to perform
 */
export type UpdateScheduleAction = ClosedEnum<typeof UpdateScheduleAction>;

export type UpdateScheduleRequestBody = {
  /**
   * Action to perform
   */
  action: UpdateScheduleAction;
};

export type UpdateScheduleRequest = {
  /**
   * Schedule ID
   */
  scheduleId: string;
  body: UpdateScheduleRequestBody;
};

/**
 * Schedule updated
 */
export type UpdateScheduleResponse = {
  success: true;
  /**
   * Credits consumed (always 0 for workspace operations).
   */
  creditsUsed: number;
  /**
   * Seconds to wait (always 0 for workspace operations).
   */
  retryAfter: number;
};

/** @internal */
export const SetEntry$inboundSchema: z.ZodMiniType<SetEntry, unknown> = z
  .object({
    id: types.string(),
    type: types.string(),
    label: types.nullable(types.string()),
    content: types.string(),
    scope: types.string(),
    updatedAt: types.string(),
  });

export function setEntryFromJSON(
  jsonString: string,
): SafeParseResult<SetEntry, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SetEntry$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SetEntry' from JSON`,
  );
}

/** @internal */
export const SetResponse$inboundSchema: z.ZodMiniType<SetResponse, unknown> = z
  .object({
    success: types.literal(true),
    entry: z.lazy(() => SetEntry$inboundSchema),
    creditsUsed: types.number(),
    retryAfter: types.number(),
  });

export function setResponseFromJSON(
  jsonString: string,
): SafeParseResult<SetResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SetResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SetResponse' from JSON`,
  );
}

/** @internal */
export type DeleteRequest$Outbound = {
  type: string;
  scope?: string | undefined;
};

/** @internal */
export const DeleteRequest$outboundSchema: z.ZodMiniType<
  DeleteRequest$Outbound,
  DeleteRequest
> = z.object({
  type: z.string(),
  scope: z.optional(z.string()),
});

export function deleteRequestToJSON(deleteRequest: DeleteRequest): string {
  return JSON.stringify(DeleteRequest$outboundSchema.parse(deleteRequest));
}

/** @internal */
export const DeleteResponse$inboundSchema: z.ZodMiniType<
  DeleteResponse,
  unknown
> = z.object({
  success: types.literal(true),
  creditsUsed: types.number(),
  retryAfter: types.number(),
});

export function deleteResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteResponse' from JSON`,
  );
}

/** @internal */
export const Schedule$inboundSchema: z.ZodMiniType<Schedule, unknown> = z
  .object({
    scheduleId: types.string(),
    name: types.string(),
    cron: types.nullable(types.string()),
    isPaused: types.boolean(),
    lastRun: types.nullable(types.string()),
    nextRun: types.nullable(types.string()),
    lastStatus: types.nullable(z.any()),
    destination: types.string(),
  });

export function scheduleFromJSON(
  jsonString: string,
): SafeParseResult<Schedule, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Schedule$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Schedule' from JSON`,
  );
}

/** @internal */
export const ListSchedulesResponse$inboundSchema: z.ZodMiniType<
  ListSchedulesResponse,
  unknown
> = z.object({
  success: types.literal(true),
  schedules: z.array(z.lazy(() => Schedule$inboundSchema)),
  creditsUsed: types.number(),
  retryAfter: types.number(),
});

export function listSchedulesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListSchedulesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListSchedulesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListSchedulesResponse' from JSON`,
  );
}

/** @internal */
export const UpdateScheduleAction$outboundSchema: z.ZodMiniEnum<
  typeof UpdateScheduleAction
> = z.enum(UpdateScheduleAction);

/** @internal */
export type UpdateScheduleRequestBody$Outbound = {
  action: string;
};

/** @internal */
export const UpdateScheduleRequestBody$outboundSchema: z.ZodMiniType<
  UpdateScheduleRequestBody$Outbound,
  UpdateScheduleRequestBody
> = z.object({
  action: UpdateScheduleAction$outboundSchema,
});

export function updateScheduleRequestBodyToJSON(
  updateScheduleRequestBody: UpdateScheduleRequestBody,
): string {
  return JSON.stringify(
    UpdateScheduleRequestBody$outboundSchema.parse(updateScheduleRequestBody),
  );
}

/** @internal */
export type UpdateScheduleRequest$Outbound = {
  scheduleId: string;
  body: UpdateScheduleRequestBody$Outbound;
};

/** @internal */
export const UpdateScheduleRequest$outboundSchema: z.ZodMiniType<
  UpdateScheduleRequest$Outbound,
  UpdateScheduleRequest
> = z.object({
  scheduleId: z.string(),
  body: z.lazy(() => UpdateScheduleRequestBody$outboundSchema),
});

export function updateScheduleRequestToJSON(
  updateScheduleRequest: UpdateScheduleRequest,
): string {
  return JSON.stringify(
    UpdateScheduleRequest$outboundSchema.parse(updateScheduleRequest),
  );
}

/** @internal */
export const UpdateScheduleResponse$inboundSchema: z.ZodMiniType<
  UpdateScheduleResponse,
  unknown
> = z.object({
  success: types.literal(true),
  creditsUsed: types.number(),
  retryAfter: types.number(),
});

export function updateScheduleResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateScheduleResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateScheduleResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateScheduleResponse' from JSON`,
  );
}
