/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { campaignsGetStatus } from "../../funcs/campaignsGetStatus.js";
import { GetCampaignStatusRequest$zodSchema } from "../../models/getcampaignstatusop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetCampaignStatusRequest$zodSchema,
};

export const tool$campaignsGetStatus: ToolDefinition<typeof args> = {
  name: "campaigns-get-status",
  description: `Query per-profile action status within a campaign

Returns which actions (message, reply, like, visit, connect) have been completed for each profile within a campaign. Replaces the slug-based filter endpoint — query by profile URLs instead of building slug lists. 0 credits, no rate limit.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await campaignsGetStatus(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
