/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { linkedinChatFindConversation } from "../../funcs/linkedinChatFindConversation.js";
import { FindLinkedInConversationRequest$zodSchema } from "../../models/findlinkedinconversationop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: FindLinkedInConversationRequest$zodSchema,
};

export const tool$linkedinChatFindConversation: ToolDefinition<typeof args> = {
  name: "linkedin-chat-find-conversation",
  description: `Find a conversation with a specific person

Find a conversation with a specific person by name. Two strategies tried in order:

1. **Resource slug search (free)**: if \`resourceSlug\` provided, searches message content for the slug and filters by participant name. This is the recommended approach for DM guard dedup — pass the unique part of your resource link.
2. **Inbox scan (1 credit/page)**: scans inbox pages looking for a participant name match. Used as fallback when no resource slug.

Optionally returns messages from the found conversation (\`includeMessages: true\`).

Max 5 pages searched in each strategy.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await linkedinChatFindConversation(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
