/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ReplyToLinkedInCommentRequest = {
  commentUrn: string;
  message: string;
  campaignSlug?: string | undefined;
  actionSlug?: string | undefined;
};

export const ReplyToLinkedInCommentRequest$zodSchema: z.ZodType<
  ReplyToLinkedInCommentRequest
> = z.object({
  actionSlug: z.string().optional(),
  campaignSlug: z.string().optional(),
  commentUrn: z.string(),
  message: z.string(),
});

export type ReplyToLinkedInCommentInternalServerErrorDetails =
  | string
  | Array<string>;

export const ReplyToLinkedInCommentInternalServerErrorDetails$zodSchema:
  z.ZodType<ReplyToLinkedInCommentInternalServerErrorDetails> = z.union([
    z.string(),
    z.array(z.string()),
  ]);

export type ReplyToLinkedInCommentInternalServerErrorError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const ReplyToLinkedInCommentInternalServerErrorError$zodSchema:
  z.ZodType<ReplyToLinkedInCommentInternalServerErrorError> = z.object({
    code: z.string(),
    details: z.union([
      z.string(),
      z.array(z.string()),
    ]).optional(),
    docs: z.string().optional(),
    message: z.string(),
  });

/**
 * The server encountered a situation it does not know how to handle.
 */
export type ReplyToLinkedInCommentInternalServerErrorResponseBody = {
  success?: boolean | undefined;
  error: ReplyToLinkedInCommentInternalServerErrorError;
};

export const ReplyToLinkedInCommentInternalServerErrorResponseBody$zodSchema:
  z.ZodType<ReplyToLinkedInCommentInternalServerErrorResponseBody> = z.object({
    error: z.lazy(() =>
      ReplyToLinkedInCommentInternalServerErrorError$zodSchema
    ),
    success: z.boolean().default(false),
  }).describe(
    "The server encountered a situation it does not know how to handle.",
  );

export type ReplyToLinkedInCommentTooManyRequestsDetails =
  | string
  | Array<string>;

export const ReplyToLinkedInCommentTooManyRequestsDetails$zodSchema: z.ZodType<
  ReplyToLinkedInCommentTooManyRequestsDetails
> = z.union([
  z.string(),
  z.array(z.string()),
]);

export type ReplyToLinkedInCommentTooManyRequestsError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const ReplyToLinkedInCommentTooManyRequestsError$zodSchema: z.ZodType<
  ReplyToLinkedInCommentTooManyRequestsError
> = z.object({
  code: z.string(),
  details: z.union([
    z.string(),
    z.array(z.string()),
  ]).optional(),
  docs: z.string().optional(),
  message: z.string(),
});

/**
 * Too many requests have been sent in a given amount of time.
 */
export type ReplyToLinkedInCommentTooManyRequestsResponseBody = {
  success?: boolean | undefined;
  error: ReplyToLinkedInCommentTooManyRequestsError;
};

export const ReplyToLinkedInCommentTooManyRequestsResponseBody$zodSchema:
  z.ZodType<ReplyToLinkedInCommentTooManyRequestsResponseBody> = z.object({
    error: z.lazy(() => ReplyToLinkedInCommentTooManyRequestsError$zodSchema),
    success: z.boolean().default(false),
  }).describe("Too many requests have been sent in a given amount of time.");

export type ReplyToLinkedInCommentUnprocessableEntityDetails =
  | string
  | Array<string>;

export const ReplyToLinkedInCommentUnprocessableEntityDetails$zodSchema:
  z.ZodType<ReplyToLinkedInCommentUnprocessableEntityDetails> = z.union([
    z.string(),
    z.array(z.string()),
  ]);

export type ReplyToLinkedInCommentUnprocessableEntityError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const ReplyToLinkedInCommentUnprocessableEntityError$zodSchema:
  z.ZodType<ReplyToLinkedInCommentUnprocessableEntityError> = z.object({
    code: z.string(),
    details: z.union([
      z.string(),
      z.array(z.string()),
    ]).optional(),
    docs: z.string().optional(),
    message: z.string(),
  });

/**
 * The request was well-formed but was unable to be followed due to semantic errors.
 */
export type ReplyToLinkedInCommentUnprocessableEntityResponseBody = {
  success?: boolean | undefined;
  error: ReplyToLinkedInCommentUnprocessableEntityError;
};

export const ReplyToLinkedInCommentUnprocessableEntityResponseBody$zodSchema:
  z.ZodType<ReplyToLinkedInCommentUnprocessableEntityResponseBody> = z.object({
    error: z.lazy(() =>
      ReplyToLinkedInCommentUnprocessableEntityError$zodSchema
    ),
    success: z.boolean().default(false),
  }).describe(
    "The request was well-formed but was unable to be followed due to semantic errors.",
  );

export type ReplyToLinkedInCommentGoneDetails = string | Array<string>;

export const ReplyToLinkedInCommentGoneDetails$zodSchema: z.ZodType<
  ReplyToLinkedInCommentGoneDetails
> = z.union([
  z.string(),
  z.array(z.string()),
]);

export type ReplyToLinkedInCommentGoneError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const ReplyToLinkedInCommentGoneError$zodSchema: z.ZodType<
  ReplyToLinkedInCommentGoneError
> = z.object({
  code: z.string(),
  details: z.union([
    z.string(),
    z.array(z.string()),
  ]).optional(),
  docs: z.string().optional(),
  message: z.string(),
});

/**
 * The requested content has been permanently deleted from the server.
 */
export type ReplyToLinkedInCommentGoneResponseBody = {
  success?: boolean | undefined;
  error: ReplyToLinkedInCommentGoneError;
};

export const ReplyToLinkedInCommentGoneResponseBody$zodSchema: z.ZodType<
  ReplyToLinkedInCommentGoneResponseBody
> = z.object({
  error: z.lazy(() => ReplyToLinkedInCommentGoneError$zodSchema),
  success: z.boolean().default(false),
}).describe(
  "The requested content has been permanently deleted from the server.",
);

export type ReplyToLinkedInCommentConflictDetails = string | Array<string>;

export const ReplyToLinkedInCommentConflictDetails$zodSchema: z.ZodType<
  ReplyToLinkedInCommentConflictDetails
> = z.union([
  z.string(),
  z.array(z.string()),
]);

export type ReplyToLinkedInCommentConflictError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const ReplyToLinkedInCommentConflictError$zodSchema: z.ZodType<
  ReplyToLinkedInCommentConflictError
> = z.object({
  code: z.string(),
  details: z.union([
    z.string(),
    z.array(z.string()),
  ]).optional(),
  docs: z.string().optional(),
  message: z.string(),
});

/**
 * The request conflicts with the current state of the server.
 */
export type ReplyToLinkedInCommentConflictResponseBody = {
  success?: boolean | undefined;
  error: ReplyToLinkedInCommentConflictError;
};

export const ReplyToLinkedInCommentConflictResponseBody$zodSchema: z.ZodType<
  ReplyToLinkedInCommentConflictResponseBody
> = z.object({
  error: z.lazy(() => ReplyToLinkedInCommentConflictError$zodSchema),
  success: z.boolean().default(false),
}).describe("The request conflicts with the current state of the server.");

export type ReplyToLinkedInCommentNotFoundDetails = string | Array<string>;

export const ReplyToLinkedInCommentNotFoundDetails$zodSchema: z.ZodType<
  ReplyToLinkedInCommentNotFoundDetails
> = z.union([
  z.string(),
  z.array(z.string()),
]);

export type ReplyToLinkedInCommentNotFoundError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const ReplyToLinkedInCommentNotFoundError$zodSchema: z.ZodType<
  ReplyToLinkedInCommentNotFoundError
> = z.object({
  code: z.string(),
  details: z.union([
    z.string(),
    z.array(z.string()),
  ]).optional(),
  docs: z.string().optional(),
  message: z.string(),
});

/**
 * The server cannot find the requested resource.
 */
export type ReplyToLinkedInCommentNotFoundResponseBody = {
  success?: boolean | undefined;
  error: ReplyToLinkedInCommentNotFoundError;
};

export const ReplyToLinkedInCommentNotFoundResponseBody$zodSchema: z.ZodType<
  ReplyToLinkedInCommentNotFoundResponseBody
> = z.object({
  error: z.lazy(() => ReplyToLinkedInCommentNotFoundError$zodSchema),
  success: z.boolean().default(false),
}).describe("The server cannot find the requested resource.");

export type ReplyToLinkedInCommentForbiddenDetails = string | Array<string>;

export const ReplyToLinkedInCommentForbiddenDetails$zodSchema: z.ZodType<
  ReplyToLinkedInCommentForbiddenDetails
> = z.union([
  z.string(),
  z.array(z.string()),
]);

export type ReplyToLinkedInCommentForbiddenError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const ReplyToLinkedInCommentForbiddenError$zodSchema: z.ZodType<
  ReplyToLinkedInCommentForbiddenError
> = z.object({
  code: z.string(),
  details: z.union([
    z.string(),
    z.array(z.string()),
  ]).optional(),
  docs: z.string().optional(),
  message: z.string(),
});

/**
 * The client does not have access rights to the content.
 */
export type ReplyToLinkedInCommentForbiddenResponseBody = {
  success?: boolean | undefined;
  error: ReplyToLinkedInCommentForbiddenError;
};

export const ReplyToLinkedInCommentForbiddenResponseBody$zodSchema: z.ZodType<
  ReplyToLinkedInCommentForbiddenResponseBody
> = z.object({
  error: z.lazy(() => ReplyToLinkedInCommentForbiddenError$zodSchema),
  success: z.boolean().default(false),
}).describe("The client does not have access rights to the content.");

export type ReplyToLinkedInCommentUnauthorizedDetails = string | Array<string>;

export const ReplyToLinkedInCommentUnauthorizedDetails$zodSchema: z.ZodType<
  ReplyToLinkedInCommentUnauthorizedDetails
> = z.union([
  z.string(),
  z.array(z.string()),
]);

export type ReplyToLinkedInCommentUnauthorizedError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const ReplyToLinkedInCommentUnauthorizedError$zodSchema: z.ZodType<
  ReplyToLinkedInCommentUnauthorizedError
> = z.object({
  code: z.string(),
  details: z.union([
    z.string(),
    z.array(z.string()),
  ]).optional(),
  docs: z.string().optional(),
  message: z.string(),
});

/**
 * Although HTTP specifies "unauthorized", this response means "unauthenticated". Authenticate to continue.
 */
export type ReplyToLinkedInCommentUnauthorizedResponseBody = {
  success?: boolean | undefined;
  error: ReplyToLinkedInCommentUnauthorizedError;
};

export const ReplyToLinkedInCommentUnauthorizedResponseBody$zodSchema:
  z.ZodType<ReplyToLinkedInCommentUnauthorizedResponseBody> = z.object({
    error: z.lazy(() => ReplyToLinkedInCommentUnauthorizedError$zodSchema),
    success: z.boolean().default(false),
  }).describe(
    "Although HTTP specifies \"unauthorized\", this response means \"unauthenticated\". Authenticate to continue.",
  );

export type ReplyToLinkedInCommentBadRequestDetails = string | Array<string>;

export const ReplyToLinkedInCommentBadRequestDetails$zodSchema: z.ZodType<
  ReplyToLinkedInCommentBadRequestDetails
> = z.union([
  z.string(),
  z.array(z.string()),
]);

export type ReplyToLinkedInCommentBadRequestError = {
  code: string;
  message: string;
  docs?: string | undefined;
  details?: string | Array<string> | undefined;
};

export const ReplyToLinkedInCommentBadRequestError$zodSchema: z.ZodType<
  ReplyToLinkedInCommentBadRequestError
> = z.object({
  code: z.string(),
  details: z.union([
    z.string(),
    z.array(z.string()),
  ]).optional(),
  docs: z.string().optional(),
  message: z.string(),
});

/**
 * The server cannot or will not process the request due to something that is perceived to be a client error.
 */
export type ReplyToLinkedInCommentBadRequestResponseBody = {
  success?: boolean | undefined;
  error: ReplyToLinkedInCommentBadRequestError;
};

export const ReplyToLinkedInCommentBadRequestResponseBody$zodSchema: z.ZodType<
  ReplyToLinkedInCommentBadRequestResponseBody
> = z.object({
  error: z.lazy(() => ReplyToLinkedInCommentBadRequestError$zodSchema),
  success: z.boolean().default(false),
}).describe(
  "The server cannot or will not process the request due to something that is perceived to be a client error.",
);

/**
 * Reply sent successfully
 */
export type ReplyToLinkedInCommentResponseBody = {
  success: boolean;
  replyUrn?: string | undefined;
  duplicate?: boolean | undefined;
};

export const ReplyToLinkedInCommentResponseBody$zodSchema: z.ZodType<
  ReplyToLinkedInCommentResponseBody
> = z.object({
  duplicate: z.boolean().optional(),
  replyUrn: z.string().optional(),
  success: z.boolean(),
}).describe("Reply sent successfully");

export type ReplyToLinkedInCommentResponse =
  | ReplyToLinkedInCommentResponseBody
  | ReplyToLinkedInCommentBadRequestResponseBody
  | ReplyToLinkedInCommentUnauthorizedResponseBody
  | ReplyToLinkedInCommentForbiddenResponseBody
  | ReplyToLinkedInCommentNotFoundResponseBody
  | ReplyToLinkedInCommentConflictResponseBody
  | ReplyToLinkedInCommentGoneResponseBody
  | ReplyToLinkedInCommentUnprocessableEntityResponseBody
  | ReplyToLinkedInCommentTooManyRequestsResponseBody
  | ReplyToLinkedInCommentInternalServerErrorResponseBody;

export const ReplyToLinkedInCommentResponse$zodSchema: z.ZodType<
  ReplyToLinkedInCommentResponse
> = z.union([
  z.lazy(() => ReplyToLinkedInCommentResponseBody$zodSchema),
  z.lazy(() => ReplyToLinkedInCommentBadRequestResponseBody$zodSchema),
  z.lazy(() => ReplyToLinkedInCommentUnauthorizedResponseBody$zodSchema),
  z.lazy(() => ReplyToLinkedInCommentForbiddenResponseBody$zodSchema),
  z.lazy(() => ReplyToLinkedInCommentNotFoundResponseBody$zodSchema),
  z.lazy(() => ReplyToLinkedInCommentConflictResponseBody$zodSchema),
  z.lazy(() => ReplyToLinkedInCommentGoneResponseBody$zodSchema),
  z.lazy(() => ReplyToLinkedInCommentUnprocessableEntityResponseBody$zodSchema),
  z.lazy(() => ReplyToLinkedInCommentTooManyRequestsResponseBody$zodSchema),
  z.lazy(() => ReplyToLinkedInCommentInternalServerErrorResponseBody$zodSchema),
]);
